### ISSUE TITLE
Maintains support of OpenSearch (auto disable features require by elasticsearch 7.10.1+)

### ISSUE THREAD

**Issue by h1lll0ck** [LuatixHQ/opencti#1601]
## Description

Upgrading to 5.0.1 from 5.0.0 now results in platform unable to start. There is an elasticsearch error that results in platform trying to re-init, but it's an existing installation so that results in an error.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
2. OpenCTI version: 5.0.0/5.0.1
3. OpenCTI client: N/A
4. Other environment details: Container deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create functioning OpenCTI 5.0.0 (in this case it started as 4.5.5 and was upgraded to 5.0.0 and was working) with data/etc
1. Stop/shutdown the platform/containers (and in this case reboot the host to upgrade the kernel) - not sure if this was a "clean" shutdown of platform, but the host rebooted so it was going to be stopped somehow
1. Start up platform using 5.0.1

## Expected Output

Platform starts as before, using an already initialized elasticsearch db

## Actual Output

Platform fails to start:

```
{"category":"APP","version":"5.0.1","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[REDIS] Redis 'Client base' client ready","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Python3 is available","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{
  "error": {
    "name": "ResponseError",
    "meta": {
      "body": {
        "error": {
          "root_cause": [
            {
              "type": "parsing_exception",
              "reason": "Unknown key for a START_OBJECT in [runtime_mappings].",
              "line": 1,
              "col": 279
            }
          ],
          "type": "parsing_exception",
          "reason": "Unknown key for a START_OBJECT in [runtime_mappings].",
          "line": 1,
          "col": 279
        },
        "status": 400
      },
      "statusCode": 400,
      "headers": {
        "date": "Tue, 28 Sep 2021 XX:XX:XX GMT",
        "content-type": "application/json; charset=UTF-8",
        "content-length": "263",
        "connection": "keep-alive",
        "access-control-allow-origin": "*",
        "server": "Jetty(8.1.12.v20130726)"
      },
      "meta": {
        "context": null,
        "request": {
          "params": {
            "method": "POST",
            "path": "/opencti_internal_objects*%2Copencti_stix_meta_objects*%2Copencti_stix_domain_objects*%2Copencti_stix_cyber_observables*%2Copencti_inferred_entities*/_search",
            "body": "{\"size\":200,\"sort\":[{\"standard_id.keyword\":\"asc\"}],\"query\":{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"match_phrase\":{\"entity_type.keyword\":\"MigrationStatus\"}},{\"match_phrase\":{\"parent_types.keyword\":\"MigrationStatus\"}}],\"minimum_should_match\":1}}],\"must_not\":[]}},\"runtime_mappings\":{}}",
            "querystring": "ignore_throttled=false&track_total_hits=true",
            "headers": {
              "user-agent": "elasticsearch-js/7.13.0 (linux 5.11.0-1019-aws-x64; Node.js v16.6.0)",
              "x-elastic-client-meta": "es=7.13.0,js=16.6.0,t=7.13.0,hc=16.6.0",
              "content-type": "application/json",
              "content-length": "281"
            },
            "timeout": 30000
          },
          "options": {},
          "id": 2
        },
        "name": "elasticsearch-js",
        "connection": {
          "url": "https://eshost/",
          "id": "https://eshost/",
          "headers": {},
          "deadCount": 0,
          "resurrectTimeout": 0,
          "_openRequests": 0,
          "status": "alive",
          "roles": {
            "master": true,
            "data": true,
            "ingest": true,
            "ml": false
          }
        },
        "attempts": 0,
        "aborted": false
      }
    }
  },
  "query": {
    "index": [
      "opencti_internal_objects*",
      "opencti_stix_meta_objects*",
      "opencti_stix_domain_objects*",
      "opencti_stix_cyber_observables*",
      "opencti_inferred_entities*"
    ],
    "ignore_throttled": false,
    "track_total_hits": true,
    "body": {
      "size": 200,
      "sort": [
        {
          "standard_id.keyword": "asc"
        }
      ],
      "query": {
        "bool": {
          "must": [
            {
              "bool": {
                "should": [
                  {
                    "match_phrase": {
                      "entity_type.keyword": "MigrationStatus"
                    }
                  },
                  {
                    "match_phrase": {
                      "parent_types.keyword": "MigrationStatus"
                    }
                  }
                ],
                "minimum_should_match": 1
              }
            }
          ],
          "must_not": []
        }
      },
      "runtime_mappings": {}
    }
  },
  "category": "APP",
  "version": "5.0.1",
  "level": "error",
  "message": "[ELASTICSEARCH] Paginate fail",
  "timestamp": "2021-09-28TXX:XX:XX.XXXZ"
}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] New platform detected, initialization...","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"error":{"name":"ConfigurationError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-09-28TXX:XX:XX.XXXZ","data":{"reason":"[INIT] Fail initialize schema, index already exists","http_status":500,"category":"technical"},"internalData":{}},"category":"APP","version":"5.0.1","level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] Platform initialization done","timestamp":"2021-09-28TXX:XX:XX.XXXZ"}

/opt/opencti/build/src/config/errors.js:8
  return new Exception();
         ^
ConfigurationError: A configuration error has occurred
    at error (/opt/opencti/build/src/config/errors.js:8:10)
    at ConfigurationError (/opt/opencti/build/src/config/errors.js:53:3)
    at /opt/opencti/build/src/initialization.js:142:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at initialization (/opt/opencti/build/src/initialization.js:379:20)
    at /opt/opencti/build/src/boot.js:7:16
```
 
## Additional information

The elasticsearch cluster appears to report no problems, but not sure how to confirm that properly.

```
$ curl 'https://eshost/_cat/indices'
green open opencti_stix_meta_relationships-000001             XXXX 5 1 9174795  15297   4.6gb   2.3gb
green open opencti_inferred_relationships-000001              XXXX 5 1       0      0     2kb     1kb
green open opencti_stix_domain_objects-000001                 XXXX 5 1  145959  46424   7.3gb     4gb
green open opencti_inferred_entities-000001                   XXXX 5 1       0      0     2kb     1kb
green open opencti_stix_cyber_observable_relationships-000001 XXXX 5 1      27      0 404.6kb 188.7kb
green open opencti_stix_sighting_relationships-000001         XXXX 5 1     606      0   1.8mb 933.8kb
green open opencti_internal_relationships-000001              XXXX 5 1    4413     35   3.6mb   1.8mb
green open opencti_internal_objects-000001                    XXXX 5 1     286    493  37.5mb   1.5mb
green open .kibana_1                                          XXXX 1 1       1      0  10.1kb     5kb
green open opencti_history-000001                             XXXX 5 1 2476050  33232   2.5gb   1.3gb
green open opencti_stix_cyber_observables-000001              XXXX 5 1  168822  57103 698.5mb 355.1mb
green open opencti_stix_meta_objects-000001                   XXXX 5 1   10158    110  24.3mb  12.1mb
green open opencti_stix_core_relationships-000001             XXXX 5 1  685248 168134 839.9mb 418.5mb
```

**Comment by richard-julien** [comment]
Hi @h1lll0ck , what are your version of elasticsearch?

**Comment by h1lll0ck** [comment]
Using AWS Elasticsearch/Opensearch service: `7.10`

```
$ curl 'https://eshost/'
{
  "name" : "XXXX",
  "cluster_name" : "XXXX:XXXX",
  "cluster_uuid" : "XXXX",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2021-07-08T21:51:39.338286Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by richard-julien** [comment]
Ok. In the 5.0.1 we introduce the support of specific ordering (observable value, marking, author) that require at least elasticsearch 7.12. So you need to upgrade your elastic to deploy the 5.0.1. If its not possible for you to do it quickly you can rollback to the 5.0.0 safely until an upgrade of your elastic.

**Comment by h1lll0ck** [comment]
Thank you for the information. That seems like a fairly significant dependency change for a patch release, and it wasn't obvious to me from any release notes/documentation (but I may have missed it). The breakage was not expected given the hotfix/patch level version change

The elasticseearch version is not easily changed (it is outsourced by design), which effectively blocks all future upgrades (and bug fixes).

Perhaps a version check can be performed to ensure the error message is more clear?

**Comment by richard-julien** [comment]
In fact its not really a dependency change, elastic 7.12 is the minimum version in the documentation since a lot of versions. Looks like it was working before with an older version of elasticsearch but it was not anticipated.
I understand it could be complex for you to upgrade your dependencies but we dont have the workforce capacity to maintains the compatibility with previous version when we introduce new capabilities.

Its is really impossible for you to upgrade please reach us on the slack channel.

We will add a version check in the future release to prevent this kind of cryptic error message.

Julien,

**Comment by h1lll0ck** [comment]
Thank for your reply. Sorry that I missed the elasticsearch dependency in the documentation. Given that AWS will probably not maintain any feature parity in their managed service, this makes running the whole system significantly more complex

**Comment by richard-julien** [comment]
So looks like you are not with the same issue because of users of opencti currently using opensearch that is for now a fork of the Elasticsearch version 7.10.2.

In order to continue to support opensearch has a possible alternative I reopen this issue to provide in 5.0.2 a way to deploy on this version with the new feature disable if needed.

**Comment by TechBurn0ut** [comment]
@richard-julien Can we get a list of those "Advanced" features that are required in 7.12?  Reason I ask is because we can take that back to AWS and at least research what is needed to get it fully supported.

**Comment by richard-julien** [comment]
I think today its only the advanced ordering introduce in 5.0.2 (markings, author, observable_value) that require runtime fields of elasticsearch 7.12
