### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by smclinden** [LuatixHQ/opencti#1620]
## Description

Just installed OpenCTI 5.0.1 and am getting an error on "yarn serv"

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 5.0.1
3. OpenCTI client: Frontend
4. Other environment details: Python 3.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Untared the 5.0.1 tarball
2. Created a Python 3.9 venv to install dependencies
3. Adjusted config files to match the syntax in the defaults

## Expected Output

I expected OpenCTI to start

## Actual Output

```
opencti/build/index.js:1
(()=>{var __webpack_modules__={4024:(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{"use strict";__webpack_require__.d(__webpack_exports__,{IV:()=>ACCESS_CONTROL,hY:()=>LOGIN_ACTION,o7:()=>LOGOUT_ACTION,sS:()=>UPLOAD_ACTION,_K:()=>USER_CREATION,nQ:()=>USER_DELETION,_4:()=>ROLE_CREATION,Oo:()=>ROLE_DELETION,Sm:()=>convertRelationToAction});const ACCESS_CONTROL="ACCESS_CONTROL",LOGIN_ACTION="LOGIN",LOGOUT_ACTION="LOGOUT",UPLOAD_ACTION="UPLOAD",USER_CREATION="USER_CREATION",USER_DELETION="USER_DELETION",ROLE_CREATION="ROLE_CREATION",ROLE_DELETION="ROLE_DELETION",convertRelationToAction=function(name,isAdd){void 0===isAdd&&(isAdd=!0);let convertName="UNDEFINED";return"has-role"===name&&(convertName="ROLE"),"member-of"===name&&(convertName="GROUP"),isAdd?`${convertName}_ADD`:`${convertName}_REMOVE`}},3234:(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{"use strict";__webpack_require__.d(__webpack_exports__,{Zx:()=>BUS_TOPICS,Sl:

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```
 
## Screenshots (optional)

**Comment by SamuelHassine** [comment]
Hello @smclinden,

After multiple attempts, I'm not able to reproduce your bug. Can you please put the log level to "debug" and copy/paste here the full output when you start the platform?

Thanks!

Kind regards,
Samuel

**Comment by smclinden** [comment]
I changed "info" to "debug" in production.json but I got the identical error.

**Comment by SamuelHassine** [comment]
What is your version of NodeJS / Yarn?

**Comment by smclinden** [comment]
I checked and Ubuntu 18.04 defaults to Node 12 (ugh!). So I did an NVM update to 14.18.0 and get this:

```
{"category":"APP","version":"5.0.1","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-10-11T12:18:57.320Z"}
{"error":{"name":"ConfigurationError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-10-11T12:18:57.340Z","data":{"reason":"ElasticSearch seems down","http_status":500,"category":"technical","error":"connect ECONNREFUSED 10.223.129.98:9200"},"
internalData":{}},"category":"APP","version":"5.0.1","level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-10-11T12:18:57.340Z"}
(node:258173) UnhandledPromiseRejectionWarning: ConfigurationError: A configuration error has occurred
    at error (/apps/usr/local/src/opencti/build/src/config/errors.js:8:10)
    at ConfigurationError (/apps/usr/local/src/opencti/build/src/config/errors.js:53:3)
    at /apps/usr/local/src/opencti/build/src/database/elasticSearch.js:189:15
    at process.async (internal/process/task_queues.js:95:5)
    at checkSystemDependencies (/apps/usr/local/src/opencti/build/src/initialization.js:113:40)
    at initialization (/apps/usr/local/src/opencti/build/src/initialization.js:372:3)
    at /apps/usr/local/src/opencti/build/src/boot.js:7:16
(Use `node --trace-warnings ...` to show where the warning was created)
(node:258173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unha
ndled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:258173) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SamuelHassine** [comment]
This time it's clearer: 

```{"error":{"name":"ConfigurationError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-10-11T12:18:57.340Z","data":{"reason":"ElasticSearch seems down","http_status":500,"category":"technical","error":"connect ECONNREFUSED 10.223.129.98:9200"},"```

**Comment by smclinden** [comment]
Oops. So I downgraded to Node 14.16.1 and restarted Elasticsearch and now I get:

```
{"category":"APP","version":"5.0.1","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-10-11T12:29:47.060Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-10-11T12:29:47.086Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-10-11T12:29:47.099Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-10-11T12:29:47.745Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[REDIS] Redis 'Client base' client ready","timestamp":"2021-10-11T12:29:47.754Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-10-11T12:29:47.754Z"}
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-10-11T12:29:47.758Z","data":{"reason":"SMTP seems down, disable the subscription manager if you dont want it","http_status":500,"category":"technical"},"internalDa
ta":{}},"category":"APP","version":"5.0.1","level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-10-11T12:29:47.758Z"}
(node:262846) UnhandledPromiseRejectionWarning: DatabaseError: A database error has occurred
    at error (/apps/usr/local/src/opencti/build/src/config/errors.js:8:10)
    at DatabaseError (/apps/usr/local/src/opencti/build/src/config/errors.js:45:3)
    at smtpIsAlive (/apps/usr/local/src/opencti/build/src/database/smtp.js:30:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at checkSystemDependencies (/apps/usr/local/src/opencti/build/src/initialization.js:126:53)
    at initialization (/apps/usr/local/src/opencti/build/src/initialization.js:372:3)
    at /apps/usr/local/src/opencti/build/src/boot.js:7:16
(Use `node --trace-warnings ...` to show where the warning was created)
(node:262846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unha
ndled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:262846) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SamuelHassine** [comment]
Ok, for the SMTP seems down, please take a look to the OpenCTI 5.0.0 release note (https://github.com/OpenCTI-Platform/opencti/releases/tag/5.0.0) and this issue (https://github.com/OpenCTI-Platform/opencti/issues/1615).

**Comment by smclinden** [comment]
Did that, now getting this:

```
{"category":"APP","version":"5.0.1","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-10-11T13:00:41.393Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-10-11T13:00:41.415Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-10-11T13:00:41.426Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-10-11T13:00:42.094Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[REDIS] Redis 'Client base' client ready","timestamp":"2021-10-11T13:00:42.102Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-10-11T13:00:42.102Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Python3 is available","timestamp":"2021-10-11T13:00:48.479Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2021-10-11T13:00:48.483Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2021-10-11T13:00:48.486Z"}
{"query":{"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"ignore_throttled":false,"track_total_hits":true,"body":{"size":200,"sort":[{"standard_id.keyword"
:"asc"}],"query":{"bool":{"must":[{"bool":{"should":[{"match_phrase":{"entity_type.keyword":"MigrationStatus"}},{"match_phrase":{"parent_types.keyword":"MigrationStatus"}}],"minimum_should_match":1}}],"must_not":[]}},"runtime_mappings":{}}},"category":"APP","version":"
5.0.1","level":"debug","message":"[ELASTICSEARCH] paginate","timestamp":"2021-10-11T13:00:48.488Z"}
{"error":{"name":"ResponseError","meta":{"body":{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [runtime_mappings].","line":1,"col":279}],"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [runtime_map
pings].","line":1,"col":279},"status":400},"statusCode":400,"headers":{"content-type":"application/json; charset=UTF-8","content-length":"263"},"meta":{"context":null,"request":{"params":{"method":"POST","path":"/opencti_internal_objects*%2Copencti_stix_meta_objects*%2
Copencti_stix_domain_objects*%2Copencti_stix_cyber_observables*%2Copencti_inferred_entities*/_search","body":"{\"size\":200,\"sort\":[{\"standard_id.keyword\":\"asc\"}],\"query\":{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"match_phrase\":{\"entity_type.keyword\":\"M
igrationStatus\"}},{\"match_phrase\":{\"parent_types.keyword\":\"MigrationStatus\"}}],\"minimum_should_match\":1}}],\"must_not\":[]}},\"runtime_mappings\":{}}","querystring":"ignore_throttled=false&track_total_hits=true","headers":{"user-agent":"elasticsearch-js/7.13.0
 (linux 5.4.0-77-generic-x64; Node.js v14.16.1)","x-elastic-client-meta":"es=7.13.0,js=14.16.1,t=7.13.0,hc=14.16.1","content-type":"application/json","content-length":"281"},"timeout":30000},"options":{},"id":2},"name":"elasticsearch-js","connection":{"url":"http://10.
223.129.98:9200/","id":"http://10.223.129.98:9200/","headers":{},"deadCount":0,"resurrectTimeout":0,"_openRequests":0,"status":"alive","roles":{"master":true,"data":true,"ingest":true,"ml":false}},"attempts":0,"aborted":false}}},"query":{"index":["opencti_internal_obje
cts*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"ignore_throttled":false,"track_total_hits":true,"body":{"size":200,"sort":[{"standard_id.keyword":"asc"}],"query":{"bool":{"must":[{"bool"
:{"should":[{"match_phrase":{"entity_type.keyword":"MigrationStatus"}},{"match_phrase":{"parent_types.keyword":"MigrationStatus"}}],"minimum_should_match":1}}],"must_not":[]}},"runtime_mappings":{}}},"category":"APP","version":"5.0.1","level":"error","message":"[ELASTI
CSEARCH] Paginate fail","timestamp":"2021-10-11T13:00:48.505Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] New platform detected, initialization...","timestamp":"2021-10-11T13:00:48.506Z"}
{"error":{"name":"ConfigurationError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-10-11T13:00:48.515Z","data":{"reason":"[INIT] Fail initialize schema, index already exists","http_status":500,"category":"technical"},"internalData":{}},"cate
gory":"APP","version":"5.0.1","level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-10-11T13:00:48.515Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] Platform initialization done","timestamp":"2021-10-11T13:00:48.516Z"}
(node:11251) UnhandledPromiseRejectionWarning: ConfigurationError: A configuration error has occurred
    at error (/apps/usr/local/src/opencti/build/src/config/errors.js:8:10)
    at ConfigurationError (/apps/usr/local/src/opencti/build/src/config/errors.js:53:3)
    at /apps/usr/local/src/opencti/build/src/initialization.js:142:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at initialization (/apps/usr/local/src/opencti/build/src/initialization.js:379:20)
    at /apps/usr/local/src/opencti/build/src/boot.js:7:16
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhan
dled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
root@UBTU-CS-P-3985:/apps/usr/local/src/opencti# 
```

**Comment by SamuelHassine** [comment]
This is linked to https://github.com/OpenCTI-Platform/opencti/issues/1601. So 2 solutions in this case:

1) Upgrade your ElasticSearch to >= 7.12
2) Wait for OpenCTI 5.0.2 which will ensure to not enable latest feature if ElasticSerarch is not supporting this.

As a reminder, prerequisites are: https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1.

Kind regards,
Samuel

**Comment by smclinden** [comment]
Upgraded Elasticsearch and everything appears to be working.
