### ISSUE TITLE
Workers no longer making progress on queued work:  queues not found

### ISSUE THREAD

**Issue by nickamon** [LuatixHQ/opencti#1664]
## Prerequisites

- [X] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [X] I went through old GitHub issues and couldn't find anything relevant
- [X] I googled the issue and didn't find anything relevant

## Description

My workers had stopped making progress.  I reviewed the RabbitMQ console and confirmed that there were no active consumers.  From researching the GitHub closed issues, I determined that the consumers were likely timing-out due to the length of time it was taking to process imported bundles.  I went with the suggested resolution of increasing the consumer ACK for RabbitMQ. I did so by mounting a new volume that contained the configuration change as shown below:
```
  rabbitmq:
    image: rabbitmq:3.9-management
    networks:
      - opencti
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - amqpdata:/var/lib/rabbitmq
      - ./20-rabbit-consumer-timeout.conf:/etc/rabbitmq/conf.d/20-rabbit-consumer-timeout.conf
    ports:
      - "15672:15672"
    restart: always
```
I subsequently ran the following command to restart the RabbitMQ container:
```docker-compose up -d```
But after this, I started getting a slew of errors in the worker logs and the RabbitMQ logs.  From reviewing the RabbitMQ console, it looks like the queues that were provisioned were no longer there, replaced via a new set of queues.  I can still see in the OpenCTI console, the queued work and the outstanding operations but this is not visible within the RabbitMQ console.  All the queues have 0 messages in there while previously they had 200K+.

These are the errors in the worker log:
```
INFO:pika.adapters.utils.connection_workflow:Pika version 1.2.0 connecting to ('172.22.0.3', 5672)
INFO:pika.adapters.utils.io_services_utils:Socket connected: <socket.socket fd=163, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.22.0.18', 50914), raddr=('172.22.0.3', 5672)>
INFO:pika.adapters.utils.connection_workflow:Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff413fbd3d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff413fbd3d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
INFO:pika.adapters.utils.connection_workflow:AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff413fbd3d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff413fbd3d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.blocking_connection:Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff413fbd3d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
INFO:pika.adapters.blocking_connection:Created channel=1
INFO:root:Thread for queue push_5233e035-9bd5-4979-a9c5-f710c75964dd started
WARNING:pika.channel:Received remote Channel.Close (404): "NOT_FOUND - no queue 'push_5233e035-9bd5-4979-a9c5-f710c75964dd' in vhost '/'" on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7ff413fbd3d0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
INFO:root:Thread for queue push_5233e035-9bd5-4979-a9c5-f710c75964dd terminated
Exception in thread Thread-99:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/opencti-worker/worker.py", line 230, in run
    self.channel.basic_consume(
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1627, in basic_consume
    return self._basic_consume_impl(
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1696, in _basic_consume_impl
    self._flush_output(ok_result.is_ready)
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1339, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (404, "NOT_FOUND - no queue 'push_5233e035-9bd5-4979-a9c5-f710c75964dd' in vhost '/'")
```

RabbitMQ logs have these errors repeating:
```
2021-10-22 19:55:19.442130+00:00 [info] <0.9598.0> connection <0.9598.0> (172.22.0.21:36346 -> 172.22.0.3:5672): user 'rabbit' authenticated and granted access to vhost '/'
2021-10-22 19:55:19.445776+00:00 [erro] <0.9607.0> Channel error on connection <0.9598.0> (172.22.0.21:36346 -> 172.22.0.3:5672, vhost: '/', user: 'rabbit'), channel 1:
2021-10-22 19:55:19.445776+00:00 [erro] <0.9607.0> operation basic.consume caused a channel exception not_found: no queue 'push_6625ec28-0553-4c72-a14c-7f3d37923d67' in vhost '/'
2021-10-22 19:55:19.469255+00:00 [info] <0.9613.0> accepting AMQP connection <0.9613.0> (172.22.0.12:47854 -> 172.22.0.3:5672)
2021-10-22 19:55:19.471904+00:00 [info] <0.9613.0> connection <0.9613.0> (172.22.0.12:47854 -> 172.22.0.3:5672): user 'rabbit' authenticated and granted access to vhost '/'
2021-10-22 19:55:19.475021+00:00 [erro] <0.9622.0> Channel error on connection <0.9613.0> (172.22.0.12:47854 -> 172.22.0.3:5672, vhost: '/', user: 'rabbit'), channel 1:
2021-10-22 19:55:19.475021+00:00 [erro] <0.9622.0> operation basic.consume caused a channel exception not_found: no queue 'push_5233e035-9bd5-4979-a9c5-f710c75964dd' in vhost '/'
2021-10-22 19:55:19.503924+00:00 [info] <0.9628.0> accepting AMQP connection <0.9628.0> (172.22.0.21:36356 -> 172.22.0.3:5672)
2021-10-22 19:55:19.507157+00:00 [info] <0.9628.0> connection <0.9628.0> (172.22.0.21:36356 -> 172.22.0.3:5672): user 'rabbit' authenticated and granted access to vhost '/'
2021-10-22 19:55:19.510482+00:00 [erro] <0.9637.0> Channel error on connection <0.9628.0> (172.22.0.21:36356 -> 172.22.0.3:5672, vhost: '/', user: 'rabbit'), channel 1:
2021-10-22 19:55:19.510482+00:00 [erro] <0.9637.0> operation basic.consume caused a channel exception not_found: no queue 'push_5233e035-9bd5-4979-a9c5-f710c75964dd' in vhost '/'
```
These are the available queues:
```


Overview | Messages | Message rates | +/-
-- | -- | -- | --

listen_483534ad-9b92-4d62-9ddf-92a4db09841a | classic | D Args | idle | 0 | 0 | 0 |   |   |  
listen_56181ea2-c3f1-471d-9d8a-4fe99c8af97f | classic | D Args | idle | 0 | 0 | 0 |   |   |  
listen_6862e7fa-cec6-41e6-b991-03e985eaa68c | classic | D Args | idle | 0 | 0 | 0 |   |   |  
listen_817e6e14-f925-4557-a66e-83b3f0323ef7 | classic | D Args | idle | 0 | 0 | 0 |   |   |  
listen_bebaf6ca-504f-49a9-8001-a4dc413d81cb | classic | D Args | idle | 0 | 0 | 0 |   |   |  
listen_df3ab36d-8735-412f-8f61-2fbb922b5ce8 | classic | D Args | idle | 0 | 0 | 0 |   |   |  
push_483534ad-9b92-4d62-9ddf-92a4db09841a | classic | D Args | idle | 0 | 0 | 0 |   |   |  
push_56181ea2-c3f1-471d-9d8a-4fe99c8af97f | classic | D Args | idle | 0 | 0 | 0 |   |   |  
push_6862e7fa-cec6-41e6-b991-03e985eaa68c | classic | D Args | idle | 0 | 0 | 0 |   |   |  
push_817e6e14-f925-4557-a66e-83b3f0323ef7 | classic | D Args | idle | 0 | 0 | 0 |   |   |  
push_bebaf6ca-504f-49a9-8001-a4dc413d81cb | classic | D Args | idle | 0 | 0 | 0 |   |   |  
push_df3ab36d-8735-412f-8f61-2fbb922b5ce8 | classic
```

Here are my connector configs:
```
{
  "data": {
    "connectors": [
      {
        "id": "6DF756BA-0B26-4CB2-8110-3DE0050083D1",
        "name": "AlienVault",
        "connector_state": "{\"latest_pulse_timestamp\": \"2021-10-22T00:03:56.301000\", \"last_run\": 1634861898}",
        "config": {
          "listen": "listen_6DF756BA-0B26-4CB2-8110-3DE0050083D1",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_6DF756BA-0B26-4CB2-8110-3DE0050083D1",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "6862e7fa-cec6-41e6-b991-03e985eaa68c",
        "name": "History",
        "connector_state": "{\"connectorLastEventId\": \"1634909330640-0\"}",
        "config": {
          "listen": "listen_6862e7fa-cec6-41e6-b991-03e985eaa68c",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_6862e7fa-cec6-41e6-b991-03e985eaa68c",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "b1a5316e-121f-4244-8f99-cfdce1b5197d",
        "name": "Common Vulnerabilities and Exposures",
        "connector_state": "{\"last_run\": 1634572128}",
        "config": {
          "listen": "listen_b1a5316e-121f-4244-8f99-cfdce1b5197d",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_b1a5316e-121f-4244-8f99-cfdce1b5197d",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "6625ec28-0553-4c72-a14c-7f3d37923d67",
        "name": "MITRE ATT&CK",
        "connector_state": "{\"last_run\": 1634835921}",
        "config": {
          "listen": "listen_6625ec28-0553-4c72-a14c-7f3d37923d67",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_6625ec28-0553-4c72-a14c-7f3d37923d67",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "817e6e14-f925-4557-a66e-83b3f0323ef7",
        "name": "OpenCTI",
        "connector_state": "{\"last_run\": 1634573123}",
        "config": {
          "listen": "listen_817e6e14-f925-4557-a66e-83b3f0323ef7",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_817e6e14-f925-4557-a66e-83b3f0323ef7",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "bebaf6ca-504f-49a9-8001-a4dc413d81cb",
        "name": "ExportFileCsv",
        "connector_state": "null",
        "config": {
          "listen": "listen_bebaf6ca-504f-49a9-8001-a4dc413d81cb",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_bebaf6ca-504f-49a9-8001-a4dc413d81cb",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "483534ad-9b92-4d62-9ddf-92a4db09841a",
        "name": "ImportReport",
        "connector_state": "null",
        "config": {
          "listen": "listen_483534ad-9b92-4d62-9ddf-92a4db09841a",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_483534ad-9b92-4d62-9ddf-92a4db09841a",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "56181ea2-c3f1-471d-9d8a-4fe99c8af97f",
        "name": "ImportFileStix",
        "connector_state": "null",
        "config": {
          "listen": "listen_56181ea2-c3f1-471d-9d8a-4fe99c8af97f",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_56181ea2-c3f1-471d-9d8a-4fe99c8af97f",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "df3ab36d-8735-412f-8f61-2fbb922b5ce8",
        "name": "ExportFileStix2",
        "connector_state": "null",
        "config": {
          "listen": "listen_df3ab36d-8735-412f-8f61-2fbb922b5ce8",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_df3ab36d-8735-412f-8f61-2fbb922b5ce8",
          "push_exchange": "amqp.worker.exchange"
        }
      },
      {
        "id": "5233e035-9bd5-4979-a9c5-f710c75964dd",
        "name": "Malpedia",
        "connector_state": "null",
        "config": {
          "listen": "listen_5233e035-9bd5-4979-a9c5-f710c75964dd",
          "listen_exchange": "amqp.connector.exchange",
          "push": "push_5233e035-9bd5-4979-a9c5-f710c75964dd",
          "push_exchange": "amqp.worker.exchange"
        }
      }
    ]
  }
}
```

Questions:

- What caused this behavior, I thought the RabbitMQ configuration uses persistent queues and persistent messages?  Why does there appear to be a new set of queues and what happened to the queued messages?
- What do you recommend I do to resolve the issue?  Do I have to delete all queued work?  How do I get queues that the workers are expecting reprovisioned within Rabbit?
- I was using the AlientVault connector.  How can I know the last pulse it read in so that I can update its config after resolving the issue to start importing again from the missing pulses?

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.3 LTS (docker)
2. OpenCTI version: opencti/platform:5.0.0
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:
```
docker ps 

CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS                 PORTS                                                                                                           NAMES
b71f93d7d3ff   opencti/worker:5.0.0                                   "python3 worker.py"      21 minutes ago   Up 21 minutes                                                                                                                          docker_worker_2
3388e6b74853   opencti/worker:5.0.0                                   "python3 worker.py"      21 minutes ago   Up 21 minutes                                                                                                                          docker_worker_3
9529dbe6c89a   opencti/worker:5.0.0                                   "python3 worker.py"      21 minutes ago   Up 21 minutes                                                                                                                          docker_worker_1
ca33f14b4fb9   opencti/worker:5.0.0                                   "python3 worker.py"      21 minutes ago   Up 21 minutes                                                                                                                          docker_worker_4
33c5994947b0   rabbitmq:3.9-management                                "docker-entrypoint.s…"   7 hours ago      Up 30 minutes          4369/tcp, 5671-5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   docker_rabbitmq_1
c0e15eaffe2b   opencti/connector-opencti:5.0.1                        "/entrypoint.sh"         10 days ago      Up 23 minutes                                                                                                                          opencti_connector-opencti_1
2cac2e8ba9c1   opencti/connector-cve:5.0.1                            "/entrypoint.sh"         10 days ago      Up 10 days                                                                                                                             cve_connector-cve_1
33bb620a79ab   opencti/connector-alienvault:5.0.1                     "/entrypoint.sh"         2 weeks ago      Up 4 days                                                                                                                              alienvault_connector-alienvault_1
b6167640df39   nginxproxy/nginx-proxy                                 "/app/docker-entrypo…"   2 weeks ago      Up 7 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                                   docker_reverse_1
1a897376bd3a   opencti/connector-malpedia:5.0.1                       "/entrypoint.sh"         3 weeks ago      Up 2 weeks                                                                                                                             malpedia_connector-malpedia_1
c7dea352aa9a   opencti/connector-mitre:5.0.1                          "/entrypoint.sh"         3 weeks ago      Up 2 weeks                                                                                                                             mitre_connector-mitre_1
603fd635d090   opencti/connector-export-file-stix:5.0.0               "/entrypoint.sh"         3 weeks ago      Up 7 hours                                                                                                                             docker_connector-export-file-stix_1
761fab11385b   opencti/connector-import-file-stix:5.0.0               "/entrypoint.sh"         3 weeks ago      Up 7 hours                                                                                                                             docker_connector-import-file-stix_1
5bf638985457   opencti/connector-export-file-csv:5.0.0                "/entrypoint.sh"         3 weeks ago      Up 7 hours                                                                                                                             docker_connector-export-file-csv_1
4ecef6b36082   opencti/connector-import-report:5.0.0                  "/entrypoint.sh"         3 weeks ago      Up 7 hours                                                                                                                             docker_connector-import-report_1
b76a71d6b093   opencti/connector-history:5.0.0                        "/entrypoint.sh"         3 weeks ago      Up 7 hours                                                                                                                             docker_connector-history_1
6740bed75409   opencti/platform:5.0.0                                 "/sbin/tini -- node …"   3 weeks ago      Up 7 hours                                                                                                                             docker_opencti_1
74a886fd3fa7   minio/minio:RELEASE.2021-09-15T04-54-25Z               "/usr/bin/docker-ent…"   3 weeks ago      Up 7 hours (healthy)   9000/tcp                                                                                                        docker_minio_1
62888a005e9a   redis:6.2.5                                            "docker-entrypoint.s…"   3 weeks ago      Up 7 hours             6379/tcp                                                                                                        docker_redis_1
53929bd4feb0   docker.elastic.co/elasticsearch/elasticsearch:7.14.1   "/bin/tini -- /usr/l…"   3 weeks ago      Up 7 hours             9200/tcp, 9300/tcp                                                                                              docker_elasticsearch_1
```
Thanks!

**Comment by richard-julien** [comment]
Hi @nickamon ,
`
But after this, I started getting a slew of errors in the worker logs and the RabbitMQ logs. From reviewing the RabbitMQ console, it looks like the queues that were provisioned were no longer there, replaced via a new set of queues. I can still see in the OpenCTI console, the queued work and the outstanding operations but this is not visible within the RabbitMQ console. All the queues have 0 messages in there while previously they had 200K+`

Looks like you loose your rabbitmq data when you restarted it.
If rabbitmq data are loose, workers will try to access queues that doest not exist anymore, you have to restart your workers.
The connectors need also to be restarted to recreate their queues and resend bundles according to the connector state.

You need to check your docker volumes and do some testing to validate rabbitmq can be restarted without losing the data.

**Comment by nickamon** [comment]
Thanks @richard-julien, I did restart both my workers and connectors and still get the same no queues errors.  I don't think the connectors will automatically recreate the queues when they restart because as shown in my earlier output, that data seems to be stored in OpenCTI.  Is there a way to clear it manually from OpenCTI and then restart the connectors so that they recreate the queues?

I'm surprised though, I used the docker-compose file provided by the project and I'm surprised the default configuration doesn't already configure RabbitMQ to be persistent.  Seems like that would be a sensible default?  I'll look into that further.

**Comment by richard-julien** [comment]
Yes you're right the connector will not recreate the queue if they are already referenced in opencti.
I think you need to:
1. Stop connectors and workers
2. delete all connectors through the opencti UI
3. Restart connectors
4. Restart workers

For the docker compose file is a way to quickly start an OpenCTI but its not the target to provide a configuration that you can simply put in production.

**Comment by nickamon** [comment]
Thanks, will give that a try. 

As for the compose, sure I agree, one can not put it into production without testing/customization but there should be sensible defaults like persistent RabbitMQ queues.  In any case, I research how to implement that and contribute that as a pull request.

**Comment by GraemeMeyerGT** [comment]
@nickamon did you get anywhere with this? I am totally new to rabbitmq, but our system is consistently spewing out the same errors as you, and we also deploy via the Docker Compose configuration provided by the devs.

**Comment by alice-debra** [comment]
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
