### ISSUE TITLE
Manual Deployment, post install queries

### ISSUE THREAD

**Issue by faustus25** [LuatixHQ/opencti#1686]
## Description

Post deployment questions following manual setup as not enough information or none found in Notion.so knowledge base

**Note OpenCTI is running and accessible via GUI but post install issue remain

## Environment

1. OS {Ubuntu 20.04}
2. OpenCTI version: {OpenCTI 5.0.0 }
3. OpenCTI client: {frontend }
4. Other environment details:

## Reproducible Steps
1. Connectors Page Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

`{"user":{"ip":"::ffff:10.24.61.10","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","referer":"https://opencti.org/dashboard/data/connectors"},"type":"READ_ERROR","operation_query":"query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}","inner_relation_creation":0,"operation":"WorkersStatusQuery","time":46,"variables":{},"size":2,"error":{"stacktrace":["Error: Request failed with status code 400","at createError (/opt/opencti/node_modules/axios/lib/core/createError.js:16:15)","at settle (/opt/opencti/node_modules/axios/lib/core/settle.js:17:12)","at IncomingMessage.handleStreamEnd (/opt/opencti/node_modules/axios/lib/adapters/http.js:260:11)","at IncomingMessage.emit (events.js:412:35)","at endReadableNT (internal/streams/readable.js:1317:12)","at processTicksAndRejections (internal/process/task_queues.js:82:21)"]},"category":"APP","version":"5.0.0","level":"error","message":"API Call","timestamp":"2021-10-26T16:02:13.771Z"}`

RabbitMQ status: RabbitMQ disconnected
RabbitMQ installed with version 3.9.8 

`sudo systemctl status rabbitmq-server.service
● rabbitmq-server.service - RabbitMQ broker
     Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-10-26 11:42:33 EDT; 14s ago
   Main PID: 792043 (beam.smp)
      Tasks: 28 (limit: 9447)
     Memory: 130.1M
     CGroup: /system.slice/rabbitmq-server.service
             ├─792043 /usr/lib/erlang/erts-12.0.4/bin/beam.smp -W w -MBas ageffcbf -MHas ageffcbf -MBlmbcs 512 -MHlmbcs 512 -MMmcs 30 -P 1048576 -t 5000000 -stbt db -zdbbl 128000 -sbwt non>
             ├─792072 erl_child_setup 32768
             ├─792115 /usr/lib/erlang/erts-12.0.4/bin/epmd -daemon
             ├─792142 inet_gethost 4
             └─792143 inet_gethost 4
Oct 26 11:42:32 server rabbitmq-server[792043]:   Doc guides:  https://rabbitmq.com/documentation.html
Oct 26 11:42:32 server rabbitmq-server[792043]:   Support:     https://rabbitmq.com/contact.html
Oct 26 11:42:32 server rabbitmq-server[792043]:   Tutorials:   https://rabbitmq.com/getstarted.html
Oct 26 11:42:32 server rabbitmq-server[792043]:   Monitoring:  https://rabbitmq.com/monitoring.html
Oct 26 11:42:32 server rabbitmq-server[792043]:   Logs: /var/log/rabbitmq/rabbit@server.log
Oct 26 11:42:32 server rabbitmq-server[792043]:         /var/log/rabbitmq/rabbit@server_upgrade.log
Oct 26 11:42:32 server rabbitmq-server[792043]:         <stdout>
Oct 26 11:42:32 server rabbitmq-server[792043]:   Config file(s): (none)
Oct 26 11:42:33 server rabbitmq-server[792043]:   Starting broker... completed with 3 plugins.
Oct 26 11:42:33 server systemd[1]: Started RabbitMQ broker.`

UFW status:
5672,15672/tcp             ALLOW       Anywhere

2. INFO:root:Listing Threat-Actors with filters null.
-ever present warning message; how do you get data to appear under Threat-Actors
**Note data has been imported from connectors such as MITRE,CVE,Cybercrime-Tracker however Threat-Actors section remains empty

3. What is the best method to run `yarn serv` at reboot post manual install? (cronjob, bash script etc.)

4. What is the best method to update OpenCTI via git or other? (v5.0.0 current version installed while v5.0.3 available)

5. MISP Connector returns no events: (I have tried changing the tags to import and orgs too but no luck)

`python3 connectors/external-import/misp/src/misp.py
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: d459d8b7-e90b-450c-9e92-cb8dab83f17f
INFO:root:Starting ping alive thread
INFO:root:Initiate work for d459d8b7-e90b-450c-9e92-cb8dab83f17f
INFO:root:Connector last run: 2021-10-23 15:41:07
INFO:root:Fetching MISP events with args: {"tags": {}, "publish_timestamp": 1635018067, "limit": 50, "page": 1}
INFO:root:MISP returned 0 events.
INFO:root:Connector successfully run (0 events have been processed), storing last_run as 1635264948
INFO:root:Reporting work update_received opencti-work--f14b5c04-655d-4f10-b8dd-b9184c2e365a`

**Comment by faustus25** [comment]
Resolved a number of issues:
1. Connectors Page Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

RabbitMQ status: RabbitMQ disconnected
RabbitMQ installed with version 3.9.8

I resolved both these errors when I upgraded to v5.0.3 as now the Connectors and RabbitMQ status appear on the OpenCTI dashboard. I believe this was linked to my existing yarn install via npm.
I decided to remove the npm install of Yarn and install from the Ubuntu repo:
https://linuxize.com/post/how-to-install-yarn-on-ubuntu-20-04/
The main problem was yarn kept referencing on older Node version 12.6.2 from a past install in the global config and would not start. Likely conflicting between and apt package manager install and npm install of yarn.

2. INFO:root:Listing Threat-Actors with filters null.
-ever present warning message; how do you get data to appear under Threat-Actors
**Note data has been imported from connectors such as MITRE,CVE,Cybercrime-Tracker however Threat-Actors section remains empty
Still not populated with data.

3.What is the best method to run yarn serv at reboot post manual install? (cronjob, bash script etc.)
Still searching for an answer to this.

4. What is the best method to update OpenCTI via git or other? (v5.0.0 current version installed while v5.0.3 available)
For the moment I upgraded to v5.0.3 via downloading the tar file, extracting it and moving the old v5.0.0 to a backup folder. I then diffed the config files for workers and connectors to see if I can copy directly to v5.0.3 plus the production config file.

**Comment by faustus25** [comment]
For item 2, this a manual effort, will see if MISP can populate it.

For item 3, will use this as a reference #1083 

For item 4, likely a git clone is the best route here.
