### ISSUE TITLE
[INIT] Fail initialize schema, index already exists

### ISSUE THREAD

**Issue by kenoby-dev** [LuatixHQ/opencti#1778]
## Description

Running `docker-compose up -d` to start the container.  The opencti/platform container continues to restart.

Checking the logs:
```
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"[INIT] Fail initialize schema, index already exists"},"internalData":{},"name":"ConfigurationError","time_thrown":"2021-12-17T15:01:50.477Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-12-17T15:01:50.477Z","version":"5.1.2"}
```

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Ubuntu 20.04

2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
OpenCTI 5.1.2

3. OpenCTI client: { e.g. frontend or python }
frontend

4. Other environment details:
Volumes are persisted and bound to an Azure File Share, using the following as an example:

```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    volumes:
      - /mnt/opencti/esdata:/usr/share/elasticsearch/data
```

The `/mnt/opencti` path on the host is mapped to an Azure File Share.

## Reproducible Steps

Steps to create the smallest reproducible scenario:

- New install
- No data in file share
- Mounts removed
- Attempt to start the container - `sudo docker-compose up -d`

## Expected Output

Containers should start.

## Actual Output

Error occurs: `[INIT] Fail initialize schema, index already exists`

Data exists in the File Share.
 
## Additional information

```
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-12-17T15:07:59.694Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-12-17T15:07:59.991Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-12-17T15:08:00.016Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-12-17T15:08:00.082Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Client base' client ready","timestamp":"2021-12-17T15:08:00.098Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-12-17T15:08:00.099Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2021-12-17T15:08:01.208Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2021-12-17T15:08:01.217Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2021-12-17T15:08:01.222Z","version":"5.1.2"}
{"category":"APP","level":"debug","message":"[ELASTICSEARCH] paginate","query":{"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"MigrationStatus"}},{"match_phrase":{"parent_types.keyword":"MigrationStatus"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true},"timestamp":"2021-12-17T15:08:01.226Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[INIT] New platform detected, initialization...","timestamp":"2021-12-17T15:08:02.051Z","version":"5.1.2"}
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","error":{"meta":{"body":{"error":{"index":"opencti_inferred_entities-000001","index_uuid":"GxgtcXIITumRqhMiggwNBA","reason":"index [opencti_inferred_entities-000001/GxgtcXIITumRqhMiggwNBA] already exists","root_cause":[{"index":"opencti_inferred_entities-000001","index_uuid":"GxgtcXIITumRqhMiggwNBA","reason":"index [opencti_inferred_entities-000001/GxgtcXIITumRqhMiggwNBA] already exists","type":"resource_already_exists_exception"}],"type":"resource_already_exists_exception"},"status":400},"headers":{"content-length":"469","content-type":"application/json; charset=UTF-8","warning":"299 Elasticsearch-7.15.1-83c34f456ae29d60e94d886e455e6a3409bba9ed \"Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.15/security-minimal-setup.html to enable security.\"","x-elastic-product":"Elasticsearch"},"meta":{"aborted":false,"attempts":1,"connection":{"_openRequests":7,"deadCount":0,"headers":{},"id":"http://elasticsearch:9200/","resurrectTimeout":0,"roles":{"data":true,"ingest":true,"master":true,"ml":false},"status":"alive","url":"http://elasticsearch:9200/"},"context":null,"name":"elasticsearch-js","request":{"id":21,"options":{},"params":{"body":"{\"aliases\":{\"opencti_inferred_entities\":{}}}","headers":{"content-length":"44","content-type":"application/json","user-agent":"elasticsearch-js/7.13.0 (linux 5.11.0-1022-azure-x64; Node.js v16.6.0)","x-elastic-client-meta":"es=7.13.0,js=16.6.0,t=7.13.0,hc=16.6.0"},"method":"PUT","path":"/opencti_inferred_entities-000001","querystring":"","timeout":30000}}},"statusCode":400},"name":"ResponseError"},"http_status":500,"reason":"Error creating index"},"internalData":{},"name":"DatabaseError","time_thrown":"2021-12-17T15:08:43.722Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-12-17T15:08:43.724Z","version":"5.1.2"}

/opt/opencti/build/src/config/errors.js:8
  return new Exception();
         ^
DatabaseError: A database error has occurred
    at error (/opt/opencti/build/src/config/errors.js:8:10)
    at DatabaseError (/opt/opencti/build/src/config/errors.js:45:3)
    at /opt/opencti/build/src/database/elasticSearch.js:420:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2021-12-17T15:08:43.730Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-12-17T15:09:14.925Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-12-17T15:09:15.037Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-12-17T15:09:15.106Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-12-17T15:09:15.176Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Client base' client ready","timestamp":"2021-12-17T15:09:15.198Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-12-17T15:09:15.199Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2021-12-17T15:09:16.377Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2021-12-17T15:09:16.387Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2021-12-17T15:09:16.392Z","version":"5.1.2"}
{"category":"APP","level":"debug","message":"[ELASTICSEARCH] paginate","query":{"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"MigrationStatus"}},{"match_phrase":{"parent_types.keyword":"MigrationStatus"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true},"timestamp":"2021-12-17T15:09:16.396Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[INIT] New platform detected, initialization...","timestamp":"2021-12-17T15:09:16.461Z","version":"5.1.2"}
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"[INIT] Fail initialize schema, index already exists"},"internalData":{},"name":"ConfigurationError","time_thrown":"2021-12-17T15:09:16.477Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-12-17T15:09:16.478Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2021-12-17T15:09:16.480Z","version":"5.1.2"}

/opt/opencti/build/src/config/errors.js:8
  return new Exception();
         ^
ConfigurationError: A configuration error has occurred
    at error (/opt/opencti/build/src/config/errors.js:8:10)
    at ConfigurationError (/opt/opencti/build/src/config/errors.js:53:3)
    at /opt/opencti/build/src/initialization.js:148:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at initialization (/opt/opencti/build/src/initialization.js:386:20)
    at /opt/opencti/build/src/boot.js:7:16
```

**Comment by nor3th** [comment]
Hey @kenoby-dev 

Could you maybe share your docker compose file?
Any chance that this issue is related to this one? https://github.com/OpenCTI-Platform/opencti/issues/1445#issuecomment-868796127

Regards

**Comment by kenoby-dev** [comment]
Yes, it looks like a similar issue to #1445.

I tried doing what was suggested in the post:

```
$ service docker stop
$ rm -Rf /var/lib/docker/* # purge everything really everything
$ service docker start
```

But the opencti platform could still not be initialized.

On further inspection, the first error looks like:

```
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","error":{"meta":{"body":{"error":{"index":"opencti_stix_meta_objects-000001","index_uuid":"aNv3N2TdTAOLRWNhJERhiw","reason":"index [opencti_stix_meta_objects-000001/aNv3N2TdTAOLRWNhJERhiw] already exists","root_cause":[{"index":"opencti_stix_meta_objects-000001","index_uuid":"aNv3N2TdTAOLRWNhJERhiw","reason":"index [opencti_stix_meta_objects-000001/aNv3N2TdTAOLRWNhJERhiw] already exists","type":"resource_already_exists_exception"}],"type":"resource_already_exists_exception"},"status":400},"headers":{"content-length":"469","content-type":"application/json; charset=UTF-8","warning":"299 Elasticsearch-7.15.1-83c34f456ae29d60e94d886e455e6a3409bba9ed \"Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.15/security-minimal-setup.html to enable security.\"","x-elastic-product":"Elasticsearch"},"meta":{"aborted":false,"attempts":1,"connection":{"_openRequests":7,"deadCount":0,"headers":{},"id":"http://elasticsearch:9200/","resurrectTimeout":0,"roles":{"data":true,"ingest":true,"master":true,"ml":false},"status":"alive","url":"http://elasticsearch:9200/"},"context":null,"name":"elasticsearch-js","request":{"id":20,"options":{},"params":{"body":"{\"aliases\":{\"opencti_stix_meta_objects\":{}}}","headers":{"content-length":"44","content-type":"application/json","user-agent":"elasticsearch-js/7.13.0 (linux 5.11.0-1022-azure-x64; Node.js v16.6.0)","x-elastic-client-meta":"es=7.13.0,js=16.6.0,t=7.13.0,hc=16.6.0"},"method":"PUT","path":"/opencti_stix_meta_objects-000001","querystring":"","timeout":30000}}},"statusCode":400},"name":"ResponseError"},"http_status":500,"reason":"Error creating index"},"internalData":{},"name":"DatabaseError","time_thrown":"2021-12-18T07:28:31.979Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-12-18T07:28:31.980Z","version":"5.1.2"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2021-12-18T07:28:31.986Z","version":"5.1.2"}
```

I've attached my docker-compose.yml and .env file (with passwords changed).
[.env.txt](https://github.com/OpenCTI-Platform/opencti/files/7738920/default.env.txt)
[docker-compose.yml.txt](https://github.com/OpenCTI-Platform/opencti/files/7738921/docker-compose.yml.txt)

**Comment by nor3th** [comment]
Hey @kenoby-dev 

What ended up working for me was to reduce the amount of services (connectors) in the docker compose file to a minimum and then the initialization worked out. After that adding connectors to the docker compose file worked smoothly.

Regards

**Comment by kenoby-dev** [comment]
Thanks for the suggestion.

I've reduced everything to the bare minimum and I'm still receiving the same error.  I've purged my volumes and all the es data and it still remains.

Not really sure what else I can do...

**Comment by kenoby-dev** [comment]
OK - i've tried again this time not using externally mounted storage and it seems to have worked.

@nor3th - Were you able to successfully mount external storage?

**Comment by nor3th** [comment]
Hey

No I only used the docker volumes, but I am also running a few services like elastic separately since they are also in use for a few other things. Does the initialization also fail when all other services except the elastic volume are using the Azure File Share?

Regards

**Comment by kenoby-dev** [comment]
OK, I tried that and it worked.

I can have the other 3 volumes mounted to an Azure File Share and esdata is local.  When I mount esdata to an external file share I get the error.

**Comment by nor3th** [comment]
Hey

This is interesting, but if you use the external Azure Elastic service, then it should be possible to have the DB in the Azure cloud.

Regards
