### ISSUE TITLE
Elasticsearch SSL CA configuration meaning changed in 5.1.2, but didn't get documented

### ISSUE THREAD

**Issue by dcode** [LuatixHQ/opencti#1882]
## Description

In the 5.1.2 release (commit https://github.com/OpenCTI-Platform/opencti/commit/adc3dd2e8bf72160013cbfa0cf72f407c8ee6da6), the semantics of `ELASTICSEARCH__SSL__CA` changed from being the contents of the certificate to the filename of the certificate.

https://github.com/OpenCTI-Platform/opencti/blob/ceba60014e24b2dd66e6452a5fc70d9ab09b3adf/opencti-platform/opencti-graphql/src/database/engine.js#L121

When migrating from an earlier version to a more recent version, this would cause the error shown below in "Actual Output"

## Environment

1. OS (where OpenCTI server runs): Official Docker container
2. OpenCTI version: >=5.1.2 (above stack trace is 5.1.4)
3. OpenCTI client: frontend
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure OpenCTI to run from docker
2. Specify the contents of a certificate file in the environment variable `ELASTICSEARCH__SSL__CA`
3. Run the `opencti/platform:5.1.4` container 

## Expected Output

I expected the value to be added to the Elasticsearch configuration as it previously did.

## Actual Output

Error output and stack trace

```
Error: ENAMETOOLONG: name too long, open '-----BEGIN CERTIFICATE-----
<certificate data truncated>
-----END CERTIFICATE-----
    at Object.openSync (node:fs:582:3)
    at readFileSync (node:fs:450:35)
    at Object.moduleId [as 8147] (/opt/opencti/build/src/database/engine.js:121:44)
    at __webpack_require__ (/opt/opencti/build/webpack/bootstrap:19:22)
    at Object.moduleId [as 4053] (/opt/opencti/build/index.js:1:705294)
    at __webpack_require__ (/opt/opencti/build/webpack/bootstrap:19:22)
    at Object.moduleId [as 6227] (/opt/opencti/build/index.js:1:368505)
    at __webpack_require__ (/opt/opencti/build/webpack/bootstrap:19:22)
    at /opt/opencti/build/webpack/startup:3:1
    at Object.<anonymous> (/opt/opencti/build/index.js:1:2718437)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

 
## Additional information

The easiest fix to this is just document the setting in the Notion docs. It could also be useful to validate the value passed in the environment variable is a valid filename that exists prior to attempting to read it. If it doesn't, you could either fall back to the prior behavior to just pass the contents as the certificate, or gracefully emit an error message.

**Comment by SamuelHassine** [comment]
Hello @dcode,

I've introduced `elasticsearch:ssl:ca_plain` (`ELASTICSEARCH__SSL__CA_PLAIN`) to be able to pass the plain text certificate. Current parameter is in used to pass a path so we don't introduce a new breaking change in this version.

Both parameters are now documented here: https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a.

Kind regards,
Sam
