### ISSUE TITLE
OTXv2.RetryError: 'Exceeded maximum number of retries'

### ISSUE THREAD

**Issue by izm1chael** [LuatixHQ/opencti#1950]
## Description
The Alienvault OTX connector appears to be having some issues with either timing out reciving to many 504 errors

## Environment

1. OS Ubuntu 20.04
2. OpenCTI version: 5.2.0
3. OpenCTI client: N/A
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. `python alienvault.py`

## Expected Output

The exoected output for this connector would be pulling OTX pulses

## Actual Output

```
INFO:root:Running pulse importer (update data: False, guess malware: True, guess cve: True, relationships: True, patterns_indicates: True)...
Traceback (most recent call last):
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2010-01-01T00%3A00%3A00&page=6 (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/OTXv2.py", line 178, in get
    response = self.session().get(
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2010-01-01T00%3A00%3A00&page=6 (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/opencti/connectors/external-import/alienvault/src/alienvault.py", line 8, in <module>
    connector.run()
  File "/usr/share/opencti/connectors/external-import/alienvault/src/alienvault/core.py", line 247, in run
    pulse_import_state = self.pulse_importer.run(current_state, work_id)
  File "/usr/share/opencti/connectors/external-import/alienvault/src/alienvault/importer.py", line 94, in run
    pulses = self._fetch_subscribed_pulses(latest_pulse_datetime)
  File "/usr/share/opencti/connectors/external-import/alienvault/src/alienvault/importer.py", line 154, in _fetch_subscribed_pulses
    pulses = self.client.get_pulses_subscribed(modified_since)
  File "/usr/share/opencti/connectors/external-import/alienvault/src/alienvault/client.py", line 27, in get_pulses_subscribed
    pulse_data = self.otx.getsince(modified_since, limit=limit)
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/OTXv2.py", line 431, in getsince
    return self.getall(limit=limit, modified_since=timestamp, max_page=max_page, max_items=max_items, iter=False)
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/OTXv2.py", line 404, in getall
    return self.walkapi(
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/OTXv2.py", line 385, in walkapi
    return list(self.walkapi_iter(url, max_page=max_page, max_items=max_items, method=method, body=body))
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/OTXv2.py", line 366, in walkapi_iter
    data = self.get(next_page_url)
  File "/opt/opencti_venv/opencti_external_venv/lib/python3.9/site-packages/OTXv2.py", line 187, in get
    raise RetryError()
OTXv2.RetryError: 'Exceeded maximum number of retries'
```

## Additional information
This has only started to recently happen, I would imagine it is less of an OpenCTI issue and more of an OTXv2 issue, however it is breaking this connector so raising it here

**Comment by richard-julien** [comment]
Looks like a problem on OTX api side, dont know how we can help.
Does OTX prevent too many calls to the API? Depending of the limitation of the API maybe you had to implements some throttling on the connector side. Can you provide more information on the OTX Api?
