### ISSUE TITLE
v5.2.3 platform initialization doesn't create 2 indexes: opencti_inferred_relationships and opencti_inferred_entities 

### ISSUE THREAD

**Issue by kudrew** [LuatixHQ/opencti#1997]
## Description
Im starting my 5.2.3 instance of the platform and loading the dashboard/ home page gives the generic "check with your opencti maintainers error".
The logs indicate the indexes: opencti_inferred_relationships and opencti_inferred_entities are not in elasticsearch.
im checking my instance of 5.14 and the two indexes are there. so this is puzzling

my workaround: create the indexes manually: opencti_inferred_relationships and opencti_inferred_entities
## Environment

1. OS (where OpenCTI server runs): docker
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 5.2.3
3. OpenCTI client: { e.g. frontend or python } ui + backend
4. Other environment details:

log:
```
{"category":"APP","error":{"data":{"category":"technical","error":{"meta":{"body":{"error":{"index":"opencti_inferred_relationships","index_uuid":"_na_","reason":"no such index [opencti_inferred_relationships]","resource.id":"opencti_inferred_relationships","resource.type":"index_or_alias","root_cause":[{"index":"opencti_inferred_relationships","index_uuid":"_na_","reason":"no such index [opencti_inferred_relationships]","resource.id":"opencti_inferred_relationships","resource.type":"index_or_alias","type":"index_not_found_exception"}],"type":"index_not_found_exception"},"status":404},"headers":{"content-length":"509","content-type":"application/json; charset=UTF-8"},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":13,"deadCount":0,"headers":{},"id":"http://10.150.12.77:9200/","resurrectTimeout":0,"roles":{"data":true,"ingest":true,"master":true,"ml":false},"status":"alive","url":"http://10.150.12.77:9200/"},"context":null,"name":"elasticsearch-js","request":{"id":7819,"options":{},"params":{"body":"{\"query\":{\"bool\":{\"must\":[{\"range\":{\"created_at\":{\"format\":\"strict_date_optional_time\",\"lt\":\"2022-03-27T19:40:08.000Z\"}}},{\"bool\":{\"should\":[{\"bool\":{\"should\":[{\"match_phrase\":{\"entity_type.keyword\":\"stix-core-relationship\"}},{\"match_phrase\":{\"parent_types.keyword\":\"stix-core-relationship\"}}],\"minimum_should_match\":1}}],\"minimum_should_match\":1}}],\"must_not\":[]}}}","headers":{"content-length":"366","content-type":"application/json","user-agent":"elasticsearch-js/7.17.0 (linux 5.4.144+-x64; Node.js v16.6.0)","x-elastic-client-meta":"es=7.17.0,js=16.6.0,t=7.17.0,hc=16.6.0"},"method":"POST","path":"/opencti_stix_core_relationships*%2Copencti_inferred_relationships/_count","querystring":"","timeout":30000}}},"statusCode":404},"name":"ResponseError"},"http_status":500,"query":{"body":{"query":{"bool":{"must":[{"range":{"created_at":{"format":"strict_date_optional_time","lt":"2022-03-27T19:40:08.000Z"}}},{"bool":{"minimum_should_match":1,"should":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"stix-core-relationship"}},{"match_phrase":{"parent_types.keyword":"stix-core-relationship"}}]}}]}}],"must_not":[]}}},"index":["opencti_stix_core_relationships*","opencti_inferred_relationships"]},"reason":"Count data fail"},"stacktrace":["DatabaseError: A database error has occurred","at error (/opt/opencti/build/src/config/errors.js:8:10)","at DatabaseError (/opt/opencti/build/src/config/errors.js:40:48)","at /opt/opencti/build/src/database/engine.js:664:13","at runMicrotasks (<anonymous>)","at processTicksAndRejections (node:internal/process/task_queues:96:5)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"DashboardStixCoreRelationshipsNumberQuery","operation_query":"query DashboardStixCoreRelationshipsNumberQuery($type:String$endDate:DateTime){stixCoreRelationshipsNumber(type:$type endDate:$endDate){total count}}","size":71,"time":47,"timestamp":"2022-03-28T19:40:08.951Z","type":"READ_ERROR","user":{"ip":"::ffff:130.211.0.166","referer":"https://dashboard?","user_id":"6adcc576-24eb-4627-b467-5e6510771b44"},"variables":{"endDate":"2022-03-27T15:40:08-04:00","type":"stix-core-relationship"},"version":"5.2.3"}
```

**Comment by alice-debra** [comment]
Hello @kudrew,
Due to a lack of recent activity on this issue, we will proceed to close it for now. Apologies for the lack of response regarding this issue. If you're still experiencing the same problem, please don't hesitate to reopen the issue. We sincerely thank you for your feedback.
Kind regards,
Alice
