### ISSUE TITLE
Platform data(old version) are too old to start on version(new version)

### ISSUE THREAD

**Issue by zero060699** [LuatixHQ/opencti#2034]
## Prerequisites
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"business","http_status":500,"reason":"Your platform data (5.2.4) are too old to start on version 5.2.5"},"internalData":{},"name":"UnsupportedError","time_thrown":"2022-04-21T06:22:04.458Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2022-04-21T06:22:04.458Z","version":"5.2.4"}
UnsupportedError: Unsupported operation
    at error (/opt/opencti/build/src/config/errors.js:8:10)
    at UnsupportedError (/opt/opencti/build/src/config/errors.js:62:51)
    at isCompatiblePlatform (/opt/opencti/build/src/initialization.js:360:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at platformInit (/opt/opencti/build/src/initialization.js:383:7)
    at boot (/opt/opencti/build/src/boot.js:9:3)

## Description

Can anyone give a solution about version? When the vendor hasn't released a new update yet, system return the notification "Your platform data () are too old to start on version ()

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: Opencti 5.2.4
3. OpenCTI client: Docker

**Comment by nor3th** [comment]
Hey 

It seems like you are trying to run the current development version (5.2.5, the `rolling` docker image) which is undergoing some STIX 2.1 adaptions. Since the version isn't finished yet and is still under heavy development as well (+ the migration scripts aren't written yet), it's no surprise that you are seeing this error.

Regards

**Comment by zero060699** [comment]
> Contributor
Hello,
I'm not trying to run the new version, I'm still run old version, I think the vendor should be change this error to notification or the other better solution.

Regards

**Comment by nor3th** [comment]
Hey @zero060699 

Ok, that's odd. Could you please share your docker compose file?

Regards

**Comment by alice-debra** [comment]
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
