### ISSUE TITLE
Report sortBy causes query to hang

### ISSUE THREAD

**Issue by rabbipigeon** [LuatixHQ/opencti#2171]
## Description

I Tried to sort reports by status thinking that it will group them by status so i clicked on status and octi kept reporting an error.

## Environment

OpenCTI is running in a docker container 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Reports 
2. Click on status column

## Additional information

Logs show
```
{
  "category": "APP",
  "error": {
    "stacktrace": [
      "GraphQLError: Variable \"$orderBy\" got invalid value \"status_id\"; Value \"status_id\" does not exist in \"ReportsOrdering\" enum.",
      "at /opt/opencti/build/node_modules/graphql/execution/values.js:147:11",
      "at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:154:9)",
      "at coerceInputValue (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:32:10)",
      "at coerceVariableValues (/opt/opencti/build/node_modules/graphql/execution/values.js:132:52)",
      "at getVariableValues (/opt/opencti/build/node_modules/graphql/execution/values.js:45:21)",
      "at buildExecutionContext (/opt/opencti/build/node_modules/graphql/execution/execute.js:280:45)",
      "at execute (/opt/opencti/build/node_modules/graphql/execution/execute.js:116:22)",
      "at k (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:497:20)",
      "at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:403:28)",
      "at runMicrotasks (<anonymous>)",
      "at processTicksAndRejections (node:internal/process/task_queues:96:5)",
      "at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:433:24)"
    ]
  },
  "inner_relation_creation": 0,
  "level": "error",
  "message": "API Call",
  "operation": "ReportsLinesPaginationQuery",
  "operation_query": "query ReportsLinesPaginationQuery($search:String$count:Int!$cursor:ID$orderBy:ReportsOrdering$orderMode:OrderingMode$filters:[ReportsFiltering]){...ReportsLines_data_2wN0PW}fragment ReportLine_node on Report{id entity_type name description published createdBy{__typename __isIdentity:__typename id name entity_type}objectMarking{edges{node{id definition x_opencti_color}}}objectLabel{edges{node{id value color}}}status{id order template{name color id}}workflowEnabled}fragment ReportsLines_data_2wN0PW on Query{reports(search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode filters:$filters){edges{node{id name published createdBy{__typename __isIdentity:__typename id name entity_type}objectMarking{edges{node{id definition}}}...ReportLine_node __typename}cursor}pageInfo{endCursor hasNextPage globalCount}}}",
  "size": 91,
  "time": 2,
  "timestamp": "2022-06-16T10:31:38.976Z",
  "type": "READ_ERROR",
  "user": {
    "ip": "::ffff:172.25.0.1",
    "referer": "https://opencti.ncs.local/dashboard/analysis/reports?sortBy=status_id&orderAsc=true&filters=%7B%7D&deSelectedElements=null",
    "user_id": "d276a177-3ce6-49c1-b573-f941c518add2"
  },
  "variables": {
    "count": 25,
    "cursor": null,
    "filters": [],
    "orderBy": "status_id",
    "orderMode": "asc",
    "search": ""
  },
  "version": "5.3.5"
}

```

**Comment by SamuelHassine** [comment]
Hello @rabbipigeon,

This problem has been solved in the latest released (5.3.6).

Kind regards,
Samuel
