### ISSUE TITLE
ElasticSearch Shutting Down - Service Logs

### ISSUE THREAD

**Issue by ims1337** [LuatixHQ/opencti#2202]
The Portainer is working fine but when i deploy the docker for CTI the Elasticesearch port or Docker port isnt loading.

Upon checking docker ps I came up that the elasticsearch is starting and shutting down in seconds.

While checking elasticsearch logs it shows below 

```
Invalid initial heap size: -Xms
Invalid initial heap size: -Xms
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:

error:
Invalid initial heap size: -Xms
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
	at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)
	at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
output:



```

Solution according to me:

- I think i need to adjust heap? If yes then how? cause the YML shows statement like this 
 xpack.ml.enabled=false
 "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}" 
 
      - Where to write the size or is it fine?
      
- Is there something wrong with my JAVA?

Please advice

**Comment by alice-debra** [comment]
Hello @ims1337,
Due to a lack of recent activity on this issue, we will proceed to close it for now. Apologies for the lack of response regarding this issue. If you're still experiencing the same problem, please don't hesitate to reopen the issue. We sincerely thank you for your feedback.
Kind regards,
Alice
