### ISSUE TITLE
Connector AlienVault not working

### ISSUE THREAD

**Issue by adis3421** [LuatixHQ/opencti#2235]
## Description

Connector AlienVault not working

## Environment

1. OS: Oracle Linux 8.6
2. OpenCTI version: 5.3.7
3. OpenCTI client: connector
4. Other environment details: Manual deployment

## Reproducible Steps

In version 5.3.7 connector alienvault is not working. I didn't check diffrent connector. 
The file connectors/external-import/alienvault/src/alienvault/utils/__init__.py  in versions 5.2.4 and 5.3.7 are different from each other which causes the error. I copy all catalog connectors/external-import/alienvault  from version 5.2.4 to 5.3.7 and its working.

## Expected Output

Working connector

## Actual Output

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: AlienVault
INFO:root:Starting ping alive thread
Traceback (most recent call last):
  File "/opt/OCTI/opencti/connectors/external-import/alienvault537/src/main.py", line 7, in <module>
    connector = AlienVault()
  File "/opt/OCTI/opencti/connectors/external-import/alienvault537/src/alienvault/core.py", line 154, in __init__
    author = self._create_author()
  File "/opt/OCTI/opencti/connectors/external-import/alienvault537/src/alienvault/core.py", line 182, in _create_author
    return create_organization("AlienVault")
  File "/opt/OCTI/opencti/connectors/external-import/alienvault537/src/alienvault/utils/__init__.py", line 145, in create_organization
    return create_identity(
  File "/opt/OCTI/opencti/connectors/external-import/alienvault537/src/alienvault/utils/__init__.py", line 161, in create_identity
    identity_id = Identity.generate_id(name, identity_class)
AttributeError: type object 'Identity' has no attribute 'generate_id'

**Comment by adis3421** [comment]
I resolved problem. I didn't use pip3 install -r requirements.txt :)
