### ISSUE TITLE
Update to 5.3.7

### ISSUE THREAD

**Issue by adis3421** [LuatixHQ/opencti#2242]
## Prerequisites

I update from 5.2.4 to 5.3.7

## Description

I have a problem with correct operation

## Environment

1. OS Oracle Linux 8.6
2. OpenCTI version: 5.3.7
3. OpenCTI client: null
4. Other environment details: Manual deployment

## Reproducible Steps

After uptade to 5.3.7 version in logs I see:

{"category":"APP","error":{"data":{"category":"technical","http_status":401},"stacktrace":["AuthRequired: You must be logged in to do this.","at error (/opt/OCTI/opencti/build/src/config/errors.js:8:10)","at AuthRequired (/opt/OCTI/opencti/build/src/config/errors.js:20:39)","at i.resolve (/opt/OCTI/opencti/build/src/graphql/authDirective.js:34:23)","at t.resolve (/opt/OCTI/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)","at executeField (/opt/OCTI/opencti/build/node_modules/graphql/execution/execute.js:481:20)","at executeFields (/opt/OCTI/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at executeOperation (/opt/OCTI/opencti/build/node_modules/graphql/execution/execute.js:344:14)","at execute (/opt/OCTI/opencti/build/node_modules/graphql/execution/execute.js:136:20)","at b (/opt/OCTI/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/requestPipeline.ts:500:20)","at processGraphQLRequest (/opt/OCTI/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/requestPipeline.ts:406:28)","at processTicksAndRejections (node:internal/process/task_queues:96:5)","at processHTTPRequest (/opt/OCTI/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/runHttpQuery.ts:433:24)"]},"inner_relation_creation":0,"level":"warn","message":"API Call","operation":"StixCoreObjectExternalReferencesLinesQuery","operation_query":"query StixCoreObjectExternalReferencesLinesQuery($count:Int!$id:String!){...StixCoreObjectExternalReferencesLines_data_44vElo}fragment FileLine_file on File{id name uploadStatus lastModified lastModifiedSinceMin metaData{mimetype list_filters messages{timestamp message}errors{timestamp message}}...FileWork_file}fragment FileWork_file on File{id works{id connector{name id}user{name id}received_time tracking{import_expected_number import_processed_number}messages{timestamp message}errors{timestamp message}status timestamp}}fragment StixCoreObjectExternalReferencesLines_data_44vElo on Query{stixCoreObject(id:$id){__typename id externalReferences(first:$count){edges{node{id source_name description url hash external_id jobs(first:100){id timestamp connector{id name}messages{timestamp message}errors{timestamp message}status}connectors(onlyAlive:false){id connector_type name active updated_at}importFiles(first:1000){edges{node{id lastModified ...FileLine_file metaData{mimetype}}}}__typename}cursor}pageInfo{endCursor hasNextPage}}}}","size":57,"time":3,"timestamp":"2022-07-20T10:18:15.377Z","type":"READ_ERROR","version":"5.3.7"}

But frontend works fine screenshots below

## Additional information

![image](https://user-images.githubusercontent.com/44203743/179960559-63176668-68c5-4490-8939-a8ab7a5fa472.png)

Error worker:
![image](https://user-images.githubusercontent.com/44203743/179961014-2c9b9efd-dea6-4ad0-a518-9568eeb8cbe9.png)

Connector screen
![image](https://user-images.githubusercontent.com/44203743/179961538-1f97c97a-2253-475e-8c0f-5c9cb9c79c7c.png)

Tools
![image](https://user-images.githubusercontent.com/44203743/180206005-9c058a11-7219-4722-b04a-1ac0adddd308.png)

**Comment by adis3421** [comment]
I resolved problem. I didn't use pip3 install -r requirements.txt :)
