### ISSUE TITLE
Error: Timeout._onTimeout - locking server instance

### ISSUE THREAD

**Issue by mattseymour** [LuatixHQ/opencti#2404]
## Description

After upgrading to 5.3.15 we get the following Elastic search timeout error which the server cannot recover from (locking up).
```
│ opencti-web (node:7) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit                                   │
│ opencti-web (Use `node --trace-warnings ...` to show where the warning was created)
│ opencti-web AbortError: Request aborted                                                                                                                                                                                     │
│ opencti-web     at Object.destroy (/opt/opencti/build/node_modules/undici/lib/api/readable.js:48:13)                                                                                                                        │
│ opencti-web     at _me.request (/opt/opencti/build/node_modules/@elastic/transport/src/connection/UndiciConnection.ts:195:23)                                                                                               │
│ opencti-web     at runMicrotasks (<anonymous>)                                                                                                                                                                              │
│ opencti-web     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                                                       │
│ opencti-web     at Rme.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:462:45)                                                                                                                 │
│ opencti-web     at $F.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:84:10)                                                                                            │
│ opencti-web     at elList (/opt/opencti/build/src/database/middleware-loader.ts:57:22)                                                                                                                                      │
│ opencti-web     at closeOldWorks (/opt/opencti/build/src/manager/connectorManager.js:62:5)                                                                                                                                  │
│ opencti-web     at connectorHandler (/opt/opencti/build/src/manager/connectorManager.js:102:7)                                                                                                                              │
│ opencti-web     at /opt/opencti/build/src/manager/connectorManager.js:124:9                                                                                                                                                 │
│ opencti-web     at Syt.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)                                                                           │
│ opencti-web     at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)
```

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Opencti 5.3.15 docker image
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 
5.3.15
5. OpenCTI client: { e.g. frontend or python }
Backend
6. Other environment details:
Docker image
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by richard-julien** [comment]
Hi, can you check your elasticsearch logs on the error period?

**Comment by alice-debra** [comment]
Hello @mattseymour,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
Kind regards,
Alice
