### ISSUE TITLE
Empty error message Cortex Analyzer OpenCTI

### ISSUE THREAD

**Issue by igcoser** [LuatixHQ/opencti#2423]
Hi, thank you for your message. I upgraded pycti to 5.3.5, 5.3.7 and 5.3.15 to test and it resolves the previous problem and the https://github.com/TheHive-Project/Cortex-Analyzers/issues/1104

```pycti                             5.3.7```

but it returns the following error in Cortex:

```
{
  "errorMessage": "",
  "input": null,
  "success": false
}
```

and if run it locally:

```
echo'{"data":"http://89.40.15.153/apache2","dataType":"url","tlp":0}' | python3 opencti.py
ERROR:root:Unknown type "CryptographicKey".
Traceback (most recent call last):
  File "opencti.py", line 114, in <module>
    OpenCTIAnalyzer().run()
  File "opencti.py", line 68, in run
    observables = opencti["api_client"].stix_cyber_observable.list(search=data)
  File "/.pyenv/versions/3.7.12/lib/python3.7/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 364, in list
    "orderMode": order_mode,
  File "/.pyenv/versions/3.7.12/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 315, in query
    {"name": error_name, "message": main_error["message"]}
ValueError: {'name': 'Unknown type "CryptographicKey".', 'message': 'Unknown type "CryptographicKey".'}
zsh: done       echo '{"data":"http://89.40.15.153/apache2","dataType":"url","tlp":0}' | 
zsh: killed     python3 opencti.py
```
Could please guide me on how to resolve this? Thank you

**Comment by SamuelHassine** [comment]
You need to update pycti to 5.3.16 and have your platform running in 5.3.16 as well.

**Comment by alice-debra** [comment]
Hello @igcoser,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
Kind regards,
Alice
