### ISSUE TITLE
Timeout Error - [SEARCH ENGINE] Paginate fail

### ISSUE THREAD

**Issue by timbayley-vf** [LuatixHQ/opencti#2441]
## Description

The OpenCTI platform is continually crashing with the error: "[SEARCH ENGINE] Paginate fail".

The platform has been relatively stable for the last 6 months or so, and has only recently been giving me this error.

## Environment

1. OS - Kubernetes (GKE 1.21.14-gke.2700 on )
2. OpenCTI version: { e.g. OpenCTI 5.3.17 }
3. OpenCTI client: { e.g. frontend }
4. Other environment details: based on Helm chart, but heavily modified.

Container versions:
redis:7.0.4
rabbitmq:3.10.2-management
docker.elastic.co/elasticsearch/elasticsearch:8.4.3
minio/minio:RELEASE.2022-06-30T20-58-09Z

## Reproducible Steps

I am not yet clear what has triggered this, but it is occurring every time an OpenCTI pod starts.

I have tried to run the Elasticsearch query manually from Dev Tools in Kibana, and Elasticsearch responds very quickly with the relevant data.

OpenCTI is able to authenticate with Elasticsearch. I am using a custom "opencti" user in Elasticsearch with admin permissions to authenticate.

## Expected Output

OpenCTI boots as normal

## Actual Output

Error and eventual CrashLoopBackoff in Kubernetes

Error:
```
{"category":"APP","error":{"context":{},"message":"Request timed out","name":"TimeoutError","stack":"TimeoutError: Request timed out\n    at Mme.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:581:17)\n    at JF.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:84:10)\n    at Object.start (/opt/opencti/build/src/manager/historyManager.ts:176:29)\n    at startModules (/opt/opencti/build/src/modules.js:88:5)\n    at boot (/opt/opencti/build/src/boot.js:16:5)"},"level":"error","message":"[SEARCH ENGINE] Paginate fail","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"History"}},{"match_phrase":{"parent_types.keyword":"History"}}]}},{"exists":{"field":"timestamp"}}],"must_not":[]}},"size":1,"sort":[{"timestamp":"desc"},{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_history"],"track_total_hits":true},"timestamp":"2022-10-10T12:52:28.510Z","version":"5.3.17"}
{"category":"APP","error":{"context":{},"message":"Request timed out","name":"TimeoutError","stack":"TimeoutError: Request timed out\n    at Mme.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:581:17)\n    at JF.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:84:10)\n    at Object.start (/opt/opencti/build/src/manager/historyManager.ts:176:29)\n    at startModules (/opt/opencti/build/src/modules.js:88:5)\n    at boot (/opt/opencti/build/src/boot.js:16:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-10-10T12:52:28.511Z","version":"5.3.17"}
```

## Additional information

Full log (for context) 

```
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-10-10T12:50:01.412Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2022-10-10T12:50:01.415Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[SEARCH ENGINE] Elasticsearch (8.4.3) client selected / runtime sorting enabled","timestamp":"2022-10-10T12:50:01.463Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2022-10-10T12:50:01.464Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2022-10-10T12:50:01.480Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2022-10-10T12:50:01.514Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2022-10-10T12:50:01.520Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2022-10-10T12:50:01.788Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Initializing cache manager","timestamp":"2022-10-10T12:50:01.789Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Pubsub subscriber' client ready","timestamp":"2022-10-10T12:50:20.884Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Cache manager initialized","timestamp":"2022-10-10T12:50:20.885Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2022-10-10T12:50:20.889Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2022-10-10T12:50:26.109Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2022-10-10T12:50:26.138Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[INIT] admin user initialized","timestamp":"2022-10-10T12:50:26.386Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[MIGRATION] Read 9 migrations from the database","timestamp":"2022-10-10T12:50:27.246Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[MIGRATION] Platform already up to date, nothing to migrate","timestamp":"2022-10-10T12:50:27.247Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[MIGRATION] Migration process completed","timestamp":"2022-10-10T12:50:27.247Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[MIGRATION] Platform version updated to 5.3.17","timestamp":"2022-10-10T12:50:27.610Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2022-10-10T12:50:27.611Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI] API ready on port 8080","timestamp":"2022-10-10T12:50:28.461Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Running Expiration manager","timestamp":"2022-10-10T12:50:28.461Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Running connector manager","timestamp":"2022-10-10T12:50:28.462Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Running retention manager","timestamp":"2022-10-10T12:50:28.462Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Running task manager","timestamp":"2022-10-10T12:50:28.462Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Subscription manager not started (disabled by configuration)","timestamp":"2022-10-10T12:50:28.473Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Sync manager already in progress by another API","timestamp":"2022-10-10T12:50:54.896Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Rule engine already started by another API","timestamp":"2022-10-10T12:51:03.871Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Connector manager already started by another API","timestamp":"2022-10-10T12:51:08.709Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Sync manager already in progress by another API","timestamp":"2022-10-10T12:51:22.371Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Rule engine already started by another API","timestamp":"2022-10-10T12:51:39.102Z","version":"5.3.17"}
(node:7) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Connector manager already started by another API","timestamp":"2022-10-10T12:51:48.530Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Sync manager already in progress by another API","timestamp":"2022-10-10T12:51:49.559Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Retention manager already in progress by another API","timestamp":"2022-10-10T12:51:53.442Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Rule engine already started by another API","timestamp":"2022-10-10T12:52:14.077Z","version":"5.3.17"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Connector manager already started by another API","timestamp":"2022-10-10T12:52:28.332Z","version":"5.3.17"}
{"category":"APP","error":{"context":{},"message":"Request timed out","name":"TimeoutError","stack":"TimeoutError: Request timed out\n    at Mme.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:581:17)\n    at JF.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:84:10)\n    at Object.start (/opt/opencti/build/src/manager/historyManager.ts:176:29)\n    at startModules (/opt/opencti/build/src/modules.js:88:5)\n    at boot (/opt/opencti/build/src/boot.js:16:5)"},"level":"error","message":"[SEARCH ENGINE] Paginate fail","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"History"}},{"match_phrase":{"parent_types.keyword":"History"}}]}},{"exists":{"field":"timestamp"}}],"must_not":[]}},"size":1,"sort":[{"timestamp":"desc"},{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_history"],"track_total_hits":true},"timestamp":"2022-10-10T12:52:28.510Z","version":"5.3.17"}
{"category":"APP","error":{"context":{},"message":"Request timed out","name":"TimeoutError","stack":"TimeoutError: Request timed out\n    at Mme.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:581:17)\n    at JF.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:84:10)\n    at Object.start (/opt/opencti/build/src/manager/historyManager.ts:176:29)\n    at startModules (/opt/opencti/build/src/modules.js:88:5)\n    at boot (/opt/opencti/build/src/boot.js:16:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-10-10T12:52:28.511Z","version":"5.3.17"}
```

## Screenshots (optional)

**Comment by richard-julien** [comment]
Any logs on elasticsearch side?

**Comment by timbayley-vf** [comment]
So sorry for the huge delay in responding. While I was away, I understand my colleague increased the JVM size in Elasticsearch, and everything looks OK 👍. Thanks for your prompt response!
