### ISSUE TITLE
OpenCTI stops running

### ISSUE THREAD

**Issue by bakhtawarw** [LuatixHQ/opencti#2450]
## Environment

1. OS (where OpenCTI server runs): { Ubuntu 20.04 Virtual Machine)
2. OpenCTI version: { 5.3.15 }
3. OpenCTI environment: { docker }

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I installed OpenCTI 5.3.15 from scratch, it runs fine initially. But when I shutdown the virtual machine and reached out to it after few days, OpenCTI failed to start and throwing this error.

## Expected Output

OpenCTI running correctly.

## Actual Output

OpenCTI failed to start and throwing this error.

![image](https://user-images.githubusercontent.com/104062347/195519168-988897a7-ca8e-4c74-8c3d-faf92f3df78c.png)

![image](https://user-images.githubusercontent.com/104062347/195520004-417ae571-7dbd-43e9-956d-fbffe5115952.png)

I have tried removing the elastic container and reinstalling elastic, then it works fine. But that's not a permanent solution, it should work smoothly without having to reinstall elastic container every time I start OpenCTI.

**Comment by richard-julien** [comment]
Looks like the problem is coming from your elasticsearch deployment. Please check your elastic logs and try to find why the container fail and why the data inside the container are not accessible.

**Comment by bakhtawarw** [comment]
@richard-julien   Elasticsearch logs are as follows:


"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.4.jar:7.17.4]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
"at java.lang.Thread.run(Thread.java:833) [?:?]",
"Caused by: org.elasticsearch.action.NoShardAvailableActionException: [2661c9c8bff0][172.18.0.15:9300][indices:data/read/search[phase/query]]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:532) ~[elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:479) [elasticsearch-7.17.4.jar:7.17.4]",
"... 20 more"] }
{"type": "server", "timestamp": "2022-10-13T18:37:59,881Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "docker-cluster", "node.name": "2661c9c8bff0", "message": "path: /opencti_history/_search, params: {ignore_throttled=false, index=opencti_history}", "cluster.uuid": "oaRvfE5DTrqG9gwl0O85Mw", "node.id": "MNyZQZhRSeqsSKqQ8T06YA" , 
"stacktrace": ["org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:713) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:400) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:745) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:497) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$000(AbstractSearchAsyncAction.java:64) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:331) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:66) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:48) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:651) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.transport.TransportService$4.handleException(TransportService.java:853) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1481) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1590) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1564) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:50) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:45) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:41) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:77) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.4.jar:7.17.4]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
"at java.lang.Thread.run(Thread.java:833) [?:?]",
"Caused by: org.elasticsearch.action.NoShardAvailableActionException: [2661c9c8bff0][172.18.0.15:9300][indices:data/read/search[phase/query]]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:532) ~[elasticsearch-7.17.4.jar:7.17.4]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:479) [elasticsearch-7.17.4.jar:7.17.4]",
"... 20 more"] }

**Comment by alice-debra** [comment]
Hello @bakhtawarw,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback. Please don’t hesitate to reopen the issue if you still have any questions.
Kind regards,
Alice
