### ISSUE TITLE
Invalid character in header content [\"authorization\"]

### ISSUE THREAD

**Issue by graememeyer** [LuatixHQ/opencti#2482]
## Description

The OpenCTI GUI container (opencti/platform:5.3.17) spams this error message when started:

```{"category":"APP","error":{"context":{},"message":"Invalid character in header content [\"authorization\"]","name":"TypeError","stack":"TypeError: Invalid character in header content [\"authorization\"]\n    at ClientRequest.setHeader (node:_http_outgoing:606:3)\n    at new ClientRequest (node:_http_client:275:14)\n    at request (node:http:96:10)\n    at /opt/opencti/build/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:69:66\n    at new Promise (<anonymous>)\n    at g6e.handle (/opt/opencti/build/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:49:16)\n    at next (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/commands/CreateBucketCommand.js:29:58)\n    at next (/opt/opencti/build/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:5:32)\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:26\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at cSe.retry (/opt/opencti/build/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22\n    at initializeBucket (/opt/opencti/build/src/database/file-storage.js:74:5)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:120:3)\n    at boot (/opt/opencti/build/src/boot.js:10:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-10-25T10:28:44.840Z","version":"5.3.17"}```

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. } - Ubuntu 20.04 LTS
3. OpenCTI version: { e.g. OpenCTI 1.0.2 }  opencti/platform:5.3.17 and opencti/platform:5.3.12
4. OpenCTI client: { e.g. frontend or python } frontend
5. Other environment details:
This is using the docker compose config (), on Ubuntu 20.04 LTS (also tested with Docker Desktop on Windows 11 WSL using Ubuntu 20.04). I've tried using docker-compose version 1.25.0, as well as the newer docker compose v2. I've tried using my own completely custom environment variables, as well as the sample .env file provided. I've checked and all the tokens provided are UUID4 compliant.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

OpenCTI should start for the first time as normal.

## Actual Output

The OpenCTI GUI container (opencti/platform:5.3.17) spams this error message when started:

```{"category":"APP","error":{"context":{},"message":"Invalid character in header content [\"authorization\"]","name":"TypeError","stack":"TypeError: Invalid character in header content [\"authorization\"]\n    at ClientRequest.setHeader (node:_http_outgoing:606:3)\n    at new ClientRequest (node:_http_client:275:14)\n    at request (node:http:96:10)\n    at /opt/opencti/build/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:69:66\n    at new Promise (<anonymous>)\n    at g6e.handle (/opt/opencti/build/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:49:16)\n    at next (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/commands/CreateBucketCommand.js:29:58)\n    at next (/opt/opencti/build/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:5:32)\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:26\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at cSe.retry (/opt/opencti/build/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22\n    at initializeBucket (/opt/opencti/build/src/database/file-storage.js:74:5)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:120:3)\n    at boot (/opt/opencti/build/src/boot.js:10:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-10-25T10:28:44.840Z","version":"5.3.17"}```

## Additional Info

I'm pretty sure these exact config files worked a few days ago, so possibly something has changed up-stream?

**Comment by graememeyer** [comment]
@richard-julien was able to reproduce this issue with an invalid char in the MINIO__ACCESS_KEY setting (which is filled by the MINIO_ROOT_USER environment variable if you're loading the example configs).

There was no visible obvious issue with any of the files I had, so it was likely an invisible character issue. I thought I had already ruled out a CRLF/LF error, so if anyone gets this error in future it may be worth downloading the example env file from https://github.com/OpenCTI-Platform/docker and starting again from scratch.

**Comment by graememeyer** [comment]
@richard-julien was able to reproduce this issue with an invalid char in the MINIO__ACCESS_KEY setting (which is filled by the MINIO_ROOT_USER environment variable if you're loading the example configs).

There was no visible obvious issue with any of the files I had, so it was likely an invisible character issue. I thought I had already ruled out a CRLF/LF error, so if anyone gets this error in future it may be worth downloading the example env file from https://github.com/OpenCTI-Platform/docker and starting again from scratch.

**Comment by graememeyer** [comment]
Final follow-up: it seems I did not successfully rule out CRLF/LF errors before, I still had the incorrect line-endings in my files.

You can check the line-endings in your files using the `cat -A` command on linux systems.

If you see `^M$` at the end of your lines, that's the _incorrect_ character. It should be simply `$` at the end of each line

Example of how to use the command and what the correct line-endings look like:

``` Bash
ctiuser@CTI-OpenCTIDev-vm:~/docker$ cat -A .env
OPENCTI_ADMIN_EMAIL=admin@opencti.io$
OPENCTI_ADMIN_PASSWORD=changemeapassword$
OPENCTI_ADMIN_TOKEN=7d1118b3-0ec2-4d52-9266-38f8b0430b3e$
OPENCTI_BASE_URL=http://localhost:8080$
```

You can convert a file with "windows" line endings to unix line endings using `dos2unix` like so:

```bash
ctiuser@CTI-OpenCTIDev-vm:~/docker$ dos2unix .env
dos2unix: converting file .env to Unix format...
```
