### ISSUE TITLE
Manual deployment problem

### ISSUE THREAD

**Issue by pulpon6** [LuatixHQ/opencti#2497]
## Prerequisites

- [ ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [ ] I went through old GitHub issues and couldn't find anything relevant
- [ ] I googled the issue and didn't find anything relevant

## Description

I want to make a manual installation of OpenCTI and I got an error on "**$ python3 worker.py &** "

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server 22
2. OpenCTI version: 5.3.17
3. OpenCTI client: python
4. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
$ cd worker
$ pip3 install -r requirements.txt
$ cp config.yml.sample config.yml
$ python3 worker.py &
$ python3 worker.py & 

## Additional information
![image](https://user-images.githubusercontent.com/76466949/198108770-c04dd821-4aa2-48e8-9490-38993a6e6ae9.png)

opencti@opencti:~/opencti/worker$ python3 worker.py &
[1] 23535
opencti@opencti:~/opencti/worker$ Traceback (most recent call last):
  File "/home/opencti/opencti/worker/worker.py", line 429, in <module>
    worker = Worker()
  File "<string>", line 6, in __init__
  File "/home/opencti/opencti/worker/worker.py", line 337, in __post_init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.10/dist-packages/pycti/api/opencti_api_client.py", line 118, in __init__
    raise ValueError("A TOKEN must be set")
ValueError: A TOKEN must be set

**Comment by JeromeSRT** [comment]
Hello,
In the config.yml, you need to put the id token of the user you use to connect the worker to your OpenCTI frontend.

**Comment by alice-debra** [comment]
Hello @pulpon6,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback. Please don’t hesitate to reopen the issue if you still have any questions.
Kind regards,
Alice
