### ISSUE TITLE
Out of Memory: Killed Process

### ISSUE THREAD

**Issue by bigverm23** [LuatixHQ/opencti#2622]
## Description

While processing multiple queued bundles, the VM is looping in and out of a process kill/restart causing the GUI to be unstable.
## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.10 in Virtualbox
2. OpenCTI version: 5.4.1
3. OpenCTI client: frontend

## Reproducible Steps

doing nothing except running queued bundles across multiple connectors

## Additional information

VM is 16gb and 8cores.

opencti container logs:
`ory":"APP","error":{"data":{"body":{"script":{"lang":"painless","params":{"message":"Connector ready to process the operation","received_time":"2022-12-01T17:42:22.393Z"},"source":"ctx._source.status = \"progress\";ctx._source[\"received_time\"] = params.received_time;ctx._source.messages.add([\"timestamp\": params.received_time, \"message\": params.message]); "}},"category":"technical","documentId":"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z","error":{"meta":{"headers":{},"meta":{"aborted":false,"attempts":3,"connection":{"headers":{},"id":"http://elasticsearch:9200/","status":"alive","url":"http://elasticsearch:9200/"},"context":null,"name":"elasticsearch-js","request":{"id":2215738,"options":{},"params":{"body":"{\"script\":{\"source\":\"ctx._source.status = \\\"progress\\\";ctx._source[\\\"received_time\\\"] = params.received_time;ctx._source.messages.add([\\\"timestamp\\\": params.received_time, \\\"message\\\": params.message]); \",\"lang\":\"painless\",\"params\":{\"received_time\":\"2022-12-01T17:42:22.393Z\",\"message\":\"Connector ready to process the operation\"}}}","headers":{"accept":"application/vnd.elasticsearch+json; compatible-with=8","content-length":"331","content-type":"application/vnd.elasticsearch+json; compatible-with=8","user-agent":"elastic-transport-js/8.2.0 (linux 5.13.0-28-generic-x64; Node.js v18.12.1)","x-elastic-client-meta":"es=8.5.0,js=18.12.1,t=8.2.0,hc=18.12.1"},"method":"POST","path":"/opencti_history/_update/work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14%3A54%3A46.447Z","querystring":"retry_on_conflict=5&timeout=5m&refresh=true"}}},"statusCode":0,"warnings":null},"name":"ConnectionError"},"http_status":500,"reason":"Error updating elastic"},"stacktrace":["DatabaseError: A database error has occurred","at error (/opt/opencti/build/src/config/errors.js:8:10)","at DatabaseError (/opt/opencti/build/src/config/errors.js:47:48)","at /opt/opencti/build/src/database/engine.js:1907:11","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at updateReceivedTime (/opt/opencti/build/src/domain/work.js:206:3)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"workToReceived","operation_query":"mutation workToReceived($id:ID!$message:String){workEdit(id:$id){toReceived(message:$message)}}","size":128,"time":60,"timestamp":"2022-12-01T17:42:22.453Z","type":"WRITE_ERROR","user":{"ip":"::ffff:172.18.0.7","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{"id":"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z","message":"Connector ready to process the operation"},"version":"5.4.1"}
{"category":"APP","error":{"data":{"category":"technical","error":{"meta":{"headers":{},"meta":{"aborted":false,"attempts":3,"connection":{"headers":{},"id":"http://elasticsearch:9200/","status":"alive","url":"http://elasticsearch:9200/"},"context":null,"name":"elasticsearch-js","request":{"id":2215744,"options":{},"params":{"body":"{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"term\":{\"internal_id.keyword\":\"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z\"}},{\"term\":{\"standard_id.keyword\":\"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z\"}},{\"term\":{\"x_opencti_stix_ids.keyword\":\"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z\"}}],\"minimum_should_match\":1}},{\"bool\":{\"should\":[{\"match_phrase\":{\"entity_type.keyword\":\"work\"}},{\"match_phrase\":{\"parent_types.keyword\":\"work\"}}],\"minimum_should_match\":1}}],\"must_not\":[]}},\"size\":5000}","headers":{"accept":"application/vnd.elasticsearch+json; compatible-with=8","content-length":"559","content-type":"application/vnd.elasticsearch+json; compatible-with=8","user-agent":"elastic-transport-js/8.2.0 (linux 5.13.0-28-generic-x64; Node.js v18.12.1)","x-elastic-client-meta":"es=8.5.0,js=18.12.1,t=8.2.0,hc=18.12.1"},"method":"POST","path":"/opencti_history*/_search","querystring":"ignore_throttled=false"}}},"statusCode":0,"warnings":null},"name":"ConnectionError"},"http_status":500,"query":{"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"term":{"internal_id.keyword":"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z"}},{"term":{"standard_id.keyword":"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z"}},{"term":{"x_opencti_stix_ids.keyword":"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z"}}]}},{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"work"}},{"match_phrase":{"parent_types.keyword":"work"}}]}}],"must_not":[]}}},"ignore_throttled":false,"index":"opencti_history*","size":5000},"reason":"Error loading ids"},"stacktrace":["DatabaseError: A database error has occurred","at error (/opt/opencti/build/src/config/errors.js:8:10)","at DatabaseError (/opt/opencti/build/src/config/errors.js:47:48)","at /opt/opencti/build/src/database/engine.js:1071:15","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at elFindByIds (/opt/opencti/build/src/database/engine.js:1070:20)","at elLoadById (/opt/opencti/build/src/database/engine.js:1086:16)","at loadWorkById (/opt/opencti/build/src/domain/work.js:34:18)","at updateProcessedTime (/opt/opencti/build/src/domain/work.js:213:23)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"workToProcessed","operation_query":"mutation workToProcessed($id:ID!$message:String$inError:Boolean){workEdit(id:$id){toProcessed(message:$message inError:$inError)}}","size":165,"time":51,"timestamp":"2022-12-01T17:42:22.512Z","type":"WRITE_ERROR","user":{"ip":"::ffff:172.18.0.7","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{"id":"work_b29fa531-5506-45a0-8012-54279c24d2ad_2022-12-01T14:54:46.447Z","inError":true,"message":"{'name': 'DatabaseError', 'message': 'Error updating elastic'}"},"version":"5.4.1"}`

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/17554438/205122082-28978796-cf47-43b7-9825-542c32f67905.png)
![image](https://user-images.githubusercontent.com/17554438/205122648-72c61bcc-d743-4e63-a5e5-821eac1f2cb7.png)
![image](https://user-images.githubusercontent.com/17554438/205122726-69f67d05-cdcb-460c-9667-77448adaa22f.png)

**Comment by bigverm23** [comment]
![image](https://user-images.githubusercontent.com/17554438/205180244-043264cb-8cdc-4088-82cf-6e752e870d75.png)

`  opencti:
    image: opencti/platform:5.4.1
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always`

**Comment by richard-julien** [comment]
Hi. Same answer as https://github.com/OpenCTI-Platform/opencti/issues/2623.
Depending on your usage a single api node with only 8 Go of memory could be not enough.

**Comment by symsal** [comment]
I have the same problem with redis oom error

**Comment by alice-debra** [comment]
Hello,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
Kind regards,
Alice
