### ISSUE TITLE
Add organizations to  SSO Users when login in

### ISSUE THREAD

**Issue by max-frank** [LuatixHQ/opencti#2625]
## Description

When setting up any of the SSO providers user accounts will be automatically created upon first login.
With the addition of organisations as a user attribute a new requirement was added that a user must have an organisation to login. The automatic user creation for SSO based users does not set any organisation and there is currently also no way to configure this, thus breaking SSO first time logins.

Workaround for now is either pre-provision a user by username/email set their organisation and then convert it into an SSO account or set the organisation after their first failed login.

## Environment

1. OS (where OpenCTI server runs): `opencti/platform:5.4.1` (container image)
2. OpenCTI version: 5.4.1
3. OpenCTI client: frontend
4. Other environment details: SAML provider

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  Setup any SSO provider
2. Have a user login via SSO for the first time
3. User receives error and can't login

## Expected Output

First time users can login and its possible to configure a organisation to add them to, either by static setting for the SSO provider or by use of a mapping attribute.

## Actual Output

User gets created with out organisation locking them out of the platform.

## Additional Information

Relevant [code block](https://github.com/OpenCTI-Platform/opencti/blob/7ebe03c9ac3c15ffcece403d080841f8dffe2f0a/opencti-platform/opencti-graphql/src/domain/user.js#L481-L488)

## Screenshots (optional)

<img width="608" alt="image" src="https://user-images.githubusercontent.com/1375575/205188445-16cb725a-7a05-4b51-975d-b6ff8b45669f.png">

```
{"category":"APP","error":{"data":{"category":"technical","http_status":401},"stacktrace":["AuthRequired: You must be logged in to do this.","at error (/opt/opencti/build/src/config/errors.js:8:10)","at AuthRequired (/opt/opencti/build/src/config/errors.js:20:39)","at fieldResolver (/opt/opencti/build/src/graphql/authDirective.js:36:23)","at resolveFn (/opt/opencti/build/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:481:20)","at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at executeOperation (/opt/opencti/build/node_modules/graphql/execution/execute.js:344:14)","at execute (/opt/opencti/build/node_modules/graphql/execution/execute.js:136:20)","at execute (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:501:20)","at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:407:28)","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)"]},"inner_relation_creation":0,"level":"warn","message":"API Call","operation":"RootPrivateQuery","operation_query":"query RootPrivateQuery{me{id name lastname language theme user_email individual_id capabilities{name id}}settings{platform_map_tile_server_dark platform_map_tile_server_light platform_hidden_types platform_theme platform_feature_flags{id enable}platform_modules{id enable}...AppThemeProvider_settings ...AppIntlProvider_settings id}about{version}}fragment AppIntlProvider_settings on Settings{platform_language}fragment AppThemeProvider_settings on Settings{platform_title platform_favicon platform_theme platform_theme_dark_background platform_theme_dark_paper platform_theme_dark_nav platform_theme_dark_primary platform_theme_dark_secondary platform_theme_dark_accent platform_theme_dark_logo platform_theme_light_background platform_theme_light_paper platform_theme_light_nav platform_theme_light_primary platform_theme_light_secondary platform_theme_light_accent platform_theme_light_logo}","size":2,"time":24,"timestamp":"2022-12-02T00:37:00.319Z","type":"READ_ERROR","version":"5.4.1"}
{"auth":{"ip":"::ffff:10.10.10.10","referer":"https://some.saml.url.very.cool/"},"category":"AUDIT","level":"error","message":"LOGIN","resource":{"error":"You can't login without an organization","provider":"saml"},"timestamp":"2022-12-02T00:39:19.774Z","version":"5.4.1"}
{"category":"APP","error":{"data":{"category":"technical","http_status":401},"stacktrace":["AuthRequired: You must be logged in to do this.","at error (/opt/opencti/build/src/config/errors.js:8:10)","at AuthRequired (/opt/opencti/build/src/config/errors.js:20:39)","at fieldResolver (/opt/opencti/build/src/graphql/authDirective.js:36:23)","at resolveFn (/opt/opencti/build/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:481:20)","at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at executeOperation (/opt/opencti/build/node_modules/graphql/execution/execute.js:344:14)","at execute (/opt/opencti/build/node_modules/graphql/execution/execute.js:136:20)","at execute (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:501:20)","at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:407:28)","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)"]},"inner_relation_creation":0,"level":"warn","message":"API Call","operation":"RootPrivateQuery","operation_query":"query RootPrivateQuery{me{id name lastname language theme user_email individual_id capabilities{name id}}settings{platform_map_tile_server_dark platform_map_tile_server_light platform_hidden_types platform_theme platform_feature_flags{id enable}platform_modules{id enable}...AppThemeProvider_settings ...AppIntlProvider_settings id}about{version}}fragment AppIntlProvider_settings on Settings{platform_language}fragment AppThemeProvider_settings on Settings{platform_title platform_favicon platform_theme platform_theme_dark_background platform_theme_dark_paper platform_theme_dark_nav platform_theme_dark_primary platform_theme_dark_secondary platform_theme_dark_accent platform_theme_dark_logo platform_theme_light_background platform_theme_light_paper platform_theme_light_nav platform_theme_light_primary platform_theme_light_secondary platform_theme_light_accent platform_theme_light_logo}","size":2,"time":2,"timestamp":"2022-12-02T00:39:21.288Z","type":"READ_ERROR","version":"5.4.1"}
```

**Comment by richard-julien** [comment]
Organizations mapping will be added in LDAP / SAML and OPENID provider.

Mapping will be configurable with

- Static definitions
```
       "organizations_default": ["Organization01"],
```
- Dynamic definitions (like roles or groups)

```
        "organizations_management": {
          "organizations_path": ["groups"],
          "organizations_mapping": ["GROUP1:Organization01"]
        },
```

- Linking to current platform organization.

Possible through the usage of the predefined organization name 'settings_platform_organization'

```
       "organizations_default": ["settings_platform_organization"],
```

**Comment by max-frank** [comment]
Thanks for the quick fix

**Comment by GraemeMeyerGT** [comment]
@richard-julien what's the full path of this configuraiton variable? (For Docker deployments). Is it something like PROVIDERS__OPENID__ORGANIZATIONS_DEFAULT ? It doesn't seem to be documented

Edit: through some trial an error, I've managed to figure out that the following seems to work:

```yml
- "PROVIDERS__OPENID__CONFIG__ORGANIZATIONS_DEFAULT=[\"My Amazing Organisation\"]"
```
