### ISSUE TITLE
[BUG] Importing PYCTI causes Python to be SIGKilled on uncaught error

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2634]
## Description

When you import the `pycti` package, if an uncaught error occurs the system sends the process a SIGKILL 

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 8 (I have also observed this on Ubuntu 18.04, 20.04)
2. OpenCTI version: 5.4.1 (This has been around a long time, decided I was sick of loosing my shell and ran it down today)
3. OpenCTI client: python `pycti` package
4. Other environment details: Tested on Python 3.7, 3.8, 3.9 and 3.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Launch Python Interpreter
2. Trip an un-caught error `x = 0 / 0` (Should drop back to interpreter)
3. Import pycti `import pycti` or `from pycti import OpenCTIApiClient`
4.  Trip an un-caught error `x = 0 / 0`
5. Process should be killed

## Expected Output

No sigkill issued to interpreter

## Actual Output

```bash
(venv) [mwatermolen@ ~]$  strace -e 'trace=!all' python
Python 3.10
Type "help", "copyright", "credits" or "license" for more information.
>>> x = 0 / 0                                                                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> import pycti
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=120116, si_uid=1028599, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=120117, si_uid=1028599, si_status=0, si_utime=0, si_stime=0} ---
>>> x = 0 / 0   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
+++ killed by SIGKILL +++
Killed
(venv) [mwatermolen@ ~]$ 
```

## Additional information

This has been an issue for atleast since the start of the year, never traced it back to `pycti` till now

**Comment by MaxwellDPS** [comment]
Issue was fixed by 5.7.X
