### ISSUE TITLE
"Dashboard > Analysis > External references" page shows an error message

### ISSUE THREAD

**Issue by Aspidoquelona** [LuatixHQ/opencti#2702]
## Description

Dashboard > Analysis > External references page shows this error message

*Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.*

## Environment

1. OS: Ubuntu 20.04 LTS
2. OpenCTI version: OpenCTI 5.5.1
3. OpenCTI client: frontend
4. Other environment details: manual installation.

## Reproducible Steps
The error occurs after migration from version 5.4.1 to 5.5.1 without any other action.

## Expected Output

Dashboard > Analysis > External references page must show the list of external references objects.

## Actual Output

No external reference is listed. The following message is shown instead:

*Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.*

## Additional information

The external references have neither dissapeared nor been deleted because if we open an entity (eg. a Report), we can see the external references realated to the Report.

LOG: 

{"category":"APP","error":{"stacktrace":["GraphQLError: Variable \"$orderBy\" got invalid value \"creator\"; Value \"creator\" does not exist in \"ExternalReferencesOrdering\" enum. Did you mean the enum value \"created\"?","at onError (/usr/local/opencti/build/node_modules/graphql/execution/values.js:147:11)","at coerceInputValueImpl (/usr/local/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:154:9)","at coerceInputValue (/usr/local/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:32:10)","at coerceVariableValues (/usr/local/opencti/build/node_modules/graphql/execution/values.js:132:52)","at getVariableValues (/usr/local/opencti/build/node_modules/graphql/execution/values.js:45:21)","at buildExecutionContext (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:280:45)","at execute (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:116:22)","at execute (/usr/local/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:501:20)","at processGraphQLRequest (/usr/local/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:407:28)","at runMicrotasks (<anonymous>)","at processTicksAndRejections (node:internal/process/task_queues:96:5)","at processHTTPRequest (/usr/local/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"ExternalReferencesLinesPaginationQuery","operation_query":"query ExternalReferencesLinesPaginationQuery($search:String$count:Int!$cursor:ID$orderBy:ExternalReferencesOrdering$orderMode:OrderingMode){...ExternalReferencesLines_data_2ltyuX}fragment ExternalReferenceLine_node on ExternalReference{id entity_type source_name external_id url created creator{id name}}fragment ExternalReferencesLines_data_2ltyuX on Query{externalReferences(search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode){edges{node{...ExternalReferenceLine_node id __typename}cursor}pageInfo{endCursor hasNextPage globalCount}}}","size":76,"time":3,"timestamp":"2023-01-04T13:13:36.050Z","type":"READ_ERROR","user":{"ip":"::ffff:127.0.0.1","referer":"https://opencti.rra.lan/dashboard/analysis/external_references","user_id":"d5bec166-7784-4eb1-817c-2eb302360a67"},"variables":{"count":25,"cursor":null,"orderBy":"creator","orderMode":"asc","search":""},"version":"5.5.1"}

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/119074626/210562546-671f6b39-ea34-4c99-9cb7-cf25add6e8e6.png)

![image](https://user-images.githubusercontent.com/119074626/210562683-d732aa16-15f2-46f4-8cbd-04c06b63bc5e.png)

**Comment by Aspidoquelona** [comment]
DELETED

**Comment by Aspidoquelona** [comment]
Interestingly, the problem has been solved by clearing the Browser (Firefox) cache.

**Comment by Aspidoquelona** [comment]
Interestingly, the problem has been solved by clearing the Browser (Firefox) cache.
