### ISSUE TITLE
Marking definition and organization segregation are applied to works management

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2712]
## Use case

Marking definition and organization segregation are applied to works management.

```
{“query”:{“bool”:{“must”:[{“bool”:{“should”:[{“term”:{“internal_id.keyword”:“work_bd8fd975-f2b6-489a-b706-04b5537b7e3e_2023-01-05T17:24:03.512Z”}},{“term”
:{“standard_id.keyword”:“work_bd8fd975-f2b6-489a-b706-04b5537b7e3e_2023-01-05T17:24:03.512Z”}},{“term”:{“x_opencti_stix_ids.keyword”:“work_bd8fd975-f2b6-4
89a-b706-04b5537b7e3e_2023-01-05T17:24:03.512Z”}}],“minimum_should_match”:1}},{“bool”:{“should”:[{“match_phrase”:{“entity_type.keyword”:“work”}},{“match_p
hrase”:{“parent_types.keyword”:“work”}}],“minimum_should_match”:1}},{“bool”:{“should”:[{“bool”:{“must_not”:[{“exists”:{“field”:“rel_object-marking.interna
l_id.keyword”}}]}},{“bool”:{“must_not”:[{“bool”:{“should”:[{“match”:{“rel_object-marking.internal_id.keyword”:“dd79a755-ba93-46eb-ad39-22dd1912e87f”}}],“m
inimum_should_match”:1}},{“bool”:{“should”:[{“match”:{“rel_object-marking.internal_id.keyword”:“244ca86a-1ba3-4411-97b5-cba24441ec46"}},{“match”:{“rel_obj
ect-marking.internal_id.keyword”:“4bb6addd-af7e-45d0-b80f-ba17320f9446”}},{“match”:{“rel_object-marking.internal_id.keyword”:“fdc3920d-67c7-46d0-993e-4a1d
f7415ca5"}}],“minimum_should_match”:1}}]}}],“minimum_should_match”:1}},{“bool”:{“should”:[{“match”:{“parent_types.keyword”:“Internal-Object”}},{“match_phr
ase”:{“entity_type.keyword”:“Internal-Object”}},{“match”:{“parent_types.keyword”:“Stix-Meta-Object”}},{“match_phrase”:{“entity_type.keyword”:“Stix-Meta-Ob
ject”}},{“match”:{“parent_types.keyword”:“stix-meta-relationship”}},{“match_phrase”:{“entity_type.keyword”:“stix-meta-relationship”}},{“match”:{“parent_ty
pes.keyword”:“Identity”}},{“match_phrase”:{“entity_type.keyword”:“Identity”}},{“match”:{“parent_types.keyword”:“Location”}},{“match_phrase”:{“entity_type.
keyword”:“Location”}},{“match”:{“rel_granted.internal_id.keyword”:“122b08b8-a821-4bd7-aa6f-253ea11ebf98”}}],“minimum_should_match”:1}}],“must_not”:[]}},“s
ize”:5000}
````

**Comment by SamuelHassine** [comment]
```{"category":"APP","error":{"stacktrace":["Error: Cannot return null for non-nullable field Mutation.workAdd.","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:594:13)","at /opt/opencti/build/node_modules/graphql/execution/execute.js:486:9","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at _ (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:501:14)","at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:407:22)","at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"workAdd","operation_query":"mutation workAdd($connectorId:String!$friendlyName:String){workAdd(connectorId:$connectorId friendlyName:$friendlyName){id}}","size":111,"time":18,"timestamp":"2023-01-05T15:29:54.001Z","type":"WRITE_ERROR","user":{"ip":"::ffff:172.18.0.1","user_id":"5d354a89-ded7-4b31-ae32-90f5226d679f"},"variables":{"connectorId":"bd8fd975-f2b6-489a-b706-04b5537b7e3e","friendlyName":"CrowdStrike @ 2023-01-05 15:29:53+00:00"},"version":"5.5.1"}```

**Comment by SamuelHassine** [comment]
```2023-01-03T20:55:09.584084332Z INFO:root:Listing Threat-Actors with filters null.
2023-01-03T20:55:09.989623074Z INFO:root:{“errors”:[{“message”:“Context creation failed: You can’t login without an organization”,“name”:“AuthFailure”}]}
2023-01-03T20:55:09.989646831Z
2023-01-03T20:55:09.990587703Z Traceback (most recent call last):
2023-01-03T20:55:09.990621392Z  File “/opt/opencti-connector-crowdstrike/main.py”, line 7, in <module>
2023-01-03T20:55:09.990626464Z   connector = CrowdStrike()
2023-01-03T20:55:09.990629460Z  File “/opt/opencti-connector-crowdstrike/crowdstrike/core.py”, line 188, in __init__
2023-01-03T20:55:09.990633614Z   self.helper = OpenCTIConnectorHelper(config)
2023-01-03T20:55:09.990637219Z  File “/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py”, line 547, in __init__
2023-01-03T20:55:09.990640848Z   self.api = OpenCTIApiClient(
2023-01-03T20:55:09.990643846Z  File “/usr/local/lib/python3.10/site-packages/pycti/api/opencti_api_client.py”, line 196, in __init__
2023-01-03T20:55:09.990647191Z   raise ValueError(
2023-01-03T20:55:09.990649766Z ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
2023-01-03T20:55:09.994910378Z Killed```
