### ISSUE TITLE
Question about AlienVault Connector

### ISSUE THREAD

**Issue by melisko9999** [LuatixHQ/opencti#2857]
Hey there, im trying to somehow get alievault connector working, i followed the tutorial on the YT, where i add config from 

[https://raw.githubusercontent.com/OpenCTI-Platform/connectors/master/external-import/alienvault/docker-compose.yml](url)

to stack editor and adjust fields so they look like this ...

`    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${dd9f52b9-c181-45eb-9856-9253ea0590bd}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=AlienVault
      - CONNECTOR_SCOPE=alienvault
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - ALIENVAULT_BASE_URL=https://otx.alienvault.com
      - ALIENVAULT_API_KEY=**HERE IS MY API KEY**
      - ALIENVAULT_TLP=White
      - ALIENVAULT_CREATE_OBSERVABLES=true
      - ALIENVAULT_CREATE_INDICATORS=true
      - ALIENVAULT_PULSE_START_TIMESTAMP=2020-05-01T00:00:00                 # BEWARE! Could be a lot of pulses!
      - ALIENVAULT_REPORT_TYPE=threat-report
      - ALIENVAULT_REPORT_STATUS=New
      - ALIENVAULT_GUESS_MALWARE=false                                        # Use tags to guess malware.
      - ALIENVAULT_GUESS_CVE=false                                            # Use tags to guess CVE.
      - ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES=FileHash-MD5,FileHash-SHA1  # Excluded Pulse indicator types.
      - ALIENVAULT_ENABLE_RELATIONSHIPS=true                                  # Enable/Disable relationship creation between SDOs.
      - ALIENVAULT_ENABLE_ATTACK_PATTERNS_INDICATES=true                      # Enable/Disable "indicates" relationships between indicators and attack patterns
      - ALIENVAULT_INTERVAL_SEC=120
    restart: always
    depends_on:
      - opencti`

and i update the stack in portainer, but nothing seems to work, i cant see the connector in my CTI instance, i keep getting this error in logs : Failure
Container 695f0e5b46a19d77d6c38beced45bbcbdaca1f95a8373cf2e0fa04976998ba98 is restarting, wait until the container is running , and i keep getting this error...

and another error `ValueError: {'name': 'Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?', 'message': 'Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?'}
Terminated
INFO INFO INFO INFO Listing Threat-Actors with filters null. | INFO INFO INFO INFO Listing Threat-Actors with filters null. | timestamp=2023-02-10T13:55:23.352062Z INFO INFO INFO INFO Listing Threat-Actors with filters null. | INFO INFO INFO INFO Listing Threat-Actors with filters null. | timestamp=2023-02-10T13:55:23.352062Z name=pycti.entities
INFO INFO INFO INFO Listing Threat-Actors with filters null. | INFO INFO INFO INFO Listing Threat-Actors with filters null. | timestamp=2023-02-10T13:55:23.420975Z INFO INFO INFO INFO Listing Threat-Actors with filters null. | INFO INFO INFO INFO Listing Threat-Actors with filters null. | timestamp=2023-02-10T13:55:23.420975Z name=pycti.entities
ERROR ERROR ERROR ERROR Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"? | ERROR ERROR ERROR ERROR Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"? | timestamp=2023-02-10T13:55:23.497493Z ERROR ERROR ERROR ERROR Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"? | ERROR ERROR ERROR ERROR Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"? | timestamp=2023-02-10T13:55:23.497493Z name=pycti.api
Traceback (most recent call last):
  File "/opt/opencti-connector-alienvault/main.py", line 7, in <module>
    connector = AlienVault()
  File "/opt/opencti-connector-alienvault/alienvault/core.py", line 161, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 614, in __init__
    connector_configuration = self.api.connector.register(self.connector)
  File "/usr/local/lib/python3.10/site-packages/pycti/api/opencti_api_connector.py", line 103, in register
    result = self.api.query(query, connector.to_input())
  File "/usr/local/lib/python3.10/site-packages/pycti/api/opencti_api_client.py", line 336, in query
    raise ValueError(
ValueError: {'name': 'Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?', 'message': 'Cannot query field "listen_routing" on type "ConnectorConfig". Did you mean "listen_exchange"?'}
Terminated`

any suggetsions ?

**Comment by melisko9999** [comment]
This issue can be closed, issue was solved simply by changing version from 5.5.4 to **:latest**

**before:** image: opencti/connector-alienvault:5.5.4
**after:**  image: opencti/connector-alienvault**:latest**

the more you know 🚀
