### ISSUE TITLE
An unknown error occurred after creating an horizontal graph based on entity type attack pattern and relations

### ISSUE THREAD

**Issue by mustaphajalloul** [LuatixHQ/opencti#2891]
## Description

 after creating a custom dashboard based onknowledge graphical  horizontal bar filtring by entity type Attack pattern  . an error occured:An unknown error occurred. Please contact your administrator or the OpenCTI maintainers. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 5.5.0 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. {add new custom dashbord
2. select horizontal bar 
4. select knowledge graph 
5. select attack pattern as entity type and validate

## Expected Output

a new graph with results 

## Actual Output

 An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.. 

## Additional information

 a part of logs
"reason":"Expect only one response","type":null},"internalData":{},"name":"DatabaseError","time_thrown":"2023-02-16T10:13:19.899Z"},"http_status":500,"reason":"Fail processing AggregationRelationsCount"},"stacktrace":["DatabaseError: A database error has occurred","at error (/opt/opencti/build/src/config/errors.js:8:10)","at DatabaseError (/opt/opencti/build/src/config/errors.js:47:48)","at /opt/opencti/build/src/database/engine.js:1500:13","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at distributionRelations (/opt/opencti/build/src/database/middleware.js:591:28)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"StixCoreRelationshipsHorizontalBarsDistributionQuery","operation_query":"query StixCoreRelationshipsHorizontalBarsDistributionQuery($field:String!$operation:StatsOperation!$startDate:DateTime$endDate:DateTime$dateAttribute:String$isTo:Boolean$limit:Int$elementId:[String]$elementWithTargetTypes:[String]$fromId:[String]$fromRole:String$fromTypes:[String]$toId:[String]$toRole:String$toTypes:[String]$relationship_type:[String]$confidences:[Int]$search:String$filters:[StixCoreRelationshipsFiltering]$filterMode:FilterMode$dynamicFrom:[StixCoreObjectsFiltering]$dynamicTo:[StixCoreObjectsFiltering]){stixCoreRelationshipsDistribution(field:$field operation:$operation startDate:$startDate endDate:$endDate dateAttribute:$dateAttribute isTo:$isTo limit:$limit elementId:$elementId elementWithTargetTypes:$elementWithTargetTypes fromId:$fromId fromRole:$fromRole fromTypes:$fromTypes toId:$toId toRole:$toRole toTypes:$toTypes relationship_type:$relationship_type confidences:$confidences search:$search filters:$filters filterMode:$filterMode dynamicFrom:$dynamicFrom dynamicTo:$dynamicTo){label value entity{__typename ...on BasicObject{__isBasicObject:__typename entity_type}...on BasicRelationship{__isBasicRelationship:__typename entity_type}...on AttackPattern{name description id}...on Campaign{name description id}...on CourseOfAction{name description id}...on Individual{name description id}...on Organization{name description id}...on Sector{name description id}...on System{name description id}...on Indicator{name description id}...on Infrastructure{name description id}...on IntrusionSet{name description id}...on Position{name description id}...on City{name description id}...on Country{name description id}...on Region{name description id}...on Malware{name description id}...on ThreatActor{name description id}...on Tool{name description id}...on Vulnerability{name description id}...on Incident{name description id}...on Event{name description id}...on Channel{name description id}...on Narrative{name description id}...on Language{name id}...on DataComponent{name id}...on DataSource{name id}...on StixCyberObservable{__isStixCyberObservable:__typename observable_value}...on Artifact{id}...on AutonomousSystem{id}...on BankAccount{id}...on CryptocurrencyWallet{id}...on CryptographicKey{id}...on Directory{id}...on DomainName{id}...on EmailAddr{id}...on EmailMessage{id}...on EmailMimePartType{id}...on ExternalReference{id}...on Grouping{id}...on Hostname{id}...on IPv4Addr{id}...on IPv6Addr{id}...on KillChainPhase{id}...on Label{id}...on MacAddr{id}...on MarkingDefinition{id}...on MediaContent{id}...on Mutex{id}...on NetworkTraffic{id}...on Note{id}...on ObservedData{id}...on Opinion{id}...on PaymentCard{id}...on PhoneNumber{id}...on Process{id}...on Report{id}...on Software{id}...on StixCoreRelationship{id}...on StixCyberObservableRelationship{id}...on StixFile{id}...on StixMetaRelationship{id}...on StixSightingRelationship{id}...on Text{id}...on Url{id}...on UserAccount{id}...on UserAgent{id}...on WindowsRegistryKey{id}...on WindowsRegistryValueType{id}...on X509Certificate{id}}}}","size":485,"time":1134,"timestamp":"2023-02-16T10:13:19.901Z","type":"READ_ERROR","user":{"ip":"::ffff:41.230.1.68","referer":"http://193.95.2.191:8080/dashboard/workspaces/dashboards/e0088011-5251-4f3e-84d7-287ffd94e4bc","user_id":"6095b2b0-b391-44c8-89f1-4ccd6f991813"},"variables":{"confidences":null,"dateAttribute":null,"dynamicFrom":[{"key":"entity_type","operator":"eq","values":["Attack-Pattern"]}],"dynamicTo":[],"elementId":null,"elementWithTargetTypes":null,"endDate":"2023-02-16T10:13:17.799Z","field":"entity_type","filterMode":null,"filters":[],"fromId":null,"fromRole":null,"fromTypes":null,"isTo":true,"limit":10,"operation":"count","relationship_type":null,"search":null,"startDate":"2023-01-16T00:00:00+01:00","toId":null,"toRole":null,"toTypes":null},"version":"5.5.0"} 

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/106604880/219350162-8e62375c-1d6d-462d-a599-2305cb2aeb84.png)

**Comment by SamuelHassine** [comment]
Hello @mustaphajalloul,

The error "Expect only one response" is linked to a duplicate in your platform. Please find the entity which is duplicated (having the same ID) and remove it. It will solve your problem.

Kind regards,
Samuel

**Comment by alice-debra** [comment]
Hello @mustaphajalloul,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
Kind regards,
Alice
