### ISSUE TITLE
Alienvault - Input resolve refs expect single value

### ISSUE THREAD

**Issue by adel-akloul-mox** [LuatixHQ/opencti#2920]
## Description

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/68532844/220879966-841412da-1faa-4d8d-a0ac-3b5f2a6bb3a6.png">

When starting Alienvault connector,  the log shows a ton of Error messages (see Actual output)

## Environment

1. OS (where OpenCTI server runs): AMZN2
2. OpenCTI version: 5.5.4
3. OpenCTI client: 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Actual Output

output of `sudo docker-compose -f --tail="10" opencti` 

```json
{
  "category": "APP",
  "error": {
    "data": {
      "category": "business",
      "http_status": 500,
      "key": "createdBy",
      "reason": "Input resolve refs expect single value",
      "values": [
        {
          "_index": "opencti_stix_domain_objects-000001",
          "base_type": "ENTITY",
          "confidence": 15,
          "contact_information": null,
          "created": "2023-01-06T04:51:03.464Z",
          "created_at": "2023-01-06T15:21:58.353Z",
          "creator_id": "88ec0c6a-13ce-5e39-b486-354fe4a7084f",
          "description": "",
          "entity_type": "Organization",
          "i_aliases_ids": [
            "aliases--9873fbd3-3297-5225-a6e6-3f53727646f2"
          ],
          "i_created_at_day": "2023-01-06",
          "i_created_at_month": "2023-01",
          "i_created_at_year": "2023",
          "i_group": {
            "destKey": "createdBy",
            "id": "identity--e52b2fa3-2af0-5e53-ad38-17d54b3d61cb",
            "multiple": false
          },
          "id": "597ad269-22fc-4cf9-b783-e92aa3c92e36",
          "identity_class": "organization",
          "internal_id": "597ad269-22fc-4cf9-b783-e92aa3c92e36",
          "lang": "en",
          "modified": "2023-01-06T04:51:03.464Z",
          "name": "AlienVault",
          "parent_types": [
            "Basic-Object",
            "Stix-Object",
            "Stix-Core-Object",
            "Stix-Domain-Object",
            "Identity"
          ],
          "revoked": false,
          "roles": null,
          "spec_version": "2.1",
          "standard_id": "identity--e52b2fa3-2af0-5e53-ad38-17d54b3d61cb",
          "updated_at": "2023-01-06T15:21:58.353Z",
          "x_opencti_aliases": null,
          "x_opencti_organization_type": null,
          "x_opencti_reliability": null,
          "x_opencti_stix_ids": []
        },
        {
          "_index": "opencti_stix_domain_objects-000001",
          "base_type": "ENTITY",
          "confidence": 15,
          "contact_information": null,
          "created": "2022-11-10T14:40:25.274Z",
          "created_at": "2022-11-10T14:42:24.920Z",
          "description": "",
          "entity_type": "Organization",
          "i_aliases_ids": [
            "aliases--9873fbd3-3297-5225-a6e6-3f53727646f2"
          ],
          "i_created_at_day": "2022-11-10",
          "i_created_at_month": "2022-11",
          "i_created_at_year": "2022",
          "i_group": {
            "destKey": "createdBy",
            "id": "identity--e52b2fa3-2af0-5e53-ad38-17d54b3d61cb",
            "multiple": false
          },
          "id": "16db66dc-1866-4976-bd0c-3068ad6bbc37",
          "identity_class": "organization",
          "internal_id": "16db66dc-1866-4976-bd0c-3068ad6bbc37",
          "lang": "en",
          "modified": "2022-11-10T14:40:25.274Z",
          "name": "AlienVault",
          "parent_types": [
            "Basic-Object",
            "Stix-Object",
            "Stix-Core-Object",
            "Stix-Domain-Object",
            "Identity"
          ],
          "revoked": false,
          "roles": null,
          "spec_version": "2.1",
          "standard_id": "identity--e52b2fa3-2af0-5e53-ad38-17d54b3d61cb",
          "updated_at": "2022-11-10T14:42:24.920Z",
          "x_opencti_aliases": null,
          "x_opencti_organization_type": null,
          "x_opencti_reliability": null,
          "x_opencti_stix_ids": []
        }
      ]
    },
    "stacktrace": [
      "UnsupportedError: Unsupported operation",
      "at error (/opt/opencti/build/src/config/errors.js:8:10)",
      "at UnsupportedError (/opt/opencti/build/src/config/errors.js:76:51)",
      "at /opt/opencti/build/src/database/middleware.js:664:13",
      "at Array.map (<anonymous>)",
      "at inputResolveRefs (/opt/opencti/build/src/database/middleware.js:658:56)",
      "at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2682:25)",
      "at createRelation (/opt/opencti/build/src/database/middleware.js:2815:16)",
      "at addStixCoreRelationship (/opt/opencti/build/src/domain/stixCoreRelationship.js:223:19)"
    ]
  },
  "inner_relation_creation": 1,
  "level": "error",
  "message": "API Call",
  "operation": "StixCoreRelationshipAdd",
  "operation_query": "mutation StixCoreRelationshipAdd($input:StixCoreRelationshipAddInput!){stixCoreRelationshipAdd(input:$input){id standard_id entity_type parent_types}}",
  "size": 637,
  "time": 98,
  "timestamp": "2023-02-23T10:01:46.273Z",
  "type": "WRITE_ERROR",
  "user": {
    "applicant_id": "88ec0c6a-13ce-5e39-b486-354fe4a7084f",
    "call_retry_number": "1",
    "ip": "::ffff:192.168.240.11",
    "user_id": "88ec0c6a-13ce-5e39-b486-354fe4a7084f"
  },
  "variables": {
    "input": {
      "confidence": 15,
      "created": "2023-02-23T09:04:44.284746Z",
      "createdBy": "identity--e52b2fa3-2af0-5e53-ad38-17d54b3d61cb",
      "description": "",
      "externalReferences": [],
      "fromId": "malware--99fb7fa5-5557-54f5-8b14-cfc13994d96d",
      "killChainPhases": [],
      "lang": null,
      "modified": "2023-02-23T09:04:44.284746Z",
      "objectLabel": [],
      "objectMarking": [
        "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
      ],
      "objectOrganization": null,
      "relationship_type": "uses",
      "revoked": null,
      "start_time": null,
      "stix_id": "relationship--2a68f82f-3221-5b74-bbfe-9ae2acd1760d",
      "stop_time": null,
      "toId": "attack-pattern--eb671754-50f0-5829-8d57-33b06b2b8e68",
      "update": false
    }
  },
  "version": "5.5.4"
}
```

**Comment by richard-julien** [comment]
Hi @adel-akloul-mox , its not directly related to the connector.
Looks like you have a duplication of the instance AlienVault .
One with id "16db66dc-1866-4976-bd0c-3068ad6bbc37" and one with id "597ad269-22fc-4cf9-b783-e92aa3c92e36
This situation should not happen and we continue to track how its still possible.
To resolve this situation you should be able to go to organizations screen and remove the most recent alienVault that is the duplicate. After the removal the data integration will be unstuck

**Comment by adel-akloul-mox** [comment]
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/68532844/220923142-79dea326-1b7b-48d4-8047-653b94940466.png">

You are totally right, removing the duplicate solved the issue.

I remember I had similar duplicate issue with marking definitions following an openCTI upgrade at the same period in January. Maybe issue is related to same release.
