### ISSUE TITLE
Source code error?

### ISSUE THREAD

**Issue by h4mr3r** [LuatixHQ/opencti#2934]
OS (where OpenCTI server runs): Debian11
OpenCTI version: 5.5.4 release

using https://filigran.notion.site/Manual-deployment-b911beba44234f179841582ab3894bb1, after yarn build i've got an error

`/root/opencti/node_modules/@whatwg-node/node-fetch/index.js:219
class PonyfillBlob extends buffer.Blob {
                                  ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/root/opencti/node_modules/@whatwg-node/node-fetch/index.js:219:35)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at createNodePonyfill (/root/opencti/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:15:24)
    at Object.<anonymous> (/root/opencti/node_modules/@whatwg-node/fetch/dist/node-ponyfill.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)`

**Comment by richard-julien** [comment]
Do you really try to build the version 3.5.4?

**Comment by rafael4ndre** [comment]
I am having this same issue with OpenCTI release 5.5.4. 

I bellieve I have all the requirements satisfied. No sure what is happening. Brand new instalation.

**Comment by h4mr3r** [comment]
> Do you really try to build the version 3.5.4?

Missclick 5.5.4 has this problem

**Comment by alice-debra** [comment]
Hello @h4mr3r,
We wanted to follow up to check if you are still experiencing the problem. If we are unable to reproduce the bug within the next few days, we may need to close this ticket.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
