### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by rafael4ndre** [LuatixHQ/opencti#2940]
## Description
On a brand new installation, when I tried to build with the "yarn build" command, I got the following error: 

/home/soc/opencti/node_modules/@whatwg-node/node-fetch/index.js:219
class PonyfillBlob extends buffer.Blob {
                                  ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/soc/opencti/node_modules/@whatwg-node/node-fetch/index.js:219:35)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at createNodePonyfill (/home/soc/opencti/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:15:24)
    at Object.<anonymous> (/home/soc/opencti/node_modules/@whatwg-node/fetch/dist/node-ponyfill.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server 22;04 LTS
2. OpenCTI version: 5.5.4
3. OpenCTI client: NA
4. Other environment details: Brand new Instalation on a brand new Ubuntu VM. All dependencies satisfied. 

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/16193394/222209048-974f8000-3f84-43fd-b593-ce12e0264d09.png)

**Comment by SamuelHassine** [comment]
Hello @rafael4ndre,

Which version of NodeJS are you using?

Kind regards,
Samuel

**Comment by rafael4ndre** [comment]
Not sure. But I installed nodejs using apt get on ubuntu 22.04. It is de default repository. 

I've been able to install openCTI (docker) after I openned this issue. I was trying to install mannualy but as I faced this "bug" I changed my mind and used the docker version. Working fine.

**Comment by rafael4ndre** [comment]
Did a quick search and find this is the packet: 

https://packages.ubuntu.com/jammy/nodejs
(12.22.9~dfsg-1ubuntu3)

I am not able to check on my server right now becouse I reverted a snapshoot to be able to deploy the docker version of openCTI, so the package is not installed on my server righ now.

**Comment by SamuelHassine** [comment]
What is the output of the command `node --version`?

**Comment by rafael4ndre** [comment]
~$ node --version
v12.22.9

**Comment by YgorAlberto** [comment]
I'm with the same problem. What was the solution?

**Comment by alice-debra** [comment]
Hello @rafael4ndre,
We wanted to follow up to check if you are still experiencing the problem. If we are unable to reproduce the bug within the next few days, we may need to close this ticket.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
