### ISSUE TITLE
Unable to Browse OpenCTI in HTTPS

### ISSUE THREAD

**Issue by cgedllist** [LuatixHQ/opencti#3018]
## Prerequisites

I followed all the steps shown in the document, issues and blogs.
Unable to bring the opencti in https, i am getting below error after changed the env values.

ERROR:
![image](https://user-images.githubusercontent.com/120620801/225101760-af41827e-9bb8-4648-ba5a-affb8ee1a130.png)

ENV File
![image](https://user-images.githubusercontent.com/120620801/225101862-77480d94-99ce-4c2e-8d8d-bbf0bf47562f.png)

## Environment

1. OS Ubuntu 20.4
2. OpenCTI version:5.5.4
3. OpenCTI client - used docker file.
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

followed the same steps
https://www.notion.so/luatix/93dd0f2899254b2581553d8b7df362da?v=979adbb6cb8b4e58aeef7c3bfb4c4624

**Comment by cgedllist** [comment]
After added the certificate im getting below error. please help.

2023-03-23T13:43:18.782672356Z {"category":"APP","level":"error","message":"[OPENCTI] Unhandled Rejection","promise":{},"reason":{"context":{},"message":"L2o.map is not a function","name":"TypeError","stack":"TypeError: L2o.map is not a function\n    at createHttpServer (/opt/opencti/build/src/http/httpServer.js:35:25)\n    at /opt/opencti/build/src/http/httpServer.js:101:29\n    at new Promise (<anonymous>)\n    at listenServer (/opt/opencti/build/src/http/httpServer.js:99:10)\n    at Object.start (/opt/opencti/build/src/http/httpServer.js:129:22)\n    at startModules (/opt/opencti/build/src/boot.js:35:22)\n    at platformStart (/opt/opencti/build/src/boot.js:170:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"timestamp":"2023-03-23T13:43:18.781Z","version":"5.6.2"}

**Comment by alice-debra** [comment]
Hello @cgedllist,
We wanted to follow up to check if you are still experiencing the problem. If we are unable to reproduce the bug within the next few days, we may need to close this ticket.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
