### ISSUE TITLE
Unable to display _Notes_ tab in _Analysis_ section

### ISSUE THREAD

**Issue by gregorygui** [LuatixHQ/opencti#3021]
## Description

Unable to display _Notes_ tab in _Analysis_ section after creation of a note

## Environment

1. OS (where OpenCTI server runs): Debian 11 - Docker
2. OpenCTI version: OpenCTI 5.6.2
3. OpenCTI client: Frontend

## Reproducible Steps

Add a _Note_ entity to a report, then unable to display _Notes_ tab in analysis section. The note is accessible via the report and can be modified.

Different tests have been conducted (for example removing all special char), but no result.

## Expected Output

Listing of notes in _Notes_ tab

## Actual Output

> Error
> An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Additional information

The opencti container logs:

```
{"category":"APP","error":{"stacktrace":["Error: Cannot return null for non-nullable field Note.content.","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:594:13)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:489:19)","at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at completeObjectValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:914:10)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:635:12)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:584:23)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:489:19)","at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at completeObjectValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:914:10)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:635:12)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:584:23)","at /opt/opencti/build/node_modules/graphql/execution/execute.js:696:25","at Function.from (<anonymous>)","at completeListValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:676:34)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:607:12)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:584:23)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"NotesLinesPaginationQuery","operation_query":"query NotesLinesPaginationQuery($search:String$count:Int!$cursor:ID$orderBy:NotesOrdering$orderMode:OrderingMode$filters:[NotesFiltering]){...NotesLines_data_2wN0PW}fragment NoteLine_node on Note{id entity_type attribute_abstract content created note_types likelihood confidence createdBy{__typename __isIdentity:__typename id name entity_type}objectMarking{edges{node{id definition_type definition x_opencti_order x_opencti_color}}}objectLabel{edges{node{id value color}}}creators{id name}status{id order template{name color id}}workflowEnabled}fragment NotesLines_data_2wN0PW on Query{notes(search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode filters:$filters){edges{node{id attribute_abstract content created createdBy{__typename __isIdentity:__typename id name entity_type}objectMarking{edges{node{id definition_type definition x_opencti_order x_opencti_color}}}...NoteLine_node __typename}cursor}pageInfo{endCursor hasNextPage globalCount}}}","size":90,"time":20,"timestamp":"2023-03-16T09:47:01.248Z","type":"READ_ERROR","user":{"ip":"::ffff:Y.Y.Y.Y","referer":"https://<HOST>/dashboard/analysis/notes?","user_id":"7ed5b42f-ec52-45bb-a7af-36bad8eac5e1"},"variables":{"count":25,"cursor":null,"filters":[],"orderBy":"created","orderMode":"desc","search":""},"version":"5.6.2"}
```

**Comment by richard-julien** [comment]
Hi, im not able to reproduce.
Looks like you have a note with an empty content in the database, situation that should not be possible.
Are you able to reproduce on the demo?

**Comment by SamuelHassine** [comment]
Closing due to inactivity.
