### ISSUE TITLE
Should OpenCTI log unsanitized passwords in errors

### ISSUE THREAD

**Issue by rlynch-ironnet** [LuatixHQ/opencti#3127]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I've got a workflow sending `$.level="error"` logs to a Slack channel for easier alerting of things. A coworker noticed the unredacted elastic creds in the below event. Should this be sanitized in the OpenCTI logs (regardless of me sending it to a Slack channel), or should the logs be treated as sensitive and I should to some post-processing?

```
Event: {
  "category": "APP",
  "error": {
    "data": {
      "category": "technical",
      "http_status": 401
    },
    "stacktrace": [
      "AuthFailure: Bad login or password",
      "at error (/opt/opencti/build/src/config/errors.js:8:10)",
      "at AuthenticationFailure (/opt/opencti/build/src/config/errors.js:12:56)",
      "at Object.token (/opt/opencti/build/src/resolvers/user.js:126:13)",
      "at processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
  },
  "inner_relation_creation": 0,
  "level": "error",
  "message": "API Call",
  "operation": "LoginFormMutation",
  "operation_query": "mutation LoginFormMutation($input:UserLoginInput!){token(input:$input)}",
  "size": 81,
  "time": 10,
  "timestamp": "2023-03-31T22:57:08.293Z",
  "type": "WRITE_ERROR",
  "variables": {
    "input": {
      "email": "my_elastic_account",
      "password": "my_elastic_password"
    }
  },
  "version": "5.6.2"
}
```

## Environment

1. OS (where OpenCTI server runs): AWS fategate
2. OpenCTI version: 5.6.2
3. OpenCTI client: backend logs
4. Other environment details: n/a

## Reproducible Steps

I'm not sure why I got a failure randomly while the platform was already running, otherwise I'd be having a different boot error.
So not really reproducible at the moment.

## Additional information

n/a

**Comment by rlynch-ironnet** [comment]
Looks like somebody (maybe me?) may have just thrown elastic creds into the login form. So its not really an elastic cred problem, but a user cred problem.

**Comment by llid3nlq** [comment]
I just made the same observation and came here to post the issue; found yours instead.

The platform logs contain plain text credentials where an incorrect password is entered. 
In some cases, this could lead to a system administrator gaining access to the intelligence platform where a user has mistyped their password.

**Comment by alice-debra** [comment]
Hello,
We’re following up to see if you are still experiencing this issue. As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice

**Comment by llid3nlq** [comment]
> Hello, We’re following up to see if you are still experiencing this issue. As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise. Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve. Kind regards, Alice

Still experiencing it? 
Did you fix the problem? If not, then it would still exist. 
I haven't used the platform since.

**Comment by alice-debra** [comment]
Hello, 
The keys you want to be redacted in the logs are manageable.
```
"logs_redacted_inputs":` [  "password",  "secret",  "token",  "api_token",  "authentication_value",  `"enterprise_license"],
```
Kind regards,
Alice
