### ISSUE TITLE
Error during migration to 5.7.0

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3185]
## Description

```
{
  "category": "APP",
  "error": {
    "context": {},
    "message": "Cannot read properties of null (reading 'label')",
    "name": "TypeError",
    "stack": "TypeError: Cannot read properties of null (reading 'label')\n    at /opt/opencti/build/src/database/utils.js:339:44\n    at Array.map (<anonymous>)\n    at /opt/opencti/build/src/database/utils.js:331:47\n    at Array.map (<anonymous>)\n    at generateUpdateMessage (/opt/opencti/build/src/database/utils.js:330:54)\n    at upsertElementRaw (/opt/opencti/build/src/database/middleware.js:2504:16)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at createEntityRaw (/opt/opencti/build/src/database/middleware.js:3032:22)\n    at createEntity (/opt/opencti/build/src/database/middleware.js:3124:16)\n    at addGroup (/opt/opencti/build/src/domain/group.js:57:19)\n    at ROo.up (/opt/opencti/build/src/migrations/1678399004325-roles-under-groups.js:24:24)"
  },
  "level": "error",
  "message": "[MIGRATION] Error during migration",
  "timestamp": "2023-04-17T22:50:17.762Z",
  "version": "5.7.0"
}
```

**Comment by SamuelHassine** [comment]
Output with error level to debug:

```
{"category":"APP","level":"info","message":"[MIGRATION] Read 12 migrations from the database","timestamp":"2023-04-17T23:13:51.277Z","version":"5.7.0"}
{"category":"APP","level":"info","message":"[MIGRATION] 3 migrations will be executed","timestamp":"2023-04-17T23:13:51.279Z","version":"5.7.0"}
{"category":"APP","level":"info","message":"[MIGRATION] Refacto roles under groups","timestamp":"2023-04-17T23:13:51.281Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"User"}},{"match_phrase":{"parent_types.keyword":"User"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true},"timestamp":"2023-04-17T23:13:51.282Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"Role"}},{"match_phrase":{"parent_types.keyword":"Role"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true},"timestamp":"2023-04-17T23:13:51.330Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] elInternalLoadById","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"term":{"internal_id.keyword":"group--22abb1ff-6ea9-5833-8bf1-aea5c4c971ce"}},{"term":{"standard_id.keyword":"group--22abb1ff-6ea9-5833-8bf1-aea5c4c971ce"}},{"term":{"x_opencti_stix_ids.keyword":"group--22abb1ff-6ea9-5833-8bf1-aea5c4c971ce"}}]}},{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"Group"}},{"match_phrase":{"parent_types.keyword":"Group"}}]}}],"must_not":[]}}},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_internal_relationships*","opencti_stix_meta_objects*","opencti_stix_meta_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_domain_objects*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observables*","opencti_inferred_entities*","opencti_inferred_relationships*"],"size":5000},"timestamp":"2023-04-17T23:13:51.472Z","version":"5.7.0"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'publisher' client ready","timestamp":"2023-04-17T23:13:51.593Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] elInternalLoadById","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"term":{"internal_id.keyword":"d7731dc3-f742-4cf9-ba95-66f6f4e61f68"}},{"term":{"standard_id.keyword":"d7731dc3-f742-4cf9-ba95-66f6f4e61f68"}},{"term":{"x_opencti_stix_ids.keyword":"d7731dc3-f742-4cf9-ba95-66f6f4e61f68"}}]}},{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"Group"}},{"match_phrase":{"parent_types.keyword":"Group"}}]}}],"must_not":[]}}},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_internal_relationships*","opencti_stix_meta_objects*","opencti_stix_meta_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_domain_objects*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observables*","opencti_inferred_entities*","opencti_inferred_relationships*"],"size":5000},"timestamp":"2023-04-17T23:13:51.616Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] elInternalLoadById","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"term":{"internal_id.keyword":"d7731dc3-f742-4cf9-ba95-66f6f4e61f68"}},{"term":{"standard_id.keyword":"d7731dc3-f742-4cf9-ba95-66f6f4e61f68"}},{"term":{"x_opencti_stix_ids.keyword":"d7731dc3-f742-4cf9-ba95-66f6f4e61f68"}},{"term":{"internal_id.keyword":"7cb7de52-0149-4670-ae3a-d46582c962ca"}},{"term":{"standard_id.keyword":"7cb7de52-0149-4670-ae3a-d46582c962ca"}},{"term":{"x_opencti_stix_ids.keyword":"7cb7de52-0149-4670-ae3a-d46582c962ca"}}]}}],"must_not":[]}}},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_internal_relationships*","opencti_stix_meta_objects*","opencti_stix_meta_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_domain_objects*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observables*","opencti_inferred_entities*","opencti_inferred_relationships*"],"size":5000},"timestamp":"2023-04-17T23:13:51.662Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"has-role"}},{"match_phrase":{"parent_types.keyword":"has-role"}}]}},{"nested":{"path":"connections","query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"connections.internal_id":"d7731dc3-f742-4cf9-ba95-66f6f4e61f68"}}]}},{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["connections.role"],"query":"*_from"}}]}}],"must_not":[]}}}},{"nested":{"path":"connections","query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"connections.internal_id":"7cb7de52-0149-4670-ae3a-d46582c962ca"}}]}},{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["connections.role"],"query":"*_to"}}]}}],"must_not":[]}}}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_relationships*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_meta_relationships*"],"track_total_hits":true},"timestamp":"2023-04-17T23:13:51.771Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"member-of"}},{"match_phrase":{"parent_types.keyword":"member-of"}}]}},{"nested":{"path":"connections","query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"connections.internal_id":"d7731dc3-f742-4cf9-ba95-66f6f4e61f68"}}]}},{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["connections.role"],"query":"*_to"}}]}}],"must_not":[]}}}},{"nested":{"path":"connections","query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"connections.types":"User"}}]}},{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["connections.role"],"query":"*_from"}}]}}],"must_not":[]}}}}],"must_not":[]}},"size":5000,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_relationships*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_meta_relationships*","opencti_inferred_relationships*"],"track_total_hits":true},"timestamp":"2023-04-17T23:13:51.853Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] elInternalLoadById","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"term":{"internal_id.keyword":"group--a7991a4f-6192-59a4-87d3-d006d2c41cc8"}},{"term":{"standard_id.keyword":"group--a7991a4f-6192-59a4-87d3-d006d2c41cc8"}},{"term":{"x_opencti_stix_ids.keyword":"group--a7991a4f-6192-59a4-87d3-d006d2c41cc8"}}]}},{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"Group"}},{"match_phrase":{"parent_types.keyword":"Group"}}]}}],"must_not":[]}}},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_internal_relationships*","opencti_stix_meta_objects*","opencti_stix_meta_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_domain_objects*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observables*","opencti_inferred_entities*","opencti_inferred_relationships*"],"size":5000},"timestamp":"2023-04-17T23:13:52.079Z","version":"5.7.0"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"stix-meta-relationship"}},{"match_phrase":{"parent_types.keyword":"stix-meta-relationship"}},{"match_phrase":{"entity_type.keyword":"stix-cyber-observable-relationship"}},{"match_phrase":{"parent_types.keyword":"stix-cyber-observable-relationship"}},{"match_phrase":{"entity_type.keyword":"stix-ref-relationship"}},{"match_phrase":{"parent_types.keyword":"stix-ref-relationship"}}]}},{"nested":{"path":"connections","query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"connections.internal_id":"c0f5cd97-1c79-41cc-a160-2ff07b3d827a"}}]}},{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["connections.role"],"query":"*_from"}}]}}],"must_not":[]}}}}],"must_not":[]}},"size":5000,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_relationships*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_meta_relationships*","opencti_inferred_relationships*"],"track_total_hits":true},"timestamp":"2023-04-17T23:13:52.125Z","version":"5.7.0"}
{"category":"APP","error":{"context":{},"message":"Cannot read properties of null (reading 'label')","name":"TypeError","stack":"TypeError: Cannot read properties of null (reading 'label')\n    at /opt/opencti/build/src/database/utils.js:339:44\n    at Array.map (<anonymous>)\n    at /opt/opencti/build/src/database/utils.js:331:47\n    at Array.map (<anonymous>)\n    at generateUpdateMessage (/opt/opencti/build/src/database/utils.js:330:54)\n    at upsertElementRaw (/opt/opencti/build/src/database/middleware.js:2504:16)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at createEntityRaw (/opt/opencti/build/src/database/middleware.js:3032:22)\n    at createEntity (/opt/opencti/build/src/database/middleware.js:3124:16)\n    at addGroup (/opt/opencti/build/src/domain/group.js:57:19)\n    at ROo.up (/opt/opencti/build/src/migrations/1678399004325-roles-under-groups.js:24:24)"},"level":"error","message":"[MIGRATION] Error during migration","timestamp":"2023-04-17T23:13:52.205Z","version":"5.7.0"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2023-04-17T23:13:52.229Z","version":"5.7.0"}
{"category":"APP","error":{"context":{"category":"technical","error":{},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:390:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:168:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-04-17T23:13:52.231Z","version":"5.7.0"}
```
