### ISSUE TITLE
Upgrade to 5.7.1 does not fix failed migration to 5.7.0

### ISSUE THREAD

**Issue by timbayley-vf** [LuatixHQ/opencti#3205]
## Description

We upgraded from 5.5.2 to 5.7.0, which led to this known issue: https://github.com/OpenCTI-Platform/opencti/issues/3185

Subsequently upgrading to 5.7.1 does not resolve the issue.

```
{"category":"APP","error":{"context":{},"message":"Cannot read properties of undefined (reading 'id')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'id')\n    at ROo.up (/opt/opencti/build/src/migrations/1679582135178-separate-case-types.js:41:68)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"level":"error","message":"[MIGRATION] Error during migration","timestamp":"2023-04-20T08:02:43.674Z","version":"5.7.1"}
```

## Environment

1. OS (where OpenCTI server runs):  COS on Kubernetes (GKE 1.23.16-gke.1400)
2. OpenCTI version: 5.7.1
3. OpenCTI client: frontend
4. Other environment details: GKE on COS, deployed using Helm

## Reproducible Steps
(not reproduced, but this should give the same result)

Steps to create the smallest reproducible scenario:
1. Install OpenCTI v5.5.2
2. Upgrade to v5.7.0
3. Upgrade to 5.7.1

## Expected Output
Initial migration fails on 5.7.0, then is subsequently resolved on migration to 5.7.1.
(in an ideal world... but this would require there to be a clean-up step in 5.7.1, which I assume is not included)

## Actual Output
Initial migration fails on 5.7.0, and continues to fail on migration to 5.7.1.

## Additional information

All logs on startup:

```
[ansible@599e55959a90 ~]$ kubectl logs opencti-opencti-767b8469dc-vbf2x -n opencti
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2023-04-20T08:02:42.608Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2023-04-20T08:02:42.610Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[SEARCH] Elasticsearch (8.4.3) client selected / runtime sorting enabled","timestamp":"2023-04-20T08:02:42.679Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2023-04-20T08:02:42.679Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2023-04-20T08:02:42.695Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2023-04-20T08:02:42.752Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'base' client ready","timestamp":"2023-04-20T08:02:42.757Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[REDIS] Clients initialized in Single mode","timestamp":"2023-04-20T08:02:42.758Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2023-04-20T08:02:42.758Z","version":"5.7.1"}
{"category":"APP","level":"warn","message":"[CHECK] SMTP seems down, email notification will may not work","timestamp":"2023-04-20T08:02:42.761Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2023-04-20T08:02:42.780Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'subscriber' client ready","timestamp":"2023-04-20T08:02:42.783Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Cache manager pub sub listener initialized","timestamp":"2023-04-20T08:02:42.783Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'lock' client ready","timestamp":"2023-04-20T08:02:42.786Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2023-04-20T08:02:42.787Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2023-04-20T08:02:42.841Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[INIT] admin user initialized","timestamp":"2023-04-20T08:02:43.350Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Read 598 migrations from the database","timestamp":"2023-04-20T08:02:43.611Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[MIGRATION] 2 migrations will be executed","timestamp":"2023-04-20T08:02:43.612Z","version":"5.7.1"}
{"category":"APP","error":{"context":{},"message":"Cannot read properties of undefined (reading 'id')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'id')\n    at ROo.up (/opt/opencti/build/src/migrations/1679582135178-separate-case-types.js:41:68)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"level":"error","message":"[MIGRATION] Error during migration","timestamp":"2023-04-20T08:02:43.674Z","version":"5.7.1"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2023-04-20T08:02:43.676Z","version":"5.7.1"}
{"category":"APP","error":{"context":{"category":"technical","error":{},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:390:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:168:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-04-20T08:02:43.676Z","version":"5.7.1"}
```

**Comment by SamuelHassine** [comment]
Fixed in #3202.

Will be ok in 5.7.2. ASAP.
