### ISSUE TITLE
OpenCTI Docker Swarm worker can't communicate with the manager node

### ISSUE THREAD

**Issue by Bella-chris** [LuatixHQ/opencti#3300]
## Description

My worker node can't communicate with manager node. My connectors containers don't startup whenever they are on the worker node. I created overlay network, forced default docker bridge network "docker_gwbridge", even used the opencti_default network and connectors fails to start even with resetting. I also tried to open ports over ubuntu firewall and conntainers couldn't communicate with OpenCTI API

Error: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/92671957/2dd9b998-48d8-48f1-b423-b477ca89d2b2)

INFO Listing Threat-Actors with filters null. | timestamp=2023-05-09T11:53:27.427596Z name=pycti.entities 
Traceback (most recent call last):
  File "/opt/opencti-connector-alienvault/main.py", line 7, in <module>
    connector = AlienVault()
  File "/opt/opencti-connector-alienvault/alienvault/core.py", line 161, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 590, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.10/site-packages/pycti/api/opencti_api_client.py", line 207, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
Terminated
## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: 5.7.3
3. OpenCTI client: Docker swarm mode 1 manager 1 worker
4. Other environment details:

**Comment by Bella-chris** [comment]
@SamuelHassine @richard-julien @nor3th Please assist

**Comment by CyberKaizen** [comment]
Are you trying this on one physical machine or VM?

**Comment by Bella-chris** [comment]
@CyberKaizen I have 2 VM on the same subnet and I tried to create for them an overlay network as well, but worker fails to communicate.

**Comment by alice-debra** [comment]
Hello @Bella-chris,
We’re following up to see if you still need an answer to this issue. As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Apologies for the lack of response regarding this question.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
