### ISSUE TITLE
[Retrieve more than 5000 results]

### ISSUE THREAD

**Issue by ShaanksM** [LuatixHQ/opencti#3322]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Hello,

I dont know why i have this error message depiste my "withPagination=True"
My goal is to retrieve all unrevoked ipv4 addresses

## My code : 

```
import json
import re
from pycti import OpenCTIApiClient

token = "xxx"

def is_valid_ipv4_address(address):
    pattern = r"^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$"
    return bool(re.match(pattern, address))



def main(token):
    opencti_api_client = OpenCTIApiClient("https://opencti.company.lan", token)

    customAttributes = """
    observables {
        edges {
            node {
                observable_value
            }
        }
    }
    revoked
    """

    ipv4_addresses = []
    after = None
    has_next_page = True

    while has_next_page:
        result = opencti_api_client.indicator.list(first=10000, after=after, filters=[
            {"key": "revoked", "values": "false"},
            {"key": "x_opencti_main_observable_type", "values": ["IPv4-Addr"]}
        ], withPagination=True, customAttributes=customAttributes)

        for entity in result['entities']:
            for observable in entity['observables']:
                observable_value = observable['observable_value']
                if is_valid_ipv4_address(observable_value):
                    ipv4_addresses.append(observable_value)

        has_next_page = result['pageInfo']['hasNextPage']
        after = result['pageInfo']['endCursor']

    # Write the IP addresses to a .txt file
    with open('ipv4_addresses.txt', 'w') as file:
        for ip in ipv4_addresses:
            file.write(ip + '\n')

if __name__ == "__main__":
    main(token)


```

## My error message (Only with first more than 5000) : 

INFO:pycti.entities:Listing Threat-Actors with filters null.
INFO:pycti.entities:Listing Indicators with filters [{"key": "revoked", "values": "false"}, {"key": "x_opencti_main_observable_type", "values": ["IPv4-Addr"]}].
ERROR:pycti.api:[SEARCH] You cannot ask for more than 5000 results. If you need more, please use pagination
Traceback (most recent call last):
  File "C:\Users\mboukrit\Desktop\python\test.py", line 52, in <module>
    main(token)
  File "C:\Users\mboukrit\Desktop\python\test.py", line 32, in main
    result = opencti_api_client.indicator.list(first=10000, after=after, filters=[
  File "C:\Users\mboukrit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycti\entities\opencti_indicator.py", line 230, in list
    result = self.opencti.query(
  File "C:\Users\mboukrit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycti\api\opencti_api_client.py", line 341, in query
    raise ValueError(
ValueError: {'name': 'DatabaseError', 'message': '[SEARCH] ``You cannot ask for more than 5000 results. If you need more, please use pagination'}``

## Environment

1. OS : Run locally script
2. OpenCTI version: Latest (i think)
3. OpenCTI client: pycti

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Copy / Paste my script
2. Run it with first at 5000
3. Run it with first at 5500, and see the difference

## Additional information

Idk the version of OpenCTI, b/c its a work for a company and i didnt have any information about opencti server.
however i have my token to play /w opencti api

**Comment by ShaanksM** [comment]
getAll (bool) – (optional) switch to return all entries (be careful to use this without any other filters) 
                                                 ^^^^^^^^^^^^^^^^^^^^^^
Its the way that i fixed the issue
