### ISSUE TITLE
can't create artifact, file, url and possible any other observable from the frontend

### ISSUE THREAD

**Issue by tomibennett** [LuatixHQ/opencti#3437]
## Description

Can't create observable from the frontend (e.g. an *artifact*). The field `x_opencti_files` is required and sent to the back through graphql but not accepted by the input type `ArtifactAddInput`.

## Environment

1. OpenCTI version: 5.7.6
2. OpenCTI client: frontend
4. Other environment details: on demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. go to the [observables dashboard](https://demo.opencti.io/dashboard/observations/observables)
3. select the `+` button to create a new observable
4. select `artifact`
5. fill the `name` field (the only required one)
6. submit the form

## Expected Output

The creation of the observable.

## Actual Output
An error message (see screenshot below)

## Additional information

Backend stacktrace:

```json
{
  "category": "APP",
  "error": {
    "stacktrace": [
      "GraphQLError: Variable \"$Artifact\" got invalid value { decryption_key: \"\", encryption_algorithm: \"\", mime_type: \"\", payload_bin: \"\", url: \"te\", x_opencti_additional_names: null, x_opencti_files: \"\" }; Field \"x_opencti_files\" is not defined by type \"ArtifactAddInput\".",
      "at /home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/values.js:147:11",
      "at coerceInputValueImpl (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/graphql/utilities/coerceInputValue.js:131:9)",
      "at coerceInputValue (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/graphql/utilities/coerceInputValue.js:32:10)",
      "at coerceVariableValues (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/values.js:132:52)",
      "at getVariableValues (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/values.js:45:21)",
      "at buildExecutionContext (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:280:45)",
      "at execute (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:116:22)",
      "at execute (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/apollo-server-core/src/requestPipeline.ts:501:20)",
      "at processGraphQLRequest (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/apollo-server-core/src/requestPipeline.ts:407:28)",
      "at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "at processHTTPRequest (/home/tom/softwares/filigran/opencti/opencti-platform/opencti-graphql/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)"
    ]
  },
  "inner_relation_creation": 0,
  "level": "error",
  "message": "API Call",
  "operation": "StixCyberObservableCreationMutation",
  "operation_query": "mutation StixCyberObservableCreationMutation($type:String!$x_opencti_score:Int$x_opencti_description:String$createIndicator:Boolean$createdBy:String$objectMarking:[String]$objectLabel:[String]$externalReferences:[String]$AutonomousSystem:AutonomousSystemAddInput$Directory:DirectoryAddInput$DomainName:DomainNameAddInput$EmailAddr:EmailAddrAddInput$EmailMessage:EmailMessageAddInput$EmailMimePartType:EmailMimePartTypeAddInput$Artifact:ArtifactAddInput$StixFile:StixFileAddInput$X509Certificate:X509CertificateAddInput$IPv4Addr:IPv4AddrAddInput$IPv6Addr:IPv6AddrAddInput$MacAddr:MacAddrAddInput$Mutex:MutexAddInput$NetworkTraffic:NetworkTrafficAddInput$Process:ProcessAddInput$Software:SoftwareAddInput$Url:UrlAddInput$UserAccount:UserAccountAddInput$WindowsRegistryKey:WindowsRegistryKeyAddInput$WindowsRegistryValueType:WindowsRegistryValueTypeAddInput$Hostname:HostnameAddInput$CryptographicKey:CryptographicKeyAddInput$CryptocurrencyWallet:CryptocurrencyWalletAddInput$Text:TextAddInput$UserAgent:UserAgentAddInput$BankAccount:BankAccountAddInput$PhoneNumber:PhoneNumberAddInput$PaymentCard:PaymentCardAddInput$MediaContent:MediaContentAddInput){stixCyberObservableAdd(type:$type x_opencti_score:$x_opencti_score x_opencti_description:$x_opencti_description createIndicator:$createIndicator createdBy:$createdBy objectMarking:$objectMarking objectLabel:$objectLabel externalReferences:$externalReferences AutonomousSystem:$AutonomousSystem Directory:$Directory DomainName:$DomainName EmailAddr:$EmailAddr EmailMessage:$EmailMessage EmailMimePartType:$EmailMimePartType Artifact:$Artifact StixFile:$StixFile X509Certificate:$X509Certificate IPv4Addr:$IPv4Addr IPv6Addr:$IPv6Addr MacAddr:$MacAddr Mutex:$Mutex NetworkTraffic:$NetworkTraffic Process:$Process Software:$Software Url:$Url UserAccount:$UserAccount WindowsRegistryKey:$WindowsRegistryKey WindowsRegistryValueType:$WindowsRegistryValueType Hostname:$Hostname CryptographicKey:$CryptographicKey CryptocurrencyWallet:$CryptocurrencyWallet Text:$Text UserAgent:$UserAgent BankAccount:$BankAccount PhoneNumber:$PhoneNumber PaymentCard:$PaymentCard MediaContent:$MediaContent){__typename id entity_type parent_types observable_value x_opencti_description created_at createdBy{__typename __isIdentity:__typename id name entity_type}objectMarking{edges{node{id definition_type definition x_opencti_order x_opencti_color}}}objectLabel{edges{node{id value color}}}}}",
  "size": 862,
  "time": 1,
  "timestamp": "2023-05-31T09:05:34.609Z",
  "type": "WRITE_ERROR",
  "user": {
    "ip": "::1",
    "referer": "http://localhost:3000/dashboard/observations/observables",
    "user_id": "88ec0c6a-13ce-5e39-b486-354fe4a7084f"
  },
  "variables": {
    "Artifact": {
      "decryption_key": "",
      "encryption_algorithm": "",
      "mime_type": "",
      "payload_bin": "",
      "url": "te",
      "x_opencti_additional_names": null,
      "x_opencti_files": ""
    },
    "AutonomousSystem": null,
    "BankAccount": null,
    "CryptocurrencyWallet": null,
    "CryptographicKey": null,
    "Directory": null,
    "DomainName": null,
    "EmailAddr": null,
    "EmailMessage": null,
    "EmailMimePartType": null,
    "Hostname": null,
    "IPv4Addr": null,
    "IPv6Addr": null,
    "MacAddr": null,
    "MediaContent": null,
    "Mutex": null,
    "NetworkTraffic": null,
    "PaymentCard": null,
    "PhoneNumber": null,
    "Process": null,
    "Software": null,
    "StixFile": null,
    "Text": null,
    "Url": null,
    "UserAccount": null,
    "UserAgent": null,
    "WindowsRegistryKey": null,
    "WindowsRegistryValueType": null,
    "X509Certificate": null,
    "createIndicator": false,
    "createdBy": null,
    "externalReferences": [],
    "objectLabel": [],
    "objectMarking": [],
    "type": "Artifact",
    "x_opencti_description": null,
    "x_opencti_score": 50
  },
  "version": "5.7.6"
}
```

## Screenshots (optional)
The error reproduced with a *software*.

![image](https://github.com/OpenCTI-Platform/opencti/assets/3235855/97023a0c-f99a-4285-b74e-2cd88764048d)

**Comment by richard-julien** [comment]
Fixed on commit https://github.com/OpenCTI-Platform/opencti/commit/c6990146b51f42e49f4ba3e0c5802b8f8ab5aa4c
Directly associated to the origin of the regression in 5.8 task,
