### ISSUE TITLE
OpenCTI 5.7.6 Fails to Initialize "previous initialization fail because you kill the platform" (bug)

### ISSUE THREAD

**Issue by YungBinary** [LuatixHQ/opencti#3487]
## Description

Upon upgrading to 5.7.6, we ran into the following issue, where initialization fails and recommends to delete all OpenSearch data. The suspected cause of this is health check capabilities for ECS tasks in AWS, where if the health check fails, the service is terminated and a new one is started.

```
{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"[INIT] Fail initialize schema, index already exists, previous initialization fail because you kill the platform before the end of the initialization. Please remove your elastic/opensearch data and restart."},"internalData":{},"name":"ConfigurationError","time_thrown":"2023-06-07T16:52:08.829Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n at error (/opt/opencti/build/src/config/errors.js:8:10)\n at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n at platformInit (/opt/opencti/build/src/initialization.js:385:13)\n at processTicksAndRejections (node:internal/process/task_queues:95:5)\n at platformStart (/opt/opencti/build/src/boot.js:168:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-06-07T16:52:08.831Z","version":"5.7.6"}
```

## Environment

1. OS (where OpenCTI server runs): AWS ECS
2. OpenCTI version: 5.7.6

## Expected Output

In the event that an upgrade is terminated, such as an unexpected shut down, i.e. AWS terminates what it thinks is an unhealthy instance. AWS is widely used as a deployment platform for OpenCTI, this same bug has been reported by others in the Slack community, and other AWS users may run into the same issue in the long-term, therefore it is expected for the initialization process to re-initialize successfully regardless if the app is terminated mid-upgrade or not.

**Comment by richard-julien** [comment]
`"[INIT] Fail initialize schema, index already exists, previous initialization fail because you kill the platform before the end of the initialization. Please remove your elastic/opensearch data and restart."`

This error happens when the initial query is not able to find the migration status of the platform.
It can be due to unavailability to your elastic, or problem in your data due to some problem that could be independant of opencti, thats hard to say.

You need to look into your elastic to see if data are still available, if shards are all green and available.

**Comment by aviyachki** [comment]
I personally experienced the same error when I ran out of space on my VM where I was testing OpenCTI. The containers were starting but ES was not able to start the shards and initialize the db.

**Comment by YungBinary** [comment]
> `"[INIT] Fail initialize schema, index already exists, previous initialization fail because you kill the platform before the end of the initialization. Please remove your elastic/opensearch data and restart."`
> 
> This error happens when the initial query is not able to find the migration status of the platform. It can be due to unavailability to your elastic, or problem in your data due to some problem that could be independant of opencti, thats hard to say.
> 
> You need to look into your elastic to see if data are still available, if shards are all green and available.

Thanks for the information, all shards are green and the cluster is showing good health. Any other ideas @richard-julien ? I suspect this happens due to AWS ECS restarting the service because the health check fails when the platform is not yet running and is initializing. Thus the migration fails mid-way and is unable to recover.

**Comment by tuedenn** [comment]
Same to me, i have try to run OpenCTI (`v5.8.0`) at my ubuntu server, recive the same error.
I have tried to stop all services, remove all images, and run `docker-compose up -d` again. But, it seems not work!
```
{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"[INIT] Fail initialize schema, index already exists, previous initialization fail because you kill the platform before the end of the initialization. Please remove your elastic/opensearch data and restart."},"internalData":{},"name":"ConfigurationError","time_thrown":"2023-06-21T08:50:09.815Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:385:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:183:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-06-21T08:50:09.818Z","version":"5.8.0"}
{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"[INIT] Fail initialize schema, index already exists, previous initialization fail because you kill the platform before the end of the initialization. Please remove your elastic/opensearch data and restart."},"internalData":{},"name":"ConfigurationError","time_thrown":"2023-06-21T08:51:13.718Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:385:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:183:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-06-21T08:51:13.721Z","version":"5.8.0"}
```

**Comment by tuedenn** [comment]
update: work around around .. and found the wordaroud solution:
stop docker service `service docker stop` and then run command `rm -Rf /var/lib/docker/*`
After purge all, restart docker `service docker start`
`docker-compose up -d` again, wait about 3m and done

**Comment by CreativeASAP** [comment]
same problem for me 
```
{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"[INIT] Fail initialize schema, index already exists, previous initialization fail because you kill the platform before the end of the initialization. Please remove your elastic/opensearch data and restart."},"internalData":{},"name":"ConfigurationError","time_thrown":"2023-11-08T14:07:07.559Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:394:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:219:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-11-08T14:07:07.562Z","version":"5.11.12"}
```

**Comment by szlf619** [comment]
version  6.3.6

this is because the history data from your previous installlation. 

Try to remove image data as follows:
### docker volume ls

find es data such as     opencti_esdata,  then  remove it:
### docker volume rm opencti_esdata

**Comment by alice-debra** [comment]
Hello,
We’re following up to see if @szlf619's solution has solved your problem. As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
