### ISSUE TITLE
 Support direct associated file with external reference option

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3534]
## Description

1. Go to Settings => Customization => Threat Actor => Enable reference on file upload
2. Try to create a threat actor in Threats => Threat Actor with a file in the creation form

```
Cannot import, element cannot be found.
```

```
{"category":"APP","error":{"data":{"category":"business","http_status":400,"reason":"Cannot import, element cannot be found."},"stacktrace":["FunctionalError: Business validation","at error (C:\\Users\\SamuelHassine\\Dropbox\\Developpement\\Associations\\Luatix\\Produits\\OpenCTI\\opencti-app\\opencti-platfo
rm\\opencti-graphql\\src\\config\\errors.js:8:10)","at FunctionalError (C:\\Users\\SamuelHassine\\Dropbox\\Developpement\\Associations\\Luatix\\Produits\\OpenCTI\\opencti-app\\opencti-platform\\opencti-graphql\\src\\config\\errors.js:83:50)","at uploadJobImport (C:\\Users\\SamuelHassine\\Dropbox\\Developpeme
nt\\Associations\\Luatix\\Produits\\OpenCTI\\opencti-app\\opencti-platform\\opencti-graphql\\src\\database\\file-storage.js:225:13)","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at upload (C:\\Users\\SamuelHassine\\Dropbox\\Developpement\\Associations\\Luatix\\Produits\\OpenCTI\\o
pencti-app\\opencti-platform\\opencti-graphql\\src\\database\\file-storage.js:328:5)","at buildEntityData (C:\\Users\\SamuelHassine\\Dropbox\\Developpement\\Associations\\Luatix\\Produits\\OpenCTI\\opencti-app\\opencti-platform\\opencti-graphql\\src\\database\\middleware.js:3031:18)","at createEntityRaw (C:\
\Users\\SamuelHassine\\Dropbox\\Developpement\\Associations\\Luatix\\Produits\\OpenCTI\\opencti-app\\opencti-platform\\opencti-graphql\\src\\database\\middleware.js:3154:20)","at createEntity (C:\\Users\\SamuelHassine\\Dropbox\\Developpement\\Associations\\Luatix\\Produits\\OpenCTI\\opencti-app\\opencti-plat
form\\opencti-graphql\\src\\database\\middleware.js:3195:16)","at addThreatActor (C:\\Users\\SamuelHassine\\Dropbox\\Developpement\\Associations\\Luatix\\Produits\\OpenCTI\\opencti-app\\opencti-platform\\opencti-graphql\\src\\domain\\threatActor.js:18:19)"]},"inner_relation_creation":0,"level":"error","messa
ge":"API Call","operation":"ThreatActorCreationMutation","operation_query":"mutation ThreatActorCreationMutation($input:ThreatActorAddInput!){threatActorAdd(input:$input){id name description entity_type parent_types ...ThreatActorCard_node}}fragment ThreatActorCard_node on ThreatActor{id name description cre
ated modified objectLabel{edges{node{id value color}}}objectMarking{edges{node{id definition_type definition x_opencti_order x_opencti_color}}}}","size":265,"time":140,"timestamp":"2023-06-16T05:51:26.705Z","type":"WRITE_ERROR","user":{"group_ids":["ac314496-4b89-4fd7-a91f-bdf5d6086bec","8119f826-aa1b-4aae-8
523-345051df2383"],"ip":"::1","organization_ids":[],"referer":"http://localhost:3000/dashboard/threats/threat_actors?sortBy=name&orderAsc=true&searchTerm=&filters=%7B%7D","socket":"query","user_id":"af5d19e6-dcbd-4f7e-8932-197b55c01491"},"variables":{"input":{"confidence":75,"description":"","externalReferences":[],"file":{"file":{"encoding":"7bit","filename":"campaign-iso.png","mimetype":"image/png"},"promise":{}},"name":"fdfdsffdfdsfdsfsdfdsfsdfd","objectLabel":[],"objectMarking":[],"threat_actor_types":[]}},"version":"5.7.6"}
````

**Comment by RomuDeuxfois** [comment]
Investigation : 
- No need to have enable reference enable to have the issue
- Other entities have this issue
