### ISSUE TITLE
Missing reference to handle creation in STIX import

### ISSUE THREAD

**Issue by 0q1627** [LuatixHQ/opencti#3775]
## Description

I want to import a STIX file obtained from a vendor. I can get to preview the content in http://host/dashboard/import/pending/<hash>. Then I press "Validate this workbench" button, the ImportFileStix connector is fired and it ends with 3 errors and no data imported.

## Environment

OpenCTI version: 5.9.0 - 5.9.2
OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Go to Data Import
Upload the STIX JSON file
... it becomes available in Analyst workbenches under Data Import
Preview the workbench
Press the "Validate this workbench" button in the upper right corner
... you are brought back to the Data Import page
you see the import task running but it ends with "ImportFileStix (10/10) - [ 3 errors ]", nothing is imported.

## Expected Output

I expected to have a report created from the STIX file.

## Actual Output

"ImportFileStix (10/10) - [ 3 errors ]"

## Additional information

Let me know how to pass the json.

This is the complete worker error:
[opencti-5.9.2-stix-import-error.txt](https://github.com/OpenCTI-Platform/opencti/files/12047659/opencti-5.9.2-stix-import-error.txt)

and for your convenience here's one of the three python errors:

```
"Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 224, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2360, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 814, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_identity.py", line 439, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_identity.py", line 372, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 224, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2360, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 814, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_identity.py", line 439, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_identity.py", line 372, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 224, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2360, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 814, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_identity.py", line 439, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_identity.py", line 372, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 224, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2360, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 814, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_identity.py", line 439, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_identity.py", line 372, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}
"}```

**Comment by RomuDeuxfois** [comment]
Hi,

The error 'Missing reference to handle creation' is fired when an ID is not present in the bundle and not found in existing DB (OpenCTI side).

Could you verify this case ?

Thank you

**Comment by SouadHadjiat** [comment]
Hello @0q1627, 
There is an issue with an indicator present in the stix file, could you share the file with us ? Could you send it by slack direct message ? You can join the filigran community slack here : https://community.filigran.io/ and you can contact me directly there (`@Souad`).

**Comment by SouadHadjiat** [comment]
Issue update : after investigation, the stix file is missing a required field for all indicators (`pattern_type`) and it is also missing an identity that is referenced by multiple entities.
