### ISSUE TITLE
Web Application Interface not accessible

### ISSUE THREAD

**Issue by uniquean777** [LuatixHQ/opencti#3843]
I have used docker installation method however all the dockers are perfectly running without any error. However the localhost server with 8080 port is not started. Please find the attached screenshots.

<img width="827" alt="2023-07-25" src="https://github.com/OpenCTI-Platform/opencti/assets/93477953/fdb666be-69a3-4d6d-8ec7-bbd3794c72b6">
<img width="552" alt="2023-07-25 -1" src="https://github.com/OpenCTI-Platform/opencti/assets/93477953/0cb771ed-c8d1-41b0-a4c1-e6709da10cec">

Can you please help out?

**Comment by uniquean777** [comment]
I changed the platform port to 9080 and tried restarting all the containers and again platform container started without any port:
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED          STATUS                   PORTS                                                                  NAMES
71c416731143   opencti/connector-export-file-csv:5.9.6               "/entrypoint.sh"         7 seconds ago    Up Less than a second                                                                           opencti_connector-export-file-csv.1.w4gxar5latr6v67btmdmfzr0w
591f6b3005a4   opencti/connector-import-file-stix:5.9.6              "/entrypoint.sh"         11 seconds ago   Up 2 seconds                                                                                    opencti_connector-import-file-stix.1.nlxc6sfbxxyhfibllfzzd0xfq
7068451b51cf   opencti/connector-export-file-txt:5.9.6               "/entrypoint.sh"         12 seconds ago   Up 3 seconds                                                                                    opencti_connector-export-file-txt.1.7cer4vmk7xpvv5aa479gsvcb8
070143b44f5d   opencti/connector-import-document:5.9.6               "/entrypoint.sh"         14 seconds ago   Up 6 seconds                                                                                    opencti_connector-import-document.1.l7ulbbvpsjb72ezk1d330rprx
2fbbaa9fe2fd   opencti/connector-export-file-stix:5.9.6              "/entrypoint.sh"         17 seconds ago   Up 9 seconds                                                                                    opencti_connector-export-file-stix.1.rjcew1mzz4zm1gdknz7z0gtwb
e0dbce154d2a   docker.elastic.co/elasticsearch/elasticsearch:8.8.2   "/bin/tini -- /usr/l…"   17 seconds ago   Up 9 seconds             9200/tcp, 9300/tcp                                                     opencti_elasticsearch.1.j8wr5n88437920jlc7530j0kk
73ea10396c98   opencti/platform:5.9.6                                "/sbin/tini -- node …"   17 seconds ago   Up 11 seconds                                                                                   opencti_opencti.1.051linyngf1rqt7lj696t8zlp
f6562a4c15a0   rabbitmq:3.12-management                              "docker-entrypoint.s…"   2 minutes ago    Up 2 minutes             4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 15691-15692/tcp, 25672/tcp   opencti_rabbitmq.1.hwn2inmws8yeu2rabi9tbjubo
9d7af50a4d37   minio/minio:RELEASE.2023-05-18T00-05-36Z              "/usr/bin/docker-ent…"   2 minutes ago    Up 2 minutes (healthy)   9000/tcp                                                               opencti_minio.1.q8oi36lvbohh9yh9uzcn4sn1t
26f289b2545c   redis:7.0.12                                          "docker-entrypoint.s…"   2 minutes ago    Up 2 minutes             6379/tcp                                                               opencti_redis.1.ske8cbyylt5oe60ttfggoa8jz

Then I ran 'docker run -p 9080:9080 opencti/platform:5.9.6' command to start the platform and encountered below error. As mentioned in above output the elasticsearch container running on port 9200.

{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2023-07-25T04:52:34.125Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2023-07-25T04:52:34.129Z","version":"5.9.6"}
{"category":"APP","error":{"context":{"category":"technical","error":"connect ECONNREFUSED 127.0.0.1:9200","http_status":500,"reason":"[SEARCH] Search engine seems down"},"message":"A configuration error has occurred","name":"ConfigurationError","stack":"ConfigurationError: A configuration error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:61:53)\n    at /opt/opencti/build/src/database/engine.js:185:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:175:3)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:138:3)\n    at platformStart (/opt/opencti/build/src/boot.js:179:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-07-25T04:52:34.172Z","version":"5.9.6"}

**Comment by addyPwN** [comment]
This seems like an issue with your docker configuration. I suggest you use docker-compose to build opencti. You can additionally pull portainer and install opencti using docker-compose and portainer.

**Comment by uniquean777** [comment]
Hey, Thanks for the quick response. however, I have tried it using the portainer as well but still facing the same issue.
<img width="788" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/93477953/15dd6ef5-81d2-4b32-a83d-8f9db4b253dd">

**Comment by uniquean777** [comment]
> This seems like an issue with your docker configuration. I suggest you use docker-compose to build opencti. You can additionally pull portainer and install opencti using docker-compose and portainer.

can you please help me with the proper guidance. I am still facing issues to deploy this application

**Comment by addyPwN** [comment]
Can you paste the contents of your docker-compose.yml that you used to build on portainer? Also, share the error log you are getting for the opencti-platform, elastic search and worker container.

**Comment by uniquean777** [comment]
Hey, Somehow i managed to create the containers now but they keep restarting also ports are not published for the platform. worker and platform container keeps restarting.
<img width="741" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/93477953/8b20c362-9c21-42fd-a1b2-63c4a2be277a">
Please find the below docker-compose file used for creating stack on portainer.
version: '3'
services:
  redis:
    image: redis:7.0.12
    restart: always
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      # Comment-out the line below for a cluster of multiple nodes
      - discovery.type=single-node
      # Uncomment the line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}    
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=rabbit01@localhost
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: always
  opencti:
    image: opencti/platform:5.9.6
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:5.9.6
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:5.9.6
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:5.9.6
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-txt:
    image: opencti/connector-export-file-txt:5.9.6
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_TXT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileTxt
      - CONNECTOR_SCOPE=text/plain
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:5.9.6
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-import-document:
    image: opencti/connector-import-document:5.9.6
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_DOCUMENT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportDocument
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/pdf,text/plain,text/html
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_ONLY_CONTEXTUAL=false # Only extract data related to an entity (a report, a threat actor, etc.)
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - IMPORT_DOCUMENT_CREATE_INDICATOR=true
    restart: always
    depends_on:
      - opencti

volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata:

**Comment by uniquean777** [comment]
also note that I am trying to install this on EC2 instance with ubuntu host OS

**Comment by TestBuddy22** [comment]
any suggestions?

**Comment by misterKr4bs** [comment]
also facing this issue. The docker-compose.yml im using initially worked and was able to interact with the UI however, after it sitting over the weekend i returned to this issue. Any fix for this yet?

**Comment by alice-debra** [comment]
Hello, 

Here are some suggestions to help troubleshoot and address any misconfiguration:

**Network configuration:**
- Ensure all services are on the same network. Add this to your docker-compose.yml for clarity:
```yaml
networks:
  default:
    driver: bridge
```
**Environment variables:**
- Verify values for variables like `${ELASTIC_MEMORY_SIZE}` are correctly set in an .env file or your environment.

**Service dependencies:**
- Add health checks to services like Elasticsearch to ensure they're ready before OpenCTI starts:
```
elasticsearch:
  healthcheck:
    test: ["CMD", "curl", "-s", "http://localhost:9200/_cat/health"]
    interval: 30s
    timeout: 10s
    retries: 5
```

**Port conflicts:**
- Ensure port 8080 isn’t occupied by another service on your host. Use netstat to check.

**Logs and errors:**
- Check Elasticsearch logs to ensure it runs without errors.

**Resource allocation:**
- Confirm sufficient memory is allocated to Docker for all services to run smoothly.

Kind regards,

Alice

**Comment by alice-debra** [comment]
Hello,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback. Please don’t hesitate to reopen the issue if you still have any questions.
Kind regards,
Alice
