### ISSUE TITLE
Blank after running for a day.

### ISSUE THREAD

**Issue by onepaanplus** [LuatixHQ/opencti#3876]
## Prerequisites

- [x ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [ x] I went through old GitHub issues and couldn't find anything relevant
- [ x] I googled the issue and didn't find anything relevant

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04.2 LTS
2. OpenCTI version: 5.9.6
3. OpenCTI client: frontend 
4. Other environment details:docker deployment on portainer. Server 4 cores and 16GB RAM

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Fresh opencti installation on portainer.
2. Successfully run the opencti for a day and then dashboard become blank
3. Elastic seems to be error.
4. Didnt modify any config for YML file.
## Additional information

elasticsearch logs
```
@timestamp=2023-07-29T15:17:28.683Z log.level=ERROR ecs.version=1.2.0 policy [opencti-ilm-policy] for index [opencti_internal_objects] failed on step [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}]. Moving to ERROR step | policy [opencti-ilm-policy] for index [opencti_internal_objects] failed on step [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}]. Moving to ERROR step | 
	at org.elasticsearch.xcore@8.8.2/org.elasticsearch.xpack.core.ilm.WaitForRolloverReadyStep.evaluateCondition(WaitForRolloverReadyStep.java:179)
	at org.elasticsearch.ilm@8.8.2/org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:235)
	at org.elasticsearch.ilm@8.8.2/org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:428)
	at org.elasticsearch.ilm@8.8.2/org.elasticsearch.xpack.ilm.IndexLifecycleService.triggered(IndexLifecycleService.java:356)
	at org.elasticsearch.server@8.8.2/org.elasticsearch.common.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:192)
	at org.elasticsearch.server@8.8.2/org.elasticsearch.common.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:226)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```
Everything else seems to be running fine for  day and then its blank when access to opencti. Question is how I can resolve this error

**Comment by nino-filigran** [comment]
@onepaanplus did you manage to get support for your issue?

**Comment by nino-filigran** [comment]
Closing this for now as I did not get any reponse.
