### ISSUE TITLE
Data ingestion failing 

### ISSUE THREAD

**Issue by openctitest** [LuatixHQ/opencti#4024]
## Description
Data synchronization not completing between main opencti instance and sub instances

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Centos 7
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
OpenCTI 5.9.5
3. OpenCTI client: { e.g. frontend or python }
frontend
4. Other environment details:
Running as docker containers

## Reproducible Steps
We have 3 clusters of OpenCTI, one is the main and two are secondary. The main runs a data data sharing stream and the two secondary have ingests set up. The synchronization starts but is not completing. At the time it stops the following error is seen in the logs:

ERR [OPENCTI-MODULE] Error executing notification manager (live) | category=APP error{"context":{"category":"business", "http_status":500, "reason":"No representative extractor available of User"}, "message":"Unsupported operation","name":"Unsupported operation","name":"UnsupportedError","stack":"UnsupportedError: Unsupported operation\n at error (/opt/opencti/build/src/config/errors.js:8:10)\n at UnsupportedError (/opt/opencti/build/src/config/errors.js:76:51) ... at processingLoop (/opt/opencti/build/src/database/redis.ts:67:13)"} timestamp=2023-08-09T11:48:47.324Z version=5.9.5

## Expected Output

Expect synchronization to occur

## Actual Output

Synchronization is not completing

**Comment by Archidoit** [comment]
Hello! Can you indicate which triggers you have?

**Comment by openctitest** [comment]
I'm not sure exactly what information you need here, on the main instance of opencti I have a live stream set to public with no filters applied

**Comment by Archidoit** [comment]
Can you provide the stream events that are just before the timestamp of your error?

Can you also indicates if you have triggers ? Triggers can be found by following these steps:
- click on the bell at the top right of your platform 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/34e25a78-0b96-4a1c-9390-93ac10834852)
- click on the 'triggers and digests' tab

**Comment by openctitest** [comment]
Thanks for the info. I do not see any stream events and there are no triggers

**Comment by RomuDeuxfois** [comment]
Hi,

About stream events, you don't have any in your redis?
If you have redis-insight, you can view all events on the platform.

![image](https://github.com/OpenCTI-Platform/opencti/assets/53513584/18955344-aabd-4bbd-b8c6-101d67717cff)

**Comment by nino-filigran** [comment]
@openctitest is this issue still needed?

**Comment by Jipegien** [comment]
closed for no activity
