### ISSUE TITLE
Data > Connectors page reports "An unknown error occured. Please contact your administrator or the OpenCTI maintainers"

### ISSUE THREAD

**Issue by NexusFuzzy** [LuatixHQ/opencti#4027]
## Description

After upgrading to the most recent version (5.9.6) through copying the most recent version of the docker-compose-yml from https://github.com/OpenCTI-Platform/docker.git, I noticed that the "Connectors" page does not work anymore.

I checked the status of the connectors on the CLI and could see that they are working as expected and also new data flows in. The only thing broken seems to be the connectors page. I digged a little deeper and after clicking on the "Connectors" link in the Web UI the two following entries are logged in the platform docker container:

```
{"category":"APP","error":{"stacktrace":["Error: socket hang up","at Function.eX.from (/opt/opencti/build/node_modules/axios/lib/core/AxiosError.js:89:14)","at RS.handleRequestError (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:591:25)","at RS.emit (node:events:512:28)","at ClientRequest.uVt.<computed> (/opt/opencti/build/node_modules/follow-redirects/index.js:14:24)","at ClientRequest.emit (node:events:512:28)","at Socket.socketOnEnd (node:_http_client:519:9)","at Socket.emit (node:events:524:35)","at endReadableNT (node:internal/streams/readable:1378:12)","at processTicksAndRejections (node:internal/process/task_queues:82:21)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"ConnectorsStatusQuery","operation_query":"query ConnectorsStatusQuery{...ConnectorsStatus_data}fragment ConnectorsStatus_data on Query{connectors{id name active auto connector_type connector_scope updated_at config{listen listen_exchange push push_exchange}}rabbitMQMetrics{queues{name messages messages_ready messages_unacknowledged consumers idle_since message_stats{ack ack_details{rate}}}}}","size":2,"time":19,"timestamp":"2023-08-10T07:20:22.128Z","type":"READ_ERROR","user":{"group_ids":["4ed7637f-efd5-4d5d-94dc-a37e8d507b4d"],"ip":"::ffff:10.0.0.2","organization_ids":[],"referer":"[http://REDACTED:8080/dashboard/data/connectors","socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{},"version":"5.9.6"}](http://REDACTED:8080/dashboard/data/connectors%22,%22socket%22:%22query%22,%22user_id%22:%2288ec0c6a-13ce-5e39-b486-354fe4a7084f%22%7D,%22variables%22:%7B%7D,%22version%22:%225.9.6%22%7D)

{"category":"APP","error":{"stacktrace":["Error: socket hang up","at Function.eX.from (/opt/opencti/build/node_modules/axios/lib/core/AxiosError.js:89:14)","at RS.handleRequestError (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:591:25)","at RS.emit (node:events:512:28)","at ClientRequest.uVt.<computed> (/opt/opencti/build/node_modules/follow-redirects/index.js:14:24)","at ClientRequest.emit (node:events:512:28)","at Socket.socketOnEnd (node:_http_client:519:9)","at Socket.emit (node:events:524:35)","at endReadableNT (node:internal/streams/readable:1378:12)","at processTicksAndRejections (node:internal/process/task_queues:82:21)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"WorkersStatusQuery","operation_query":"query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}","size":2,"time":22,"timestamp":"2023-08-10T07:20:22.131Z","type":"READ_ERROR","user":{"group_ids":["4ed7637f-efd5-4d5d-94dc-a37e8d507b4d"],"ip":"::ffff:10.0.0.2","organization_ids":[],"referer":"[http://REDACTED:8080/dashboard/data/connectors","socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{},"version":"5.9.6"}](http://REDACTED:8080/dashboard/data/connectors%22,%22socket%22:%22query%22,%22user_id%22:%2288ec0c6a-13ce-5e39-b486-354fe4a7084f%22%7D,%22variables%22:%7B%7D,%22version%22:%225.9.6%22%7D)
```

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. } - SLES 15-SP3
3. OpenCTI version: { e.g. OpenCTI 1.0.2 } - 5.9.6
4. OpenCTI client: { e.g. frontend or python } - Frontend
5. Other environment details: - OpenCTI running as docker

## Reproducible Steps

1. Log in
2. Click on Data > Connectors

## Expected Output

Show status of connectors

## Actual Output

Error message

## Additional information

See above

**Comment by NexusFuzzy** [comment]
Probable duplicate to https://github.com/OpenCTI-Platform/opencti/issues/1460, closing
