### ISSUE TITLE
Missing reference to handle creation 

### ISSUE THREAD

**Issue by The-Stuke** [LuatixHQ/opencti#4043]
## Description

I have noticed when querying one of our TAXII feeds that the TAXII connector sends the bundles to OpenCTI and can import data such as external references, but it does not appear to be to be creating observables/indicators in the platform.

## Environment

1. OS: Docker
2. OpenCTI version: 5.9.0, but was not working on prior versions in the past months. Not sure when it started to fail.
3. OpenCTI client: NA

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run TAXII2 connector
2. Have it query TAXII server for new objects
3. Observe errors in worker logs/see no new observable created

## Expected Output

In Progress and Complete Works to be generated for the connector along with observables/indicators created.

## Actual Output

Connector sends bundles to OpenCTI. Worker fails with below error stating "Missing reference to handle creation"

Connector Output
```
INFO Connector last run: 2023-08-10 03:01:26 | timestamp=2023-08-10T04:30:03.174905Z name=pycti.connector
INFO Polling entire API root Public API Root | timestamp=2023-08-10T04:30:05.404555Z name=pycti.connector
INFO Polling Collection Public Collection | timestamp=2023-08-10T04:30:07.437365Z name=pycti.connector
INFO Sending Bundle to server with '40493' objects | timestamp=2023-08-10T15:07:23.900155Z name=pycti.connector
INFO Run Complete. Sleeping until next run in 1 hours | timestamp=2023-08-10T15:07:24.983844Z name=pycti.connector
```

Worker error
```
ERROR Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 224, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2357, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 814, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_opinion.py", line 561, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_opinion.py", line 422, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 224, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2357, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 814, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_opinion.py", line 561, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_opinion.py", line 422, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 224, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2357, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 814, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_opinion.py", line 561, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_opinion.py", line 422, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 224, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2357, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 814, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_opinion.py", line 561, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_opinion.py", line 422, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}
 | timestamp=2023-08-10T15:11:40.162553Z name=pycti.api
```

## Additional information

The connector has bypass all capabilities to ensure there was no permission issue.

Created the Git issue https://github.com/OpenCTI-Platform/connectors/issues/1288 as I thought this was specific to the TAXII connector, but it looks to be more related to how the worker handles the file.

Sample indicator that was imported from the connector
```json
{
      "type": "indicator",
      "spec_version": "2.1",
      "id": "indicator--81af5e1c-04b2-4865-a53a-e67b17737dda",
      "created_by_ref": "identity--bc4bc868-77f8-4692-a96e-97f95d7526c8",
      "created": "2023-07-12T08:10:02.424194Z",
      "modified": "2023-07-12T08:10:02.424194Z",
      "name": "metasploitselfsignedca Control Server at X.X.X.X",
      "description": "Malware Control Server",
      "indicator_types": [
        "command-and-control"
      ],
      "pattern": "[ipv4-addr:value = 'X.X.X.X']",
      "pattern_type": "stix",
      "pattern_version": "2.1",
      "valid_from": "2023-07-12T08:10:02.424194Z",
      "object_marking_refs": [
        "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da",
        "marking-definition--77bf6aa4-2787-414c-955d-6c789b482685"
      ]
    }
```

## Screenshots (optional)
The connector not showing any in progress/completed works.
![image](https://github.com/OpenCTI-Platform/opencti/assets/48042955/49c08d87-86ea-44aa-9c6b-ada109590c2a)

**Comment by Jipegien** [comment]
Will it be covered by the new built-in TAXII client @richard-julien?

**Comment by Jipegien** [comment]
@The-Stuke From 5.10, the way we handle incoming TAXII collection will be updated. The worker will not stop even if there is missing refs and will continue to import everything it can. In your case, some object will have some missing references but it will continue and create the following objects.
