### ISSUE TITLE
Can not delete 'related-to' relationship from specific types

### ISSUE THREAD

**Issue by debelyoo** [LuatixHQ/opencti#4156]
## Description

Relationships of type 'related-to' from Text objects or Hostname objects can not be deleted.

## Environment

1. OS (where OpenCTI server runs): Official OpenCTI docker image (base image: node:20-alpine)
2. OpenCTI version: 5.8.7
3. OpenCTI client: frontend and python

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select a relationship from a text object to a malware (or intrusion-set)
2. Delete it
3. An error message is shown ("Type X-OpenCTI-Text not supported")
OR
1. Select a relationship from a hostname object to a malware (or intrusion-set)
2. Delete it
3. An error message is shown ("Type X-OpenCTI-Hostname not supported")

## Expected Output

The relationship should be deleted.

## Actual Output

An error message is displayed. The relationship is not deleted.

## Additional information

It works for 'related-to' relationships from IP, domain, URL, file.

**Comment by SouadHadjiat** [comment]
Do you reproduce this issue with newly created Text or Hostname objects ? Does it happen with specific Text / Hostname objects ? @debelyoo

**Comment by debelyoo** [comment]
I can't reproduce it with newly created relationships. Apparently it happens only on old relationships. It happens only with Text and Hostname objects (works fine with other SCO such as domains, IPs, or URL).

**Comment by Archidoit** [comment]
Do you have more logs or error message to provide (from your console / backend) ?

**Comment by debelyoo** [comment]
The error log I see in the backend:
```
{"category":"APP","error":{"data":{"category":"technical","http_status":500,"reason":"Type X-OpenCTI-Text not supported"},"stacktrace":["DatabaseError: A database error has occurred","at error (/opt/opencti/build/src/config/errors.js:8:10)","at DatabaseError (/opt/opencti/build/src/config/errors.js:54:48)","at getParentTypes (/opt/opencti/build/src/schema/schemaUtils.js:136:11)","at Object.computeCache (/opt/opencti/build/src/schema/schema-relationsRef.ts:58:7)","at Object.convertDatabaseNameToInputName (/opt/opencti/build/src/schema/schema-relationsRef.ts:102:10)","at keyFn (/opt/opencti/build/src/database/middleware.js:419:69)","at t.f (/opt/opencti/build/node_modules/ramda/es/reduceBy.js:60:15)","at t.@@transducer/step (/opt/opencti/build/node_modules/ramda/es/internal/_xwrap.js:17:17)","at arrayReduce (/opt/opencti/build/node_modules/ramda/es/internal/_xArrayReduce.js:6:33)","at xReduce_default (/opt/opencti/build/node_modules/ramda/es/internal/_createReduce.js:6:14)","at reduceBy (/opt/opencti/build/node_modules/ramda/es/reduceBy.js:71:10)","at /opt/opencti/build/node_modules/ramda/es/internal/_dispatchable.js:44:15","at /opt/opencti/build/node_modules/ramda/es/internal/_curryN.js:40:27","at /opt/opencti/build/node_modules/ramda/es/internal/_arity.js:16:19"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"StixCoreRelationshipEdit","operation_query":"mutation StixCoreRelationshipEdit($id:ID!){stixCoreRelationshipEdit(id:$id){delete}}","size":45,"time":66,"timestamp":"2023-08-25T09:24:03.878Z","type":"WRITE_ERROR","user":{"group_ids":["fb3d0691-748a-4a1e-9056-1ea3e672fccb"],"ip":"::ffff:127.0.0.1","organization_ids":[],"socket":"query","user_id":"517d0a78-fec0-4b28-9111-94c76ad00cc5"},"variables":{"id":"1beef675-a000-4abc-bab3-b924c49722a4"},"version":"5.8.7"}
```

**Comment by ristowee** [comment]
Hi,
I seem to have the same kind of problems with X-OpenCTI-Hostname and X-OpenCTI-Cryptocurrency-Wallet and @SouadHadjiat asked me to report my issues here.

We have been trying to modify TLP markings in a background process (remove TLP:CLEAR and add TLP:AMBER). Some of the objects have probably not been migrated properly and we see the same error. That log contains 5k objects and is truncated but if I try to modify a single object in the UI I get this:
```
{
  "category": "APP",
  "error": {
    "data": {
      "category": "technical",
      "http_status": 500,
      "reason": "Type X-OpenCTI-Hostname not supported"
    },
    "stacktrace": [
      "DatabaseError: A database error has occurred",
      "at error (/opt/opencti/build/src/config/errors.js:8:10)",
      "at DatabaseError (/opt/opencti/build/src/config/errors.js:54:48)",
      "at getParentTypes (/opt/opencti/build/src/schema/schemaUtils.js:149:11)",
      "at Object.computeCache (/opt/opencti/build/src/schema/schema-relationsRef.ts:58:7)",
      "at Object.convertDatabaseNameToInputName (/opt/opencti/build/src/schema/schema-relationsRef.ts:106:10)",
      "at keyFn (/opt/opencti/build/src/database/middleware.js:419:69)",
      "at t.f (/opt/opencti/build/node_modules/ramda/es/reduceBy.js:60:15)",
      "at t.@@transducer/step (/opt/opencti/build/node_modules/ramda/es/internal/_xwrap.js:17:17)",
      "at arrayReduce (/opt/opencti/build/node_modules/ramda/es/internal/_xArrayReduce.js:6:33)",
      "at xReduce_default (/opt/opencti/build/node_modules/ramda/es/internal/_createReduce.js:6:14)",
      "at reduceBy (/opt/opencti/build/node_modules/ramda/es/reduceBy.js:71:10)",
      "at /opt/opencti/build/node_modules/ramda/es/internal/_dispatchable.js:44:15",
      "at /opt/opencti/build/node_modules/ramda/es/internal/_curryN.js:40:27",
      "at /opt/opencti/build/node_modules/ramda/es/internal/_arity.js:16:19"
    ]
  },
  "inner_relation_creation": 0,
  "level": "error",
  "message": "API Call",
  "operation": "StixCyberObservablePopoverDeletionMutation",
  "operation_query": "mutation StixCyberObservablePopoverDeletionMutation($id:ID!){stixCyberObservableEdit(id:$id){delete}}",
  "size": 45,
  "time": 2436,
  "timestamp": "2023-08-30T09:09:01.404Z",
  "type": "WRITE_ERROR",
  "user": {
    "group_ids": [
      "ed761d52-169e-4a7e-adaf-7882b5df5fe1",
      "7452e9cb-8953-428d-aa8d-42e1a4d1e419"
    ],
    "ip": "::ffff:10.73.12.63",
    "organization_ids": [
    ],
    "referer": "https://opencti.local/dashboard/observations/observables/56da2345-e3df-475e-8f4c-b837d76de68f",
    "socket": "query",
    "user_id": "7c8973fb-af5d-4ede-b76c-963d3e366cb3"
  },
  "variables": {
    "id": "56da2345-e3df-475e-8f4c-b837d76de68f"
  },
  "version": "5.9.6"
}
```

**Comment by SouadHadjiat** [comment]
@ristowee could you give the entity_type of the observable that causes the error ? The result of this query :
```
query {
  stixCyberObservable(id: "56da2345-e3df-475e-8f4c-b837d76de68f") {
    id
    entity_type
  }
}
```
To know for sure if the observable itself doesn't have the right entity type, or if it has relationships with the wrong type.

**Comment by ristowee** [comment]
I checked a few observables with `x-opencti-hostname--` prefix in their `standard_id` and the `entity_type` seems to be "Hostname" (no "X-OpenCTI-" seen there).

**Comment by debelyoo** [comment]
Hi, I upgraded to version 5.10.3, and retried to delete the relationships that were failing before but I still have an issue (different than the previous one though):
```
ValueError: {'name': "Cannot read properties of null (reading 'multiple')", 'message': "Cannot read properties of null (reading 'multiple')"}
```
