### ISSUE TITLE
Yarn install error : Node-gyp failed to build your package

### ISSUE THREAD

**Issue by Damag3dRoot** [LuatixHQ/opencti#4160]
## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.4
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }

hello,

I have an error when i want to install manualy opencti

When i lunch "yarn install" i have this error : 

```
sudo yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @graphql-tools/graphql-tag-pluck@npm:7.5.2 [cb903] doesn't provide @babel/core (p4ba6e), requested by @babel/plugin-syntax-import-assertions
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (pebcd9) with version 16.7.1, which doesn't satisfy what graphql-import and some of its descendants request
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (p2c3b2) with version 16.7.1, which doesn't satisfy what merge-graphql-schemas and some of its descendants request
➤ YN0060: │ opencti-graphql@workspace:. provides vitest (p9588b) with version 0.29.8, which doesn't satisfy what @vitest/coverage-istanbul requests
➤ YN0002: │ opencti-graphql@workspace:. doesn't provide webpack (p25690), requested by ts-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 658ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 57ms
➤ YN0000: ┌ Link step
➤ YN0007: │ node-calls-python@patch:node-calls-python@npm%3A1.7.7#./patch/node-calls-python-1.7.7.patch::version=1.7.7&hash=5402a7&locator=opencti-graphql%40workspace%3A. must be built because it never has been before or the last one failed
➤ YN0009: │ node-calls-python@patch:node-calls-python@npm%3A1.7.7#./patch/node-calls-python-1.7.7.patch::version=1.7.7&hash=5402a7&locator=opencti-graphql%40workspace%3A. couldn't be built successfully (exit code 7, logs can be found here: /tmp/xfs-7d43ed1f/build.log)
➤ YN0000: └ Completed in 1s 927ms
➤ YN0000: Failed with errors in 3s 847ms
```

And the build.log : 
```

# This file contains the result of Yarn building a package (node-calls-python@patch:node-calls-python@npm%3A1.7.7#./patch/node-calls-python-1.7.7.patch::version=1.7.7&hash=5402a7&locator=opencti-graphql%40workspace%3A.)
# Script code: node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@12.22.9 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack /home/opencti/Documents/opencti/node_modules/ssri/lib/index.js:16
gyp ERR! stack const getOptString = options => options?.length ? `?${options.join('?')}` : ''
gyp ERR! stack                                         ^
gyp ERR! stack 
gyp ERR! stack SyntaxError: Unexpected token '.'
gyp ERR! stack     at wrapSafe (internal/modules/cjs/loader.js:915:16)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:963:27)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:863:32)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:887:19)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:74:18)
gyp ERR! stack     at Object.<anonymous> (/home/opencti/Documents/opencti/node_modules/make-fetch-happen/lib/cache/policy.js:3:14)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:999:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
gyp ERR! System Linux 6.2.0-26-generic
gyp ERR! command "/usr/bin/node" "/home/opencti/Documents/opencti/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/opencti/Documents/opencti/node_modules/node-calls-python
gyp ERR! node -v v12.22.9
gyp ERR! node-gyp -v v9.4.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
```

Thanks for help

**Comment by nino-filigran** [comment]
@Damag3dRoot did you manage to get somme support on this?

**Comment by nino-filigran** [comment]
Closing this issue as I did not get response.
