### ISSUE TITLE
Network Traffic refs fail to be updated / upserted by integration

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#4476]
It seems that Network Traffic object not compliant with STIX2.

**Network Traffic object:** https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_rgnc3w40xy

**Error:**
```
Traceback (most recent call last): File "/opt/opencti-worker/worker.py", line 224, in data_handler self.api.stix2.import_bundle_from_json( File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json return self.import_bundle( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2361, in import_bundle self.import_observable(item, update, types) File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 1007, in import_observable self.opencti.stix_nested_ref_relationship.create( File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_nested_ref_relationship.py", line 261, in create result = self.opencti.query( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 358, in query raise ValueError( ValueError: {'name': 'UnsupportedError', 'message': 'Cant add another relation on single ref'}
```

**Object submitted by connector:**
```
{"type": "bundle", "id": "bundle--01bad548-253b-4e83-ad3d-d06fcded03b8", "spec_version": "2.1", "x_opencti_seq": 4, "objects": [{"type": "network-traffic", "spec_version": "2.1", "id": "network-traffic--10f24956-90b4-4402-9a0d-6ff7a654ab39", "dst_ref": "ipv4-addr--0000000-90b4-4401-0000-6ff7a6540000", "protocols": ["tcp"], "object_marking_refs": ["marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"], "nb_deps": 4}]}
```

## Environment

2. OpenCTI version: 5.10.3
3. OpenCTI client: 5.10.3

**Comment by AlexSanchezN** [comment]
Requested that back in January 
https://github.com/OpenCTI-Platform/opencti/issues/2695

It is supposed to be implemented in 5.11.0

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/38f69a94-0e42-4307-a9af-513a52661b7b)

Hope it makes it :-)

**Comment by Jipegien** [comment]
We won't make it for 5.11. 

We will define a solution and try to implement it in one of the next releases.

I close this one and keep 2695.

**Comment by richard-julien** [comment]
Reopen has it working fine at creation but not at upsert

**Comment by richard-julien** [comment]
Bundle for testing

[network.json](https://github.com/OpenCTI-Platform/opencti/files/13476807/network.json)
