### ISSUE TITLE
ERROR:pycti.api:Invalid field dst_port when creating a Network-Traffic object

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#4616]
## Description
I'm seeing the error below in the worker logs after upgrading to 5.11.X (currently in 5.11.1)
We've been creating Network-Traffic items for months with that field without issue.
I don't see those errors in yesterday's logs.

INFO:pycti.entities:Creating Stix-Cyber-Observable {Network-Traffic} with indicator at False.
---------------- other INFO messages that do not seem related -------------------
ERROR:pycti.api:Invalid field dst_port
ERROR:pycti.api:Traceback (most recent call last):
  File "/opt/opencti/./worker/worker.py", line 226, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.10/dist-packages/pycti/utils/opencti_stix2.py", line 214, in import_bundle_from_json
    return self.import_bundle(
  File "/usr/local/lib/python3.10/dist-packages/pycti/utils/opencti_stix2.py", line 2387, in import_bundle

  File "/usr/local/lib/python3.10/dist-packages/pycti/utils/opencti_stix2.py", line 942, in import_observable
    stix_observable_result = self.opencti.stix_cyber_observable.create(
  File "/usr/local/lib/python3.10/dist-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1184, in create
    result = self.opencti.query(query, input_variables)
  File "/usr/local/lib/python3.10/dist-packages/pycti/api/opencti_api_client.py", line 360, in query
    raise ValueError(
ValueError: {'name': 'ValidationError', 'message': 'Invalid field dst_port'}

## Environment

Ubuntu 22.04 bare metal (3 OpenCTI node)
5.11.1 version installed today

The field exists in the schema

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/3708fadd-7046-4fa7-8c01-2463185b05d4)

Thanks in advance for your excellent work

**Comment by AlexSanchezN** [comment]
That was fast! Thank you very much
