### ISSUE TITLE
Platform shutdown / crash on RabbitMQ exception (not catched)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4648]
## Description

Seen in Slack but also in our cloud environments.

The following exception:
```
Error: write ECONNRESET
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:952:11)
    at Socket._write (node:net:964:8)
    at writeOrBuffer (node:internal/streams/writable:447:12)
    at _write (node:internal/streams/writable:389:10)
    at Socket.Writable.write (node:internal/streams/writable:393:10)
    at roundrobin (/opt/opencti/build/node_modules/amqplib/lib/mux.js:59:25)
    at Wye._readIncoming (/opt/opencti/build/node_modules/amqplib/lib/mux.js:65:3)
    at Immediate._onImmediate (/opt/opencti/build/node_modules/amqplib/lib/mux.js:95:12)
    at processImmediate (node:internal/timers:478:21)
```

leads to crash completely the NodeJS process without proper catching.

New in 5.11.

**Comment by Hmarionx** [comment]
Exception is catched but problem still occur
