### ISSUE TITLE
Can not delete 'related-to' relationship from specific types (bis)

### ISSUE THREAD

**Issue by debelyoo** [LuatixHQ/opencti#4758]
## Description

Relationships of type 'related-to' from Text objects or Hostname objects can not be deleted.

Similar to #4156.

## Environment

1. OS (where OpenCTI server runs): Official OpenCTI docker image (base image: node:20-alpine)
2. OpenCTI version: 5.10.3
3. OpenCTI client: frontend and python

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select a relationship from a text object to a malware (or intrusion-set)
2. Delete it
3. An error message is shown ("Cannot read properties of null (reading 'multiple')")

## Expected Output

The relationship should be deleted.

## Actual Output

An error message is displayed. The relationship is not deleted.

## Additional information

It works for 'related-to' relationships from IP, domain, URL, file.
Stack trace:
```
 Traceback (most recent call last):
    |   File "/app/main.py", line 192, in process_sdos
    |     delete_relationships(idx, relationships_to_delete, sdo_id)
    |   File "/app/main.py", line 174, in delete_relationships
    |     opencti_api_client.stix_core_relationship.delete(id=relationship_id)
    |   File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_core_relationship.py", line 698, in delete
    |     self.opencti.query(query, {"id": id})
    |   File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 363, in query
    |     raise ValueError(
    | ValueError: {'name': "Cannot read properties of null (reading 'multiple')", 'message': "Cannot read properties of null (reading 'multiple')"}
```

**Comment by SamuelHassine** [comment]
Hello @debelyoo,

Can you please share the platform log when this happening? So we can find the line of middleware JS.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
We have modified a lot of things in the delete process in 5.11.X. The best would be to update to 5.11.10 and see if this still happens.

**Comment by ghost** [comment]
@debelyoo I've tested it with 5.11.10 according to your description. For me it is working.
Steps:
1. Create Observable of type text
2. Create a relation to a Malware
3. Delete the relation (Data / Relations)
Outcome: Relation is deleted without error

**Comment by debelyoo** [comment]
@iFrozenPhoenix the problem does not occur with newly created relationships. I observe it on old relationships that have been created in older versions of OpenCTI (my OpenCTI instance is 2 years old).
But I will upgrade to version 5.11.x and try again.

**Comment by debelyoo** [comment]
Hello again. I upgraded my OpenCTI instance to 5.12.4 and rerun my deletion script. I have the following error now:
```
Traceback (most recent call last):
	File "/app/main.py", line 111, in <module>
		main()
	File "/app/main.py", line 103, in main
		schedule.run_all()
	File "/usr/local/lib/python3.12/site-packages/schedule/__init__.py", line 829, in run_all
		default_scheduler.run_all(delay_seconds=delay_seconds)
	File "/usr/local/lib/python3.12/site-packages/schedule/__init__.py", line 118, in run_all
		self._run_job(job)
	File "/usr/local/lib/python3.12/site-packages/schedule/__init__.py", line 172, in _run_job
		ret = job.run()
			^^^^^^^^^
	File "/usr/local/lib/python3.12/site-packages/schedule/__init__.py", line 693, in run
		ret = self.job_func()
	File "/app/cleanup/cleaner.py", line 329, in clean_relationships
		self._opencti.stix_core_relationship.delete(id=relationship["id"])
	File "/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_core_relationship.py", line 698, in delete
		self.opencti.query(query, {"id": id})
	File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 368, in query
		raise ValueError(
			ValueError: {'name': 'UnsupportedError', 'message': 'SCHEMA_VALIDATION_ERROR'} 
```
This error occurs when I try to delete a 'related-to' relationship between a Text and an Intrusion-Set.

**Comment by alice-debra** [comment]
Hello @debelyoo,
We’re following up to see if you are still experiencing this issue. As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice

**Comment by debelyoo** [comment]
Hello, thanks for the follow-up. It's a long time I haven't checked this. You can close this ticket and I will reopen in case I experience it again.
