### ISSUE TITLE
OpenCTI unable to recognize merged Elasticsearch indices after reindexing and index name change

### ISSUE THREAD

**Issue by CreativeASAP** [LuatixHQ/opencti#4870]
I had a working OpenCTI instance, but there was an issue with the server that resulted in data corruption in the Elasticsearch database. As a result, I isolated the corrupted data and set up a new instance of OpenCTI with a fresh Elasticsearch database. The new instance started collecting data from scratch.

Later, I managed to fix the problem with the previous data and displayed it separately in OpenCTI, and everything was working fine. Then, I was asked to merge the data from both Elasticsearch databases into a single one. To do this, I took a snapshot of one Elasticsearch instance and restored it in the other Elasticsearch instance.

However, Elasticsearch does not allow two indices with the same name, so I changed the index names and performed reindexing for each index within the same category. For example:

```
POST _reindex?wait_for_completion=false
{
  "source": {
    "index": ["opencti_internal_objects-000001","new_opencti_internal_objects-000001"]
  },
  "dest": {
    "index": "tmp_opencti_internal_objects"
  }
}
```
This was done to merge the two indices into one. After that, I performed another reindexing operation:
```
POST _reindex?wait_for_completion=false
{
  "source": {
    "index": "tmp_opencti_internal_objects"
  },
  "dest": {
    "index": "opencti_internal_objects-000001"
  }
}
```
This was to change the index name so that OpenCTI could recognize and use it. However, after waiting for several days and starting OpenCTI, it was unable to recognize the existing indices and created new indices instead.

**Comment by CreativeASAP** [comment]
this is my indices
![Screenshot 2023-11-09 104346](https://github.com/OpenCTI-Platform/opencti/assets/144696457/d7324e85-aa0e-4ebe-92c5-8e04340770ba)

**Comment by CreativeASAP** [comment]
the opencti errors is
```
 {"category":"APP","error":{"context":{"category":"business","http_status":500,"reason":"Engine execution fail, some shards are not available, please check your engine status","shards":{"failed":1,"failures":[{"index":"opencti_stix_meta_relationships","node":"vtObfJx1SVKoMO0XvTPuYg","reason":{"caused_by":{"reason":"[nested] failed to find nested object under path [connections]","type":"illegal_state_exception"},"index":"opencti_stix_meta_relationships","index_uuid":"eJkfbU8tSma3PLnBAXP9pA","reason":"failed to create query: [nested] failed to find nested object under path [connections]","type":"query_shard_exception"},"shard":0}],"skipped":0,"successful":3,"total":4}},"message":"Engine shards failure","name":"LockError","stack":"LockError: Engine shards failure\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at EngineShardsError (/opt/opencti/build/src/config/errors.js:111:44)\n    at /opt/opencti/build/src/database/engine.js:242:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2814:35)\n    at createRelation (/opt/opencti/build/src/database/middleware.js:2914:16)\n    at addStixCoreRelationship (/opt/opencti/build/src/domain/stixCoreRelationship.js:250:19)"},"level":"error","message":"[SEARCH] Paginate fail","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"based-on"}},{"match_phrase":{"parent_types.keyword":"based-on"}}]}},{"nested":{"path":"connections","query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"connections.internal_id":"1ad1683b-54c0-4670-b9a1-a58b2de674da"}}]}},{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["connections.role"],"query":"*_from"}}]}}],"must_not":[]}}}},{"nested":{"path":"connections","query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"connections.internal_id":"d9bc564c-d431-4db3-b1b1-bbc66ea1c3da"}}]}},{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["connections.role"],"query":"*_to"}}]}}],"must_not":[]}}}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_relationships*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_meta_relationships*"],"track_total_hits":true},"timestamp":"2023-11-09T07:48:04.867Z","version":"5.11.12"}

```

**Comment by Jipegien** [comment]
@sbocahu, any advice to help on this?

**Comment by sbocahu** [comment]
Could you double check your configuration and cluster health status ?

The error clearly states a shard availability issue: "some shards are not available"
This error is thrown by OpenCTI if there were more than _elasticsearch:max_shards_failure_ (default: 0) shards erroring out when queried

**Comment by CreativeASAP** [comment]
I solved it by changing the setting of the cluster

```
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.node_concurrent_outgoing_recoveries": 15,
    "cluster.routing.allocation.node_concurrent_incoming_recoveries": 15
  }
}
```
