### ISSUE TITLE
Latest Version of OpenCTI installed through Docker - No Successful StartUp

### ISSUE THREAD

**Issue by MrTaherAmine** [LuatixHQ/opencti#4912]
## Description

I have installed the latest version of OpenCTI on top of Docker with Portainer on a virtualized Debian 12 OS. I can't seem to startup the OpenCTI platform this is the error code:

```
{"category":"APP", "error":{"context": {"category":"technical", "error": "getaddrinfo ENOTFOUND elasticsearch","http_status":
500, "reason":"[SEARCH] Search engine seems down"},"message": "A configuration error has
occurred", "name": "ConfigurationError", "stack"; "ConfigurationError: A configuration error has occurred in at error (/opt/opencti
src/config/errors.js:8:10)\n at ConfigurationError (/apt/opencti/build/src/config/errors.js:65:53)\n at /opt/opencti/build/
database/engine.js:178:15\n at processTicksAndRejections (node: internal/process/task_queues:95:5)\n at searchEngineVersion
at searchEngineInit (/opt/opencti/build/src/database/engine.js:213:27) in
checkSystem Dependencies (/opt/opencti/build/src/initialization.js:137:3)\n at platformStart [/opt/opencti/build/src/boot.js:
215:5)"},"level":"error", "message": "[OPENCTI] Platform start fail","timestamp":"2023-11-16T12:10:28.9062","version": "5.11.14")
```

## Environment

1. OS: Debian 12 / VM
2. OpenCTI version: Latest
3. OpenCTI client: Latest
4. Other environment details: Docker/Portainer

**Comment by ncatlin** [comment]
Is your minio container running? I just ran into this issue - the latest minio version seems to not work on older CPUs - changing to a supported build (https://github.com/minio/minio/issues/18365 ) made minio work and then everything else started ok.

**Comment by MrTaherAmine** [comment]
Hello @ncatlin , thanks for the information. Yes actually the MinIO container is not running and it always has exit codes, but my CPU is new in fact and here is the error code after analyzing the error log:

```
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html> Version: RELEASE. 2023-11-01T01-57-10Z (go1.21.3 linux/amd64)
Status:
1 Online,
Offline.
S3-API: http://10.0.2.68:9000 http://10.0.0.57:9000 http://172.18.0.17:9000 http://127.0.0.1:9000 Console: http://10.0.2.68:38609 http://10.0.0.57:38609 http://172.18.0.17:38609 http://127.0.0.1:38609

Documentation: https://min.io/docs/minio/linux/index.html

Warning: The standard parity is set to 0. This can lead to data loss.
You are running an older version of MinIO released 2 weeks before the latest release
Update: Run mc admin update`
Exiting on signal: TERMINATED
```

I believe the issue is related to ElasticSearch and not MinIO as I mentioned in my first comment:

```
{"category":"APP", "error":{"context": {"category":"technical", "error": "getaddrinfo ENOTFOUND elasticsearch","http_status":
500, "reason":"[SEARCH] Search engine seems down"},"message": "A configuration error has
occurred", "name": "ConfigurationError", "stack"; "ConfigurationError: A configuration error has occurred in at error (/opt/opencti
src/config/errors.js:8:10)\n at ConfigurationError (/apt/opencti/build/src/config/errors.js:65:53)\n at /opt/opencti/build/
database/engine.js:178:15\n at processTicksAndRejections (node: internal/process/task_queues:95:5)\n at searchEngineVersion
at searchEngineInit (/opt/opencti/build/src/database/engine.js:213:27) in
checkSystem Dependencies (/opt/opencti/build/src/initialization.js:137:3)\n at platformStart [/opt/opencti/build/src/boot.js:
215:5)"},"level":"error", "message": "[OPENCTI] Platform start fail","timestamp":"2023-11-16T12:10:28.9062","version": "5.11.14")
```

**Comment by Geordeaux** [comment]
I am also having this same issue. This bug is causing the opencti container to repeatedly crash. I have tested the connectivity between the docker containers. When I restart docker-opencti-1 I can ping docker-elasticsearch-1 for about 15 seconds before the docker-opencti-1 container crashes again and is then stuck in a 'restarting' state. The only error produced by this is the same error mentioned above by @MrTaherAmine. 

`{"category":"APP", "error":{"context": {"category":"technical", "error": "getaddrinfo ENOTFOUND elasticsearch","http_status":
500, "reason":"[SEARCH] Search engine seems down"},"message": "A configuration error has
occurred", "name": "ConfigurationError", "stack"; "ConfigurationError: A configuration error has occurred in at error (/opt/opencti
src/config/errors.js:8:10)\n at ConfigurationError (/apt/opencti/build/src/config/errors.js:65:53)\n at /opt/opencti/build/
database/engine.js:178:15\n at processTicksAndRejections (node: internal/process/task_queues:95:5)\n at searchEngineVersion
at searchEngineInit (/opt/opencti/build/src/database/engine.js:213:27) in
checkSystem Dependencies (/opt/opencti/build/src/initialization.js:137:3)\n at platformStart [/opt/opencti/build/src/boot.js:
215:5)"},"level":"error", "message": "[OPENCTI] Platform start fail","timestamp":"2023-11-16T12:10:28.9062","version": "5.11.14")`

However, this error is very misleading because 
1. The elasticsearch container is running fine without errors
2. The elasticsearch container is properly networked and is temporarily reachable by the opencti container

@MrTaherAmine Were you able to find a solution to this issue?

**Comment by alice-debra** [comment]
Hello @MrTaherAmine,
We’re following up to see if you still need an answer to this question. As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
