### ISSUE TITLE
Issue connecting to redis cluster - failed to refresh slots

### ISSUE THREAD

**Issue by Pez721** [LuatixHQ/opencti#4934]
## Description
I have deployed opencti in GCP kubernetes and I'm encountering an error when connecting to Redis:

{"category":"APP","level":"info","message":"[REDIS] 'base' Redis client reconnecting","timestamp":"2023-11-20T16:32:36.128Z","version":"5.9.6"}
{"category":"APP","error":{"context":{},"message":"Failed to refresh slots cache.","name":"ClusterAllFailedError","stack":"ClusterAllFailedError: Failed to refresh slots cache.\n    at tryNode (/opt/opencti/build/node_modules/ioredis/built/cluster/index.js:308:31)\n    at callback (/opt/opencti/build/node_modules/ioredis/built/cluster/index.js:325:21)\n    at /opt/opencti/build/node_modules/ioredis/built/cluster/index.js:662:24\n    at run (/opt/opencti/build/node_modules/ioredis/built/utils/index.js:117:22)\n    at tryCatcher (/opt/opencti/build/node_modules/standard-as-callback/built/utils.js:12:23)\n    at /opt/opencti/build/node_modules/standard-as-callback/built/index.js:33:50\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"level":"error","message":"[REDIS] Redis 'base' client error","timestamp":"2023-11-20T16:32:36.811Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'base' client closed","timestamp":"2023-11-20T16:32:36.812Z","version":"5.9.6"}

Opencti web continuously attempts to reconnect to redis and fails.

The redis cluster looks healthy:
[ansible@3091e4923a6f ~]$ kubectl get pods -n redis
NAME                              READY   STATUS    RESTARTS   AGE
redis-cluster-follower-0          1/1     Running   0          11d
redis-cluster-follower-1          1/1     Running   0          11d
redis-cluster-follower-2          1/1     Running   0          11d
redis-cluster-leader-0            1/1     Running   0          11d
redis-cluster-leader-1            1/1     Running   0          11d
redis-cluster-leader-2            1/1     Running   0          11d
redis-operator-7d75b4d686-94kp5   1/1     Running   0          11d

[ansible@3091e4923a6f ~]$ kubectl logs pod/redis-cluster-leader-0 -n redis
sed: /data/nodes.conf: No such file or directory
Running without TLS mode
Starting redis service in cluster mode.....
10:C 09 Nov 2023 16:15:39.071 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10:C 09 Nov 2023 16:15:39.071 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=10, just started
10:C 09 Nov 2023 16:15:39.071 # Configuration loaded
10:M 09 Nov 2023 16:15:39.072 * monotonic clock: POSIX clock_gettime
10:M 09 Nov 2023 16:15:39.073 * No cluster configuration found, I'm 538bd9a8f53dd4f4aba30c82939bea54c3cc8bde
10:M 09 Nov 2023 16:15:39.075 * Running mode=cluster, port=6379.
10:M 09 Nov 2023 16:15:39.075 # Server initialized
10:M 09 Nov 2023 16:15:39.077 * Creating AOF base file appendonly.aof.1.base.rdb on server start
10:M 09 Nov 2023 16:15:39.080 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
10:M 09 Nov 2023 16:15:39.080 * Ready to accept connections
10:M 09 Nov 2023 16:18:08.357 # configEpoch set to 1 via CLUSTER SET-CONFIG-EPOCH
10:M 09 Nov 2023 16:18:08.404 # IP address for this node updated to 10.60.132.24
10:M 09 Nov 2023 16:18:13.272 # Cluster state changed: ok
10:M 09 Nov 2023 16:18:50.924 * Replica 10.60.133.3:6379 asks for synchronization
10:M 09 Nov 2023 16:18:50.924 * Partial resynchronization not accepted: Replication ID mismatch (Replica asked for 'd8186c65e9e6e70542136d21de4a8cad939aed5e', my replication IDs are '139750583c448ac64c1732177c3c42f7e46f92b8' and '0000000000000000000000000000000000000000')
10:M 09 Nov 2023 16:18:50.924 * Replication backlog created, my new replication IDs are '3cdbb0394b8601d4fc2949125a10b12af38f0382' and '0000000000000000000000000000000000000000'
10:M 09 Nov 2023 16:18:50.924 * Delay next BGSAVE for diskless SYNC
10:M 09 Nov 2023 16:18:55.752 * Starting BGSAVE for SYNC with target: replicas sockets
10:M 09 Nov 2023 16:18:55.753 * Background RDB transfer started by pid 367
367:C 09 Nov 2023 16:18:55.753 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
10:M 09 Nov 2023 16:18:55.754 # Diskless rdb transfer, done reading from pipe, 1 replicas still up.
10:M 09 Nov 2023 16:18:55.758 * Background RDB transfer terminated with success
10:M 09 Nov 2023 16:18:55.758 * Streamed RDB transfer with replica 10.60.133.3:6379 succeeded (socket). Waiting for REPLCONF ACK from slave to enable streaming
10:M 09 Nov 2023 16:18:55.758 * Synchronization with replica 10.60.133.3:6379 succeeded

There is a service deployed for all leader nodes:
[ansible@3091e4923a6f ~]$ kubectl get services -n redis
NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
redis-cluster-follower              ClusterIP   10.60.130.111   <none>        6379/TCP   11d
redis-cluster-follower-additional   ClusterIP   10.60.130.204   <none>        6379/TCP   11d
redis-cluster-follower-headless     ClusterIP   None            <none>        6379/TCP   11d
redis-cluster-leader                ClusterIP   10.60.131.23    <none>        6379/TCP   11d
redis-cluster-leader-additional     ClusterIP   10.60.131.177   <none>        6379/TCP   11d
redis-cluster-leader-headless       ClusterIP   None            <none>        6379/TCP   11d

And this is what I have configured in the opencti-web deployment:
        - name: REDIS__MODE
          value: cluster
        - name: REDIS__HOSTNAMES
          value: '["redis-cluster-leader.redis"]'
        - name: REDIS__USE_SSL
          value: "false"
        - name: REDIS__PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-password
        - name: REDIS__TRIMMING
          value: "500000"

## Environment

1. OS (where OpenCTI server runs): Container-Optimized OS with containerd ( cos_containerd ) - deployed on Google Kubernetes Engine
2. OpenCTI version: 5.9.6
3. OpenCTI client: frontend?
6. Other environment details: Redis version 7.0.5 deployed via the Opstree operator in kubernetes in cluster mode.

Do you know the cause of this?

Many thanks

**Comment by nino-filigran** [comment]
Hey @Pez721 can you try to reach out on our community directly on Slack, using the channel OpenCTI? It seems that it's a bug which is related to your platform and we are not able to reproduce it. I'll change the tag of your request to question too.

**Comment by alice-debra** [comment]
Hello @Pez721,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
Kind regards,
Alice
