### ISSUE TITLE
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

### ISSUE THREAD

**Issue by atlatey** [LuatixHQ/opencti#5010]
## Description

Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Environment

1. OS Docker
2. OpenCTI version: 5.10.2
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Login to OpenCTI Dashboard
2. Click on 'Analyses', and then click on the 'PLUS' icon on the bottom right to add
3. Fill in any values and click 'CREATE'
4. Error

## Expected Output

Be able to create an analyses with my own values.

## Actual Output

An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Additional information

**Google Chrome Console error:**

TypeError: this.editor.disableReadOnlyMode is not a function
    at u4.shouldComponentUpdate (front-OZBZMED4.js:1226:73624)
    at j7a (front-OZBZMED4.js:6:10930)
    at Z7a (front-OZBZMED4.js:8:5184)
    at rfa (front-OZBZMED4.js:8:45658)
    at tfa (front-OZBZMED4.js:8:40412)
    at Bjl (front-OZBZMED4.js:8:40335)
    at Aln (front-OZBZMED4.js:8:40183)
    at drt (front-OZBZMED4.js:8:36453)
    at l3a (front-OZBZMED4.js:8:37272)
    at $ie (front-OZBZMED4.js:6:3359)
Yit @ front-OZBZMED4.js:8
o.componentDidCatch.a.callback @ front-OZBZMED4.js:8
B7a @ front-OZBZMED4.js:6
i3a @ front-OZBZMED4.js:8
Z4a @ front-OZBZMED4.js:8
Z4a @ front-OZBZMED4.js:8
Z4a @ front-OZBZMED4.js:8
zjl @ front-OZBZMED4.js:8
Wjl @ front-OZBZMED4.js:8
q0e @ front-OZBZMED4.js:8
l3a @ front-OZBZMED4.js:8
$ie @ front-OZBZMED4.js:6
X0e @ front-OZBZMED4.js:8
M3a @ front-OZBZMED4.js:5
sit @ front-OZBZMED4.js:5
_rt @ front-OZBZMED4.js:5
ABl @ front-OZBZMED4.js:5

**Safari Console Error**

[Error] TypeError: this.editor.disableReadOnlyMode is not a function. (In 'this.editor.disableReadOnlyMode(zf)', 'this.editor.disableReadOnlyMode' is undefined)
shouldComponentUpdate — front-OZBZMED4.js:1226:73644
Z7a — front-OZBZMED4.js:8:5188
tfa — front-OZBZMED4.js:8:40416
Bjl — front-OZBZMED4.js:8:40339
Aln — front-OZBZMED4.js:8:40187
drt — front-OZBZMED4.js:8:36457
l3a — front-OZBZMED4.js:8:37276
$ie — front-OZBZMED4.js:6:3361
X0e — front-OZBZMED4.js:8:37737
M3a — front-OZBZMED4.js:5:9185
sit — front-OZBZMED4.js:5:33902
_rt — front-OZBZMED4.js:5:17727
ABl — front-OZBZMED4.js:5:17501
	Yit (front-OZBZMED4.js:8:183)
	(anonymous function) (front-OZBZMED4.js:8:704)
	B7a (front-OZBZMED4.js:6:10082)
	i3a (front-OZBZMED4.js:8:32312)
	Z4a (front-OZBZMED4.js:8:31885)
	Z4a (front-OZBZMED4.js:8:31782)
	Z4a (front-OZBZMED4.js:8:31782)
	zjl (front-OZBZMED4.js:8:31413)
	Wjl (front-OZBZMED4.js:8:41572)
	q0e (front-OZBZMED4.js:8:40911)
	l3a (front-OZBZMED4.js:8:37428)
	$ie (front-OZBZMED4.js:6:3361)
	X0e (front-OZBZMED4.js:8:37737)
	M3a (front-OZBZMED4.js:5:9185)
	sit (front-OZBZMED4.js:5:33902)
	_rt (front-OZBZMED4.js:5:17727)
	ABl (front-OZBZMED4.js:5:17501)

**Comment by nino-filigran** [comment]
@atlatey can you please try to upgrade to our latest version and see if the problem persists please?

**Comment by nino-filigran** [comment]
Additionnaly, could you please share server side logs ?

**Comment by nino-filigran** [comment]
Closing this ticket since no activity for a while. Please re-open this ticket if you need it.
