### ISSUE TITLE
in dashboard > data > connectors : screen does not load (an unknown error occurred)

### ISSUE THREAD

**Issue by atlatey** [LuatixHQ/opencti#5123]
## Description

Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Environment

1. OS Docker
2. OpenCTI version 5.12.2
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Login to OpenCTI Dashboard
2. Click on 'Data' tab
3. Click on 'Connectors' pane
4. Error

## Expected Output

Load up the /dashboard/data/connectors page
## Actual Output

An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Additional information

**Console Logs**
Failed to load resource: the server responded with a status of 504 (Gateway Timeout

Error
    at Object.render (front-3O2MFGM5.js:8460:46772)
    at a.render (front-3O2MFGM5.js:40:46528)
    at Cot (front-3O2MFGM5.js:8:6275)
    at Yka (front-3O2MFGM5.js:8:6067)
    at iSa (front-3O2MFGM5.js:8:45661)
    at nSa (front-3O2MFGM5.js:8:40415)
    at Dfs (front-3O2MFGM5.js:8:40338)
    at Mon (front-3O2MFGM5.js:8:40185)
    at Eot (front-3O2MFGM5.js:8:36454)
    at Zxa (front-3O2MFGM5.js:8:35374)
    
**Network Logs**
Request URL:
http://0.0.0.0:8080/graphql
Request Method:
POST
Status Code:
504 Gateway Timeout
Remote Address:
0.0.0.0:8080
Referrer Policy:
unsafe-url

**Server Logs**

Error 1:

{
  "category": "APP",
  "error": {
    "stacktrace": [
      "Error: connect ECONNREFUSED CHANGEDFORPRIVACY",
      "at Function.$ne.from (/opt/opencti/build/node_modules/axios/lib/core/AxiosError.js:89:14)",
      "at oA.handleRequestError (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:593:25)",
      "at oA.emit (node:events:514:28)",
      "at ClientRequest.kKt.<computed> (/opt/opencti/build/node_modules/follow-redirects/index.js:14:24)",
      "at ClientRequest.emit (node:events:514:28)",
      "at Socket.socketErrorListener (node:_http_client:495:9)",
      "at Socket.emit (node:events:514:28)",
      "at emitErrorNT (node:internal/streams/destroy:151:8)",
      "at emitErrorCloseNT (node:internal/streams/destroy:116:3)",
      "at processTicksAndRejections (node:internal/process/task_queues:82:21)"
    ]
  },
  "inner_relation_creation": 0,
  "level": "error",
  "message": "API Call",
  "operation": "ConnectorsStatusQuery",
  "operation_query": "query ConnectorsStatusQuery{...ConnectorsStatus_data}fragment ConnectorsStatus_data on Query{connectors{id name active auto connector_type connector_scope updated_at config{listen listen_exchange push push_exchange}built_in}rabbitMQMetrics{queues{name messages messages_ready messages_unacknowledged consumers idle_since message_stats{ack ack_details{rate}}}}}",
  "size": 2,
  "time": 45269,
  "timestamp": "2023-12-04T23:01:24.759Z",
  "type": "READ_ERROR",
  "user": {
    "group_ids": [
      "CHANGEDFORPRIVACY"
    ],
    "ip": "::ffff:CHANGEDFORPRIVACY",
    "organization_ids": [],
    "referer": "http://0.0.0.0:8080/dashboard/data/connectors",
    "socket": "query",
    "user_id": "CHANGEDFORPRIVACY"
  },
  "variables": {},
  "version": "5.12.2"
}

Error 2:

{
  "category": "APP",
  "error": {
    "stacktrace": [
      "Error: connect ECONNREFUSED CHANGEDFORPRIVACY",
      "at Function.$ne.from (/opt/opencti/build/node_modules/axios/lib/core/AxiosError.js:89:14)",
      "at oA.handleRequestError (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:593:25)",
      "at oA.emit (node:events:514:28)",
      "at ClientRequest.kKt.<computed> (/opt/opencti/build/node_modules/follow-redirects/index.js:14:24)",
      "at ClientRequest.emit (node:events:514:28)",
      "at Socket.socketErrorListener (node:_http_client:495:9)",
      "at Socket.emit (node:events:514:28)",
      "at emitErrorNT (node:internal/streams/destroy:151:8)",
      "at emitErrorCloseNT (node:internal/streams/destroy:116:3)",
      "at processTicksAndRejections (node:internal/process/task_queues:82:21)"
    ]
  },
  "inner_relation_creation": 0,
  "level": "error",
  "message": "API Call",
  "operation": "WorkersStatusQuery",
  "operation_query": "query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}",
  "size": 2,
  "time": 45281,
  "timestamp": "2023-12-04T23:01:24.761Z",
  "type": "READ_ERROR",
  "user": {
    "group_ids": [
      "CHANGEDFORPRIVACY"
    ],
    "ip": "::ffff:CHANGEDFORPRIVACY",
    "organization_ids": [],
    "referer": "http://0.0.0.0:8080/dashboard/data/connectors",
    "socket": "query",
    "user_id": "CHANGEDFORPRIVACY"
  },
  "variables": {},
  "version": "5.12.2"
}

**Comment by SamuelHassine** [comment]
Hello,

It seems your RabbitMQ is not exposing the management interface (or not working properly).

Kind regards,
Samuel

**Comment by alice-debra** [comment]
Hello @atlatey,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
Kind regards,
Alice
