### ISSUE TITLE
Docker Containers Failing to start upon initial install

### ISSUE THREAD

**Issue by rxerium** [LuatixHQ/opencti#5159]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Hi there,

I am attempting to setup OpenCTI through Docker however the platform does not seem to start as I see a lot of services restarting. 
![image](https://github.com/OpenCTI-Platform/opencti/assets/59293085/7235418e-da58-4d23-a665-6b639588af09)

## Environment

1. OS (where OpenCTI server runs): Ubuntu22.04 / 16GB RAM / 400GB SSD / 6vCPU cores
2. OpenCTI version: Latest docker image
3. OpenCTI client: n/a
4. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Simply by following the documentation then running `docker-compose up -d`

## Additional information

The logs for each of the restarting containers results in the following, the below are logs from `docker_worker_3`
```
{"timestamp": "2023-12-08T19:35:35.002122Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:35:35.012417Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c853e7d70>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:35:37.670220Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:35:37.683227Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88e0fceb10>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:35:40.968532Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:35:40.983080Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9961b0fcb0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:35:44.523487Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:35:44.533423Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc272df7b90>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:35:49.648874Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:35:50.679237Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65a66d7fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:35:53.943909Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:35:53.950199Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbbd61caea0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:35:59.176661Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:35:59.183695Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334b0f1190>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:36:07.344051Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:36:07.350181Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe6de2e7ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:36:22.122637Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:36:23.169171Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23d8416ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:36:50.266260Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:36:50.270709Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eb9552b10>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:37:42.693194Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:37:47.702110Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7ff89182c200>: Failed to resolve 'opencti' ([Errno -3] Try again)\"))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:38:48.889584Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:38:53.899240Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f212f6840e0>: Failed to resolve 'opencti' ([Errno -3] Try again)\"))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:39:55.218404Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:40:00.237823Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f3e6c333dd0>: Failed to resolve 'opencti' ([Errno -3] Try again)\"))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:41:01.547706Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:41:06.557867Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f6b333bba70>: Failed to resolve 'opencti' ([Errno -3] Try again)\"))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:42:07.785625Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:42:12.794331Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f3d24fc2870>: Failed to resolve 'opencti' ([Errno -3] Try again)\"))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:43:14.056797Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:43:19.074840Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7fed0c2f87a0>: Failed to resolve 'opencti' ([Errno -3] Try again)\"))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
{"timestamp": "2023-12-08T19:44:20.805566Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null.", "taskName": null}
{"timestamp": "2023-12-08T19:44:25.815711Z", "level": "ERROR", "name": "pycti.api", "message": "HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f46ab853c50>: Failed to resolve 'opencti' ([Errno -3] Try again)\"))", "taskName": null}
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 563, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 476, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
```

**Comment by rxerium** [comment]
My config is
```
OPENCTI_ADMIN_EMAIL=admin@opencti.io
OPENCTI_ADMIN_PASSWORD=........
OPENCTI_ADMIN_TOKEN=$(cat /proc/sys/kernel/random/uuid)
MINIO_ROOT_USER=$(cat /proc/sys/kernel/random/uuid)
MINIO_ROOT_PASSWORD=$(cat /proc/sys/kernel/random/uuid)
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=..........
ELASTIC_MEMORY_SIZE=4G
CONNECTOR_HISTORY_ID=$(cat /proc/sys/kernel/random/uuid)
CONNECTOR_EXPORT_FILE_STIX_ID=$(cat /proc/sys/kernel/random/uuid)
CONNECTOR_EXPORT_FILE_CSV_ID=$(cat /proc/sys/kernel/random/uuid)
CONNECTOR_IMPORT_FILE_STIX_ID=$(cat /proc/sys/kernel/random/uuid)
CONNECTOR_IMPORT_REPORT_ID=$(cat /proc/sys/kernel/random/uuid)
```

**Comment by richard-julien** [comment]
Can you check the logs of the platform? thanks

**Comment by menmvlad** [comment]
> Can you check the logs of the platform? thanks

I got the same issue. How do you check logs of the platform exactly? I've did an install with docker and 4/10 containers are working, everything else is restarting after 3-5 seconds.

**Comment by richard-julien** [comment]
Should be something like this

`docker logs [ID container]`

**Comment by menmvlad** [comment]
Hello, I've had hard time to install it, but finally I did it. I did the manual installation on debian based OS and not the docker one. 

I've had everything working untill the command yarn serv. Then I've did the following steps so I can get the opencti live.

The error I've recieved and realized nothing from the prerequisites was installed was this error:

_"APP","error":{"context":{"category":"technical","error":"socket hang up","http_status":500,"reason":"[SEARCH] Search engine seems down"_

For the manual installation you need to install elasticsearch manually:

```
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.3-amd64.deb
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.3-amd64.deb.sha512
shasum -a 512 -c elasticsearch-8.11.3-amd64.deb.sha512 
sudo dpkg -i elasticsearch-8.11.3-amd64.deb
```
After successfully installing change the SSL of elastic like the following, just change the true ones with false(probably the elasticsearch config will be located at - **/etc/elasticsearch/elasticsearch.yml**):



# Enable security features
```
xpack.security.enabled: false

xpack.security.enrollment.enabled: false

# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: false
  keystore.path: certs/http.p12

# Enable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: false
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12
```


After changing the config of elastic you need to start/restart it - `sudo systemctl start elasticsearch.service`

Install minio, easiest way for me was to install go, then run - `go install github.com/minio/minio@latest`

After successfully installing minio, now we need to start it with the command -` /go/bin/minio server start` 

After that we need to install rabbitmq from here - [https://www.rabbitmq.com/install-debian.html#manual-installation](https://www.rabbitmq.com/install-debian.html#manual-installation).

After successfully installing rabbitmq you must run in separate window the command - `redis-server `


You also need to apply changes to the `/opencti/config/production.json`. Change everything that says **changeme**, plus the email:

```
"admin": {
      "email": "email@domain.com",
      "password": "somepassyoulike",
      "token": "349c9g38-12b3-4d28-844f-d1ba442ac25s" (here you must have a valid UUIDv4)
```

and also change it here 

```
in the minio object:
    "access_key": "minioadmin",
    "secret_key": "minioadmin",

```

Hope that helps :)

Please fix the instructions and the installation with docker.

**Comment by nino-filigran** [comment]
@rxerium I assume this is fixed given your reaction to the above comment?

**Comment by rxerium** [comment]
Apologies for the delayed reply. Yes it is!! Thanks so much!
