### ISSUE TITLE
No user information in user tab

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#5175]
## Description

There is no information in the user tab after selecting a user

## Environment

1. OS (where OpenCTI server runs): Mac OS 14
2. OpenCTI version: 5.12.4
3. OpenCTI client: Firefox
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on Settings tab
2. Click on Security tab
3. Click on a user

## Actual Output

After selecting a user

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/5cfe9537-7485-4ea2-b95a-3ebb2cdc25ba)

## Additional information

Logs of OpenCTI

{
    "category":"APP",
    "error":{
        "data":{
            "category":"technical",
            "error":{
                "meta":{
                    "body":{
                        "error":{
                            "failed_shards":[{
                                "index":"octi_inferred_relationships-000001",
                                "node":"A7RSASQCSriqrxD40Fo30A",
                                "reason":{
                                    "index":"octi_inferred_relationships-000001",
                                    "index_uuid":"XruJWjVLTfuZYwDOrqErBw",
                                    "reason":"No mapping found for [name.keyword] in order to sort on",
                                    "type":"query_shard_exception"
                                    },
                                "shard":0
                            },
                            {
                                "index":"octi_internal_relationships-000001",
                                "node":"A7RSASQCSriqrxD40Fo30A",
                                "reason":{
                                    "index":"octi_internal_relationships-000001",
                                    "index_uuid":"i87HZaCDRDaNMXfkVbWBtw",
                                    "reason":"No mapping found for [name.keyword] in order to sort on",
                                    "type":"query_shard_exception"},
                                "shard":0
                            }],
                            "grouped":true,
                            "phase":"query",
                            "reason":"Partial shards failure",
                            "root_cause":[{
                                "index":"octi_inferred_relationships-000001",
                                "index_uuid":"XruJWjVLTfuZYwDOrqErBw",
                                "reason":"No mapping found for [name.keyword] in order to sort on",
                                "type":"query_shard_exception"
                                },
                                {
                                "index":"octi_internal_relationships-000001",
                                    "index_uuid":"i87HZaCDRDaNMXfkVbWBtw",
                                    "reason":"No mapping found for [name.keyword] in order to sort on",
                                    "type":"query_shard_exception"
                                }],
                            "type":"search_phase_execution_exception"
                        },
                        "status":400
                    },
                    "headers":{
                        "content-length":"1092",
                        "content-type":"application/vnd.elasticsearch+json;compatible-with=8",
                        "warning":"299 Elasticsearch-8.11.1-6f9ff581fbcde658e6f69d6ce03050f060d1fd0c \"[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices.\"",
                        "x-elastic-product":"Elasticsearch"
                    },
                    "meta":{
                        "aborted":false,
                        "attempts":0,
                        "connection":{
                            "headers":{},
                            "id":"http://127.0.0.1:9200/",
                            "status":"alive",
                            "url":"http://127.0.0.1:9200/"},
                            "context":null,
                            "name":"elasticsearch-js",
                            "request":{
                                "id":6882,
                                "options":{},
                                "params":{
                                    "body":"{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"terms\":{\"internal_id.keyword\":[\"bd886d17-e893-4d52-90ee-2a8b82d7582d\",\"388c4cb5-df35-43fd-8625-6edcc1b176c2\"]}},{\"terms\":{\"standard_id.keyword\":[\"bd886d17-e893-4d52-90ee-2a8b82d7582d\",\"388c4cb5-df35-43fd-8625-6edcc1b176c2\"]}},{\"terms\":{\"x_opencti_stix_ids.keyword\":[\"bd886d17-e893-4d52-90ee-2a8b82d7582d\",\"388c4cb5-df35-43fd-8625-6edcc1b176c2\"]}}],\"minimum_should_match\":1}}],\"must_not\":[]}},\"sort\":[{\"name.keyword\":\"asc\"}],\"size\":5000,\"_source\":true}",
                                    "headers":{
                                        "accept":"application/vnd.elasticsearch+json; compatible-with=8",
                                        "content-length":"498",
                                        "content-type":"application/vnd.elasticsearch+json; compatible-with=8",
                                        "user-agent":"elasticsearch-js/8.10.0 (darwin 23.1.0-arm64; Node.js 20.10.0; Transport 8.3.4)",
                                        "x-elastic-client-meta":"es=8.10.0,js=20.10.0,t=8.3.4,hc=20.10.0"
                                    },
                                    "method":"POST",
                                    "path":"/octi_internal_objects*%2Cocti_internal_relationships*%2Cocti_stix_meta_objects*%2Cocti_stix_meta_relationships*%2Cocti_stix_cyber_observable_relationships*%2Cocti_stix_domain_objects*%2Cocti_stix_core_relationships*%2Cocti_stix_sighting_relationships*%2Cocti_stix_cyber_observables*%2Cocti_inferred_entities*%2Cocti_inferred_relationships*/_search",
                                    "querystring":"ignore_throttled=false"
                                }
                            }
                        },
                        "statusCode":400,
                        "warnings":[
                            "299 Elasticsearch-8.11.1-6f9ff581fbcde658e6f69d6ce03050f060d1fd0c \"[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices.\""]
                    },
                    "name":"ResponseError"
                },
                "http_status":500,
                "query":{
                        "_source":true,
                        "body":{
                            "query":{
                                "bool":{
                                    "must":[{
                                        "bool":{
                                            "minimum_should_match":1,
                                            "should":[{
                                                "terms":{
                                                    "internal_id.keyword":["bd886d17-e893-4d52-90ee-2a8b82d7582d","388c4cb5-df35-43fd-8625-6edcc1b176c2"]
                                                }
                                            },
                                            {
                                                "terms":{"standard_id.keyword":["bd886d17-e893-4d52-90ee-2a8b82d7582d","388c4cb5-df35-43fd-8625-6edcc1b176c2"]
                                                }
                                            },
                                            {
                                                "terms":{
                                                    "x_opencti_stix_ids.keyword":["bd886d17-e893-4d52-90ee-2a8b82d7582d","388c4cb5-df35-43fd-8625-6edcc1b176c2"]
                                                }
                                            }]
                                        }
                                    }],
                                    "must_not":[]
                                }
                            },
                            "sort":[{"name.keyword":"asc"}]
                        },
                        "ignore_throttled":false,
                        "index":["octi_internal_objects*","octi_internal_relationships*","octi_stix_meta_objects*","octi_stix_meta_relationships*","octi_stix_cyber_observable_relationships*","octi_stix_domain_objects*","octi_stix_core_relationships*","octi_stix_sighting_relationships*","octi_stix_cyber_observables*","octi_inferred_entities*","octi_inferred_relationships*"],
                        "size":5000
                    },
                    "reason":"[SEARCH] Error loading ids"
                },
                "stacktrace":["DatabaseError: A database error has occurred","at error (/Users/jerome/Applications/OpenCTI/opencti/build/src/config/errors.js:8:10)","at DatabaseError (/Users/jerome/Applications/OpenCTI/opencti/build/src/config/errors.js:58:48)","at /Users/jerome/Applications/OpenCTI/opencti/build/src/database/engine.js:1316:15","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at elFindByIds (/Users/jerome/Applications/OpenCTI/opencti/build/src/database/engine.js:1315:20)","at batchListThrough (/Users/jerome/Applications/OpenCTI/opencti/build/src/database/middleware.js:321:19)"]
            },
            "inner_relation_creation":0,
            "level":"error",
            "message":"API Call",
            "operation":"RootUserQuery",
            "operation_query":"query RootUserQuery($id:String!$rolesOrderBy:RolesOrdering$rolesOrderMode:OrderingMode$groupsOrderBy:GroupsOrdering$groupsOrderMode:OrderingMode$organizationsOrderBy:OrganizationsOrdering$organizationsOrderMode:OrderingMode){user(id:$id){id name ...User_user_1a0yag ...UserAnalytics_user}}fragment UserAnalytics_user on User{id name description}fragment User_user_1a0yag on User{id name description external user_email firstname lastname account_status account_lock_after_date language api_token otp_activated roles(orderBy:$rolesOrderBy orderMode:$rolesOrderMode){id name description}capabilities{id name}groups(orderBy:$groupsOrderBy orderMode:$groupsOrderMode){edges{node{id name description}}}default_hidden_types objectOrganization(orderBy:$organizationsOrderBy orderMode:$organizationsOrderMode){edges{node{id name authorized_authorities}}}sessions{id created ttl}}",
            "size":198,
            "time":84,
            "timestamp":"2023-12-11T14:59:35.583Z",
            "type":"READ_ERROR",
            "user":{"group_ids":["c7b2cffc-da4f-4b9c-9cb9-8b384eaaa3a8","bd886d17-e893-4d52-90ee-2a8b82d7582d","81141f09-ef71-4dfc-a947-2520042ef7e8"],
                "ip":"::ffff:127.0.0.1",
                "organization_ids":["ca715962-7a8b-4a78-901c-9453133ab0f7"],
                "referer":"http://127.0.0.1:4000/dashboard/settings/accesses/users/e7873e79-1ea3-4d9e-b917-c6f89b5ad73b",
                "socket":"query",
                "user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"
            },
            "variables":{
                "groupsOrderBy":"name",
                "groupsOrderMode":"asc",
                "id":"e7873e79-1ea3-4d9e-b917-c6f89b5ad73b",
                "organizationsOrderBy":"name",
                "organizationsOrderMode":"asc",
                "rolesOrderBy":"name",
                "rolesOrderMode":"asc"
            }
        }
    },  
    "version":"5.12.4"
}

## Screenshots (optional)

User selection

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/636bb8b2-b5a1-4baf-b9f9-0af66740d58f)

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/ad7ab1b7-0777-4cfe-b1ba-aae4cde3520b)

Logs of Firefox Web Dev tool

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/65730ec3-e8fb-483b-993e-0a4d97317c99)

**Comment by SamuelHassine** [comment]
Hello,

Did you do a migration for rollover policies and do you have a proper index template applying on octi_internal_relationships with the mapping?

It seems your index template was not applied at index creation.

Kind regards,
Samuel

**Comment by JeromeSRT** [comment]
> Hello,
> 
> 
> 
> Did you do a migration for rollover policies and do you have a proper index template applying on octi_internal_relationships with the mapping?
> 
> 
> 
> It seems your index template was not applied at index creation.
> 
> 
> 
> Kind regards,
> 
> Samuel

Hello,

Yes, I did a migration for the rollover policies.

I have no references for the index template to apply on octi_internal_relationships with mapping to check.

May be there is a howto to force the application of the template ?

For information, I have the same trouble if I start an "empty" platform without data.

Kind regards,

Jerome

**Comment by JeromeSRT** [comment]
> > Hello,
> > 
> > 
> > 
> > Did you do a migration for rollover policies and do you have a proper index template applying on octi_internal_relationships with the mapping?
> > 
> > 
> > 
> > It seems your index template was not applied at index creation.
> > 
> > 
> > 
> > Kind regards,
> > 
> > Samuel
> 
> Hello,
> 
> Yes, I did a migration for the rollover policies.
> 
> I have no references for the index template to apply on octi_internal_relationships with mapping to check.
> 
> May be there is a howto to force the application of the template ?
> 
> For information, I have the same trouble if I start an "empty" platform without data.
> 
> Kind regards,
> 
> Jerome

Hello Filigram team,

The last version 5.12.7 solved the problem described above, but others appeared concerning the drop-down list in the report tab and others.

King regards,

Jerome

**Comment by SamuelHassine** [comment]
Hello Jerome,

All known bugs have been fixed in 5.12.12. 

Kind regards,
Samuel
