### ISSUE TITLE
Cannot import CSV file

### ISSUE THREAD

**Issue by C0nnexor** [LuatixHQ/opencti#5221]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I cannot import a simple CSV file in which for every row a domain name is reported. In "Data Import" I see only "Import File Stix" enabled.
In the admin platform, portainer.io (v2.11.1), I see the following error message in the logs regarding the container "import document".

```
{"timestamp": "2023-12-14T14:17:46.884762Z", "level": "ERROR", "name": "pycti.api", "message": "Variable \"$input\" got invalid value null at \"input.id\"; Expected non-nullable type \"ID!\" not to be null."}
Traceback (most recent call last):
  File "/opt/opencti-connector-import-document/main.py", line 7, in <module>
    connector = ReportImporter()
                ^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-import-document/reportimporter/core.py", line 39, in __init__
    self.helper = OpenCTIConnectorHelper(config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 689, in __init__
    connector_configuration = self.api.connector.register(self.connector)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_connector.py", line 103, in register
    result = self.api.query(query, connector.to_input())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 365, in query
    raise ValueError(
ValueError: {'name': 'Variable "$input" got invalid value null at "input.id"; Expected non-nullable type "ID!" not to be null.', 'message': 'Variable "$input" got invalid value null at "input.id"; Expected non-nullable type "ID!" not to be null.'}
Terminated
```

## Environment

1. OS (where OpenCTI server runs): Docker - portainer.io 2.11.1
2. OpenCTI version: 5.11.8
3. OpenCTI client: Python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click data import
2. Select CSV file to import
3. Nothing runs
4. Import Document container prints errors

**Comment by nino-filigran** [comment]
@C0nnexor could you please ask your question on our Slack channel to get more support?

**Comment by alice-debra** [comment]
Hello @C0nnexor,
Due to a lack of recent activity on this issue, we will proceed to close it for now. We hope you found help on Slack. We sincerely thank you for your feedback, and please don’t hesitate to reopen the issue if the problem persists.
Kind regards,
Alice
