### ISSUE TITLE
 Error when export

### ISSUE THREAD

**Issue by Ozer0x777** [LuatixHQ/opencti#5374]
**Description**

This error occurs every time i try to export iocs:

Environment**

OpenCTI 5.12.14
Ubuntu 22.04

**Reproducible Steps**
    Go to data
    Try exporting

**Additional information**
```

ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | timestamp=2023-12-28T08:33:30.320537Z ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | timestamp=2023-12-28T08:33:30.320537Z name=pycti.connector ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | timestamp=2023-12-28T08:33:30.320537Z ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | timestamp=2023-12-28T08:33:30.320537Z name=pycti.connector exc_info=Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1386, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1386, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 279, in _data_handler
    message = self.callback(json_data["event"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-export-file-stix/export-file-stix.py", line 98, in _process_message
    bundle = self.helper.api_impersonate.stix2.export_list(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2250, in export_list
    entities_list = do_list(
                    ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_domain_object.py", line 1121, in list
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 349, in query
    r = self.session.post(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Screenshots**
![image](https://github.com/OpenCTI-Platform/opencti/assets/128625306/45a5faa9-4f68-44c2-9466-9fdef83019f8)

**Comment by nino-filigran** [comment]
Hi @Ozer0x777 I cannot reproduce your bug. 
Can you first try to upgrade your version to the latest please? 
Also can you be more specific around the type of export you're attempting? 

Could you potentially also raise this in slack, to get additionnal supports from both our devs and the community?

**Comment by Ozer0x777** [comment]
The issue happens when i try to export entities/ or any "data"
Data >Entities> Open export panel > then i ask for json and all "data"

Even with the last update i got the same issue 

![image](https://github.com/OpenCTI-Platform/opencti/assets/128625306/f3e1e42f-a7f5-4d3e-b4c6-7447cb08670f)


![image](https://github.com/OpenCTI-Platform/opencti/assets/128625306/c2039cef-6188-4533-a7fc-3cc8238a6461)

**Comment by nino-filigran** [comment]
Thanks for your response. 
I'm not a dev myself, I can try to get answer for you, but in the meantime, could you also try to raise your issue on slack, where both the community and our devs are more active?

**Comment by nino-filigran** [comment]
Hi did you manage to get any support?

**Comment by nino-filigran** [comment]
Clsoing this issue given I did not receive any response .feel free to re-open it if you still have the issue.
