### ISSUE TITLE
Docs - Neither Docker nor manual Install Work ( SOLVED ) 

### ISSUE THREAD

**Issue by decyphertek-io** [LuatixHQ/opencti#5452]
Request:
-------------

Can you test out the docs yourself and see they just dont work. Can you provide more detailed docs ? I am using Ubuntu 22.04 LTS for the manual install and Flatcar Linux LTS for the Docker install. 

OpenCTI Manual install Fails:
---------------------------------------

      # https://docs.opencti.io/latest/deployment/installation/
      sudo apt update && sudo apt install build-essential nodejs npm python3 python3-pip python3-dev -y
      wget https://github.com/OpenCTI-Platform/opencti/releases/download/5.12.15/opencti-release-5.12.15.tar.gz
      tar -xvf opencti-release-5.12.15.tar.gz
      cd opencti && cp config/default.json config/production.json
      vim config/production.json
      # Change admin token ( run from terminal - uuidgen ) & change passwords/ usernames
      vim ~/.bashrc
      export PATH=$PATH:/home/ubuntu/.local/bin
      source ~/.bashrc
      cd src/python && pip3 install -r requirements.txt 
      cd ../..
      sudo npm install -g yarn
      yarn install && yarn build && yarn serv
      python3 worker.py &
      You can now go to http://localhost:4000 and log in with the credentials configured in your production.json file.

      # ERROR
      ubuntu@ip-172-31-41-191:~/opencti$ yarn install && yarn build && yarn serv
      ➤ YN0000: ┌ Resolution step
      ➤ YN0060: │ opencti-graphql@workspace:. provides graphql (pebcd9) with version 16.8.1, which doesn't satisfy what graphql-
          import and some of its descendants request
      ➤ YN0060: │ opencti-graphql@workspace:. provides graphql (p2c3b2) with version 16.8.1, which doesn't satisfy what merge-
          graphql-schemas and some of its descendants request
      ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> 
         is the six-letter p-prefixed code
      ➤ YN0000: └ Completed in 0s 667ms
      ➤ YN0000: ┌ Fetch step
      ➤ YN0000: └ Completed in 1s 84ms
      ➤ YN0000: ┌ Link step
      ➤ YN0007: │ node-calls-python@patch:node-calls-python@npm%3A1.7.7#./patch/node-calls-python-1.7.7.patch::version=1.7.7&
           hash=5402a7&locator=opencti-graphql%40workspace%3A. must be built because it never has been before or the last one failed
      ➤ YN0009: │ node-calls-python@patch:node-calls-python@npm%3A1.7.7#./patch/node-calls-python-1.7.7.patch::version=1.7.7&
          hash=5402a7&locator=opencti-graphql%40workspace%3A. couldn't be built successfully (exit code 1, logs can be found here: 
          /tmp/xfs-009026ba/build.log)
      ➤ YN0000: └ Completed in 1s 767ms
      ➤ YN0000: Failed with errors in 3s 927ms

OpenCTI Docker Install Fails.
-------------------------------------

It is listening on port 8080 for a few minutes , the webpage is never accessible, then the docker container stops listening on port 8080?

      # https://docs.opencti.io/latest/deployment/installation/
      $ git clone https://github.com/OpenCTI-Platform/docker.git && cd docker
      $ sudo sysctl -w vm.max_map_count=1048575
      $ mv .env.sample .env
      # Change the admin email,  admin password, generate a UUID token. Change minio & rabbitmq user / pass . 
      $ uuidgen
      $ vim .env
      $ docker-compose up -d

**Comment by decyphertek-io** [comment]
Looking at the docker logs , I found that I didnt have enough memory for Elasticsearch, it failed, so Opencti fails. 

    # There is insufficient memory for the Java Runtime Environment to continue.
    # Native memory allocation (mmap) failed to map 4294967296 bytes for committing reserved memory.
    # An error report file with more information is saved as:
    # logs/hs_err_pid28.log
    error:
    OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000700000000, 4294967296, 0) failed; error='Not 
    enough space' (errno=12)
	    at org.elasticsearch.server.cli.JvmOption.flagsFinal(JvmOption.java:120)
	    at org.elasticsearch.server.cli.JvmOption.findFinalOptions(JvmOption.java:87)
	    at org.elasticsearch.server.cli.MachineDependentHeap.determineHeapSettings(MachineDependentHeap.java:59)
	    at org.elasticsearch.server.cli.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:138)
	    at org.elasticsearch.server.cli.JvmOptionsParser.determineJvmOptions(JvmOptionsParser.java:91)
	    at org.elasticsearch.server.cli.ServerProcess.createProcess(ServerProcess.java:208)
	    at org.elasticsearch.server.cli.ServerProcess.start(ServerProcess.java:104)
	    at org.elasticsearch.server.cli.ServerProcess.start(ServerProcess.java:88)
	    at org.elasticsearch.server.cli.ServerCli.startServer(ServerCli.java:239)
	    at org.elasticsearch.server.cli.ServerCli.execute(ServerCli.java:100)
	    at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	    at org.elasticsearch.cli.Command.main(Command.java:50)
	    at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
    
      
      {"category":"APP","error":{"context":{"category":"technical","error":"connect ECONNREFUSED 
     172.19.0.11:9200","http_status":500,"reason":"[SEARCH] Search engine seems down"},"message":"A configuration error   
     occurred","name":"ConfigurationError","stack":"ConfigurationError: A configuration error has occurred\n    at error 
     (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:61:53)\n    at 
     /opt/opencti/build/src/database/engine.js:182:15\n    at processTicksAndRejections (node:internal/process
     /task_queues:95:5)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:172:3)\n    at 
     checkSystemDependencies (/opt/opencti/build/src/initialization.js:131:3)\n    at platformStart (/opt/opencti/build
     /src/boot.js:179:5)"},"level":"error","message":"[OPENCTI] Platform start 
     fail","timestamp":"2024-01-15T20:32:54.577Z","version":"5.8.2"}
