### ISSUE TITLE
OpenCTI Startup issues

### ISSUE THREAD

**Issue by LikelyMalware** [LuatixHQ/opencti#5711]
## Description

I created a brand new standalone OpenCTI env with Docker. the platform does not starts. the rest of the services works fine, although the platform itself doesn't start. it shows me the following log:

`2024-01-27 01:54:20 {"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Cannot destructure property 'password_policy_min_length' of 't' as it is undefined.","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Cannot destructure property 'password_policy_min_length' of 't' as it is undefined.\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)\n    at platformStart (/opt/opencti/build/src/boot.js:242:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Cannot destructure property 'password_policy_min_length' of 't' as it is undefined.","name":"TypeError","stack":"TypeError: Cannot destructure property 'password_policy_min_length' of 't' as it is undefined.\n    at checkPasswordInlinePolicy (/opt/opencti/build/src/domain/user.js:419:5)\n    at checkPasswordFromPolicy (/opt/opencti/build/src/domain/user.js:471:18)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at addUser (/opt/opencti/build/src/domain/user.js:501:5)\n    at initAdmin (/opt/opencti/build/src/domain/user.js:1409:5)\n    at initializeAdminUser (/opt/opencti/build/src/config/providers.js:45:5)\n    at platformInit (/opt/opencti/build/src/initialization.js:379:7)\n    at platformStart (/opt/opencti/build/src/boot.js:238:5)"}],"level":"error","message":"Platform unmanaged direct error","timestamp":"2024-01-26T23:54:20.358Z","version":"5.12.23"}`

I went through the code and i'm not sure what causes this issue. the password and tokens i use should be just fine.

## Environment

1. OS Windows 10
2. OpenCTI version: 5.12.23
3. OpenCTI client: frontend
4. Other environment details:

**Comment by SamuelHassine** [comment]
Hello @LikelyMalware,

For whatever reason, it seems your Settings have been deleted. I think you should completely reset your platform at this point. If not possible, please reach us on Slack.

Kind regards,
Samuel

**Comment by jcandiat** [comment]
I update from 5.12.22 to 5.12.24 and i had a similar error...

![image](https://github.com/OpenCTI-Platform/opencti/assets/5710026/89a3cce2-d772-4548-9173-2601f8430398)

**Comment by aptohunter** [comment]
me too

**Comment by nino-filigran** [comment]
Did you both try the above solution proposed by Sam?

**Comment by aptohunter** [comment]
> 你们都尝试过Sam提出的上述解决方案吗？

yes，i delete all of docker imgaes and volumes ，also been 500

**Comment by jcandiat** [comment]
The platform started with the 5.12.26 version uploaded to Github!

**Comment by alice-debra** [comment]
Hello @LikelyMalware,
We’re following up to see if you still need an answer to this question. If you still need help with this, don't hesitate to ask on our Slack: https://filigran-community.slack.com/. 
As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice

**Comment by aptohunter** [comment]
你好，你的收信我已收到，谢谢
