### ISSUE TITLE
CSV Mapper error importing File hashes

### ISSUE THREAD

**Issue by akshaysth** [LuatixHQ/opencti#5738]
## Description

Importing a CSV file containing a SHA-256 hash with a simple CSV mapper config fails. Testing the CSV in the CSV mapper configuration panel, displays the error illustrated in the screenshot below:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1302562/5483c0d4-1c22-464e-808f-194778110a2c)

Platform logs show the following error:
```
2024-01-29 14:21:37 {"category":"APP","errors":[{"attributes":{"data":{"entity_type":"StixFile","hashes":"1a1c10e61db489aaf7a1593236260745cb0c1dfa782cc371e3e82b60924a182b","objectMarking":[]},"genre":"BUSINESS","http_status":500,"properties":[[{"src":"hashes"}],[{"src":"name"}]]},"message":"Missing required elements for StixFile creation ( - )","name":"UNSUPPORTED_ERROR","stack":"UNSUPPORTED_ERROR: Missing required elements for StixFile creation ( - )\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnsupportedError (/opt/opencti/build/src/config/errors.js:83:51)\n    at idGen (/opt/opencti/build/src/schema/identifier.js:267:11)\n    at generateStixUUID (/opt/opencti/build/src/schema/identifier.js:406:10)\n    at generateStixId (/opt/opencti/build/src/schema/identifier.js:418:16)\n    at generateStandardId (/opt/opencti/build/src/schema/identifier.js:434:43)\n    at handleId (/opt/opencti/build/src/parser/csv-mapper.ts:135:28)\n    at mapRecord (/opt/opencti/build/src/parser/csv-mapper.ts:264:3)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at mappingProcess (/opt/opencti/build/src/parser/csv-mapper.ts:300:19)\n    at /opt/opencti/build/src/parser/csv-bundler.ts:47:24\n    at async Promise.all (index 1)\n    at bundleProcess (/opt/opencti/build/src/parser/csv-bundler.ts:40:5)\n    at csvMapperTest (/opt/opencti/build/src/modules/internal/csvMapper/csvMapper-domain.ts:24:18)"}],"inner_relation_creation":0,"level":"error","message":"Missing required elements for StixFile creation ( - )","operation":"CsvMapperTestDialogQuery","operation_query":"query CsvMapperTestDialogQuery($configuration:String!$content:String!){csvMapperTest(configuration:$configuration content:$content){objects nbRelationships nbEntities}}","size":518,"time":7,"timestamp":"2024-01-29T19:21:37.851Z","type":"READ_ERROR","user":{"group_ids":["29329133-d41d-451d-8575-c39b3f21475c"],"ip":"::ffff:192.168.65.1","organization_ids":[],"referer":"http://localhost:8080/dashboard/data/processing/csv_mapper","socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}},"variables":{"configuration":"{\"id\":\"7f57b42f-9655-4779-b85e-ee6d41d8c9f0\",\"name\":\"test\",\"has_header\":true,\"separator\":\",\",\"skipLineChar\":\"\",\"representations\":[{\"id\":\"6702f5cf-a3ff-49da-a108-65ffd1ce633a\",\"type\":\"entity\",\"target\":{\"entity_type\":\"StixFile\"},\"attributes\":[{\"key\":\"hashes\",\"column\":{\"column_name\":\"A\",\"configuration\":null},\"default_values\":null,\"based_on\":null}]}]}","content":"sha-256,label\n1a1c10e61db489aaf7a1593236260745cb0c1dfa782cc371e3e82b60924a182b,test"},"version":"5.12.24"}
```

There is an existing feature request (https://github.com/OpenCTI-Platform/opencti/issues/4806) that is proposed for 6.0.0 that addresses this issue, however, there's currently no other workaround.

## Environment

1. OS (where OpenCTI server runs): docker
2. OpenCTI version: 5.12.24
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new CSV Mapper config with only the File entity
2. populate the File entity's hash as Column A of the CSV file
3. Save and test the CSV Mapper config with a CSV file

## Expected Output

Creation of a File observable with the appropriate(MD5, SHA1, SHA256) hash(es)

## Actual Output

Error shown in the screenshot above.

**Comment by SamuelHassine** [comment]
Hello @akshaysth,

We know this is painful and we confirm there is no workaround. We are working hard on the implementation of this feature.

Kind regards,
Samuel
