### ISSUE TITLE
File indexing blocked

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5822]
## Description

File indexing has been blocked for several days/weeks. The counter is no longer progressing and remains stuck on my 1300th file.

## Environment

OCTI 5.12.26
OpenSearch (AWS cloud)

## Logs

`{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"The specified key does not exist.","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: The specified key does not exist.
    at error (/opt/opencti/build/src/config/errors.js:8:10)
    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)
    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)
    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)
    at fileIndexHandler (/opt/opencti/build/src/manager/fileIndexManager.ts:159:18)
    at /opt/opencti/build/src/manager/fileIndexManager.ts:202:9
    at Tft.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)
    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"},{"message":"The specified key does not exist.","name":"NoSuchKey","stack":"NoSuchKey: The specified key does not exist.
    at de_NoSuchKeyRes (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5196:23)
    at de_GetObjectCommandError (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3440:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /opt/opencti/build/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at /opt/opencti/build/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:63:20
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
    at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at getFileContent (/opt/opencti/build/src/database/file-storage.js:157:18)
    at loadFilesToIndex (/opt/opencti/build/src/manager/fileIndexManager.ts:53:19)"}],"level":"error","manager":"FILE_INDEX_MANAGER","message":"Platform unmanaged direct error","timestamp":"2024-02-05T00:23:12.995Z","version":"5.12.26"}`

**Comment by SamuelHassine** [comment]
@Lhorus6 I think this is the bug we have fixed in 5.12.29, no @richard-julien?

**Comment by richard-julien** [comment]
I dont think. Its a different engine than the upload system. 

loadFilesToIndex doest handle this kind of situation.

> const filesToIndex = await BluePromise.map(filesToLoad, loadFilesToIndex, { concurrency: 5 });

```
export const getFileContent = async (id, encoding = 'utf8') => {
  const object = await s3Client.send(new s3.GetObjectCommand({
    Bucket: bucketName,
    Key: id
  }));
  return streamToString(object.Body, encoding);
};
```

**Comment by Jipegien** [comment]
I am not sure to understand the situation and its impact. Is it the count that is broken, or the entire file indexing? Is it concerning all platform?

**Comment by richard-julien** [comment]
I think the file indexing is blocked due to this problem.

**Comment by Lhorus6** [comment]
Exactly, the file indexing is blocked. I can redirect you to the user with this problem if you want to dig with them directly on their platform
