### ISSUE TITLE
Cannot read properties of null Errors

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#5824]
## Description

Seeing lots of `Cannot read properties of null (reading 'filter')` & `Cannot read properties of null (reading 'split')` errors during normal operation

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 5.12.
3. OpenCTI client: Frontend
4. Other environment details: Clusered Scaled 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Not sure

## Actual Output

```json
{
    "category": "APP",
    "errors": [
        {
            "attributes": {
                "genre": "TECHNICAL",
                "http_status": 500
            },
            "message": "Cannot read properties of null (reading 'filter')",
            "name": "UNKNOWN_ERROR",
            "stack": "UNKNOWN_ERROR: Cannot read properties of null (reading 'filter')\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:70:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)\n    at Object.warn (/opt/opencti/build/src/config/conf.js:320:47)\n    at Object.willSendResponse (/opt/opencti/build/src/graphql/loggerPlugin.js:100:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at b (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:530:5)\n    at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"
        },
        {
            "message": "Cannot read properties of null (reading 'filter')",
            "name": "TypeError",
            "stack": "TypeError: Cannot read properties of null (reading 'filter')\n    at /opt/opencti/build/src/database/middleware.js:1533:42\n    at Array.map (<anonymous>)\n    at prepareAttributesForUpdate (/opt/opencti/build/src/database/middleware.js:1477:19)\n    at updateAttributeRaw (/opt/opencti/build/src/database/middleware.js:1573:28)\n    at updateAttributeMetaResolved (/opt/opencti/build/src/database/middleware.js:1947:24)\n    at upsertElement (/opt/opencti/build/src/database/middleware.js:2682:20)\n    at createEntity (/opt/opencti/build/src/database/middleware.js:3320:16)\n    at addVulnerability (/opt/opencti/build/src/domain/vulnerability.js:19:19)"
        }
    ],
    "inner_relation_creation": 1,
    "level": "warn",
    "message": "Platform unmanaged direct error",
    "operation": "VulnerabilityAdd",
    "operation_query": "mutation VulnerabilityAdd($input:VulnerabilityAddInput!){vulnerabilityAdd(input:$input){id standard_id entity_type parent_types}}",
    "size": 771,
    "time": 108,
    "timestamp": "2024-02-03T07:11:58.445Z",
    "type": "WRITE_ERROR",
    "user": {
        "applicant_id": "6a4b11e1-90ca-4e42-ba42-db7bc7f7d505",
        "call_retry_number": "1",
        "group_ids": [],
        "ip": "192.X.X.X",
        "organization_ids": [],
        "socket": "query",
        "user_id": "6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"
    },
    "version": "5.12.15"
}
```

**Comment by Jipegien** [comment]
We are unable to reproduce. Can you give more details about how to reproduce?

**Comment by MaxwellDPS** [comment]
I dont have any, I can provide logs directly proceeding this, but I need to know what clustered components yall want it scoped to

**Comment by Jipegien** [comment]
if the problem is still there after upgrading to the latest version, let me know.
