### ISSUE TITLE
What is this error means?

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#5999]
```
ERR Fail to execute engine pagination | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500,"query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":2,"should":[{"bool":{"minimum_should_match":3,"should":[{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["event_source_id.keyword"],"query":"be6b5136-4db9-4ccd-b2fa-cb8031387f27"}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["status.keyword"],"query":"complete"}}]}},{"bool":{"minimum_should_match":1,"should":[{"range":{"completed_time":{"lte":"now-7d/d"}}}]}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["entity_type.keyword","parent_types.keyword"],"query":"Work"}}]}}]}}],"must_not":[]}},"size":500,"sort":[{"standard_id.keyword":"asc"}]},"index":["opencti_history"],"track_total_hits":true}},"message":"Fail to execute engine pagination","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Fail to execute engine pagination\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/engine.js:2520:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at elList (/opt/opencti/build/src/database/engine.js:2543:22)\n    at deleteCompletedWorks (/opt/opencti/build/src/manager/connectorManager.js:93:3)\n    at connectorHandler (/opt/opencti/build/src/manager/connectorManager.js:117:7)\n    at /opt/opencti/build/src/manager/connectorManager.js:137:9\n    at npt.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"},{"message":"The content length (536932588) is bigger than the maximum allowed string (536870888)","name":"RequestAbortedError","stack":"RequestAbortedError: The content length (536932588) is bigger than the maximum allowed string (536870888)\n    at aYt.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:574:34)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at k$e.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:89:10)\n    at elList (/opt/opencti/build/src/database/engine.js:2543:22)\n    at deleteCompletedWorks (/opt/opencti/build/src/manager/connectorManager.js:93:3)\n    at connectorHandler (/opt/opencti/build/src/manager/connectorManager.js:117:7)\n    at /opt/opencti/build/src/manager/connectorManager.js:137:9\n    at npt.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"}] manager=CONNECTOR_MANAGER timestamp=2024-02-16T06:34:16.696Z version=5.12.31
```

This is an error message that occurs in the opencti container. It continues to occur periodically. 

The behavior of opencti itself is fine, but the site is too slow to respond.

**Comment by labo-flg** [comment]
From what I can see in, it happens when starting a connector, at the connector manager level.
It tries to cleanup old completed works but fails on the elastic search query.

@helene-nguyen is this something you also encounters when testing connectors on your side ?

**Comment by helene-nguyen** [comment]
Hello @misohouse,

I've checked the log error. Not a connector or OpenCTI issue, it is a database issue. According to this log:

`"RequestAbortedError: The content length (536932588) is bigger than the maximum allowed string (536870888)`

The following message occured because it is a limitation from the database:

- [Elasticsearch Limitations](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-kibana.html#:~:text=Querying%20many%20many,of%20fields%20returned.)

And this comes from the circuit breaker of Elastic:

- [Circuit breaker](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html)

You can increase the cluster settings following these steps if needed:

- [Cluster settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html)

Hope that helps :)

**Comment by helene-nguyen** [comment]
I close the issue for now, it can be re-opened if needed 😊

**Comment by misohouse** [comment]
@helene-nguyen I read the “Cluster setting” page but it’s hard to understand that since I set up the elasticsearch by docker-compose in portainer.

Would you tell me how to configure the cluster setting of elasticsearch by docker-compose in portainer?
