### ISSUE TITLE
Deploy of OpenCTI in GKE (GCP) fails with ERROR "Invalid URL"

### ISSUE THREAD

**Issue by sorenopsy** [LuatixHQ/opencti#6107]
## Description

Trying to deploy Opencti on GKE (Google Cloud kubernetes) using helm chart
https://github.com/devops-ia/helm-charts/tree/main/charts/opencti
with basic configuration:

env:
  APP__ADMIN__EMAIL: admin@opencti.io
  APP__ADMIN__PASSWORD: test
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
  APP__BASE_PATH: "/"
  APP__SESSION_COOKIE: "true"
  ELASTICSEARCH__ENGINE_SELECTOR: auto
  ELASTICSEARCH__URL: http://opencti-elasticsearch:9200
  MINIO__ENDPOINT:  opencti-minio:9000
  RABBITMQ__HOSTNAME: opencti-rabbitmq
  RABBITMQ__PORT_MANAGEMENT: 15672
  RABBITMQ__PORT: 5672
  RABBITMQ__USERNAME: guest
  RABBITMQ__PASSWORD: guest
  # REDIS
  REDIS__HOSTNAME: opencti-redis-master
  REDIS__PORT: 6379
  REDIS__MODE: single

Everythins is up, except opencti-servre that fails with the following error:

2024-02-26T08:57:47.052141505Z stdout F {"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2024-02-26T08:57:47.049Z","version":"5.12.33"}
2024-02-26T08:57:47.052932012Z stdout F {"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2024-02-26T08:57:47.052Z","version":"
5.12.33"}
2024-02-26T08:57:47.053644623Z stdout F {"category":"APP","level":"info","message":"[SEARCH] Engine client not specified, trying to discover it with opensearch client","timesta
mp":"2024-02-26T08:57:47.053Z","version":"5.12.33"}
2024-02-26T08:57:47.091452661Z stdout F {"category":"APP","level":"info","message":"[SEARCH] Engine detected to elk","timestamp":"2024-02-26T08:57:47.085Z","version":"5.12.33"}
2024-02-26T08:57:47.111675618Z stdout F {"category":"APP","level":"info","message":"[SEARCH] elk (8.11.3) client selected / runtime sorting enabled / attachment processor enabl
ed","timestamp":"2024-02-26T08:57:47.111Z","version":"5.12.33"}
2024-02-26T08:57:47.112092614Z stdout F {"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2024-02-26T08:57:47.111Z","version":"5.12.33"}
2024-02-26T08:57:47.120065538Z stdout F {"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Invalid URL","name":"UNKNOWN_ERROR","stack"
:"UNKNOWN_ERROR: Invalid URL\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._l
ogWithError (/opt/opencti/build/src/config/conf.js:311:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)\n    at platformStart (/opt/opencti/build/src/boo
t.js:21:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Invalid URL","name":"TypeError","stack":"TypeError: Invalid URL\n    at new
 URL (node:internal/url:775:36)\n    at parseUrl (/opt/opencti/build/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)\n    at toEndpointV1 (/opt/opencti/build/node_modu
les/@smithy/middleware-endpoint/dist-cjs/index.js:112:32)\n    at i (/opt/opencti/build/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65)\n    at processTicksA
ndRejections (node:internal/process/task_queues:95:5)"}],"level":"error","message":"Platform unmanaged direct error","timestamp":"2024-02-26T08:57:47.119Z","version":"5.12.33"

## Environment

OS (where OpenCTI server runs): Container-Optimized OS with containerd ( cos_containerd ) - deployed on Google Kubernetes Engine
OpenCTI version: 5.12.33
OpenCTI client: frontend?
Other environment details: 

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/39803539/37b3dab0-744e-43a7-b76a-e0ae42bd4eea)

**Comment by sorenopsy** [comment]
After troubleshooting fond out that missing parameters of MINIO_ACCESS_KEY and MINIO_SECRET_KEY created the issue.

**Comment by ishtiaqSamdani** [comment]
@sorenopsy  have you provided AWS S3's ACCESS_KEY and SECRET_KEY? or GCS?
