### ISSUE TITLE
Error migrating from 5.10.3 to 5.11.0

### ISSUE THREAD

**Issue by alsbnd** [LuatixHQ/opencti#6165]
Hi,

I have a problem trying to upgrade from 5.10.3 to 5.11.0.
I use Portainer 2.19.4 for managing opencti.

Here are the environment data:
OS: Debian 11
OpenCTI version: 5.10.3 CE
Redis: 7.2.4
Elasticsearch: 8.12.0
Minio: RELEASE.2023-05-18T00-05-36Z
Rabbitmq: 3.12-management

I wrote 5.11.0 in the Portainer stack editor.
Update Stack run well, but the platform did not start on port 8080 and the log of the service is:
ERR [MIGRATION] Error during migration | category=APP error={"context":{},"message":"Cannot read properties of undefined (reading '_index')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading '_index')\n    at uxd.up (/opt/opencti/build/src/migrations/1694352490408-stream-access.js:27:31)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"} timestamp=2024-02-28T16:22:23.639Z version=5.11.0

ERR [OPENCTI] Platform start fail | category=APP error={"context":{"category":"technical","error":{},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:394:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:219:5)"} timestamp=2024-02-28T16:22:23.645Z version=5.11.0

After that I come back to 5.10.3 and everything come back well.

What I must do for upgrading OpenCTI? I would like to use the 6.0.0 and the end.

Regards,

Alessio

**Comment by SamuelHassine** [comment]
Hello,

We advise you to go directly to 6.0.0.

Kind regards,
Samuel

**Comment by alsbnd** [comment]
I will try as soon as possibile.
But when I tried to migrate to 5.12.23, 5.12.24 and others than 5.11.0 the problems was the same.
But I will try.

Thanks.

**Comment by alsbnd** [comment]
Hi,

I installed the 6.0.0 but the platform still fails to start.

These are the messages. Weird thing is the at the end of the log messages appears "5.11.0", but this images is not anymore live.    

ERR [MIGRATION] Error during migration | category=APP error={"context":{},"message":"Cannot read properties of undefined (reading '_index')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading '_index')\n    at uxd.up (/opt/opencti/build/src/migrations/1694352490408-stream-access.js:27:31)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"} timestamp=2024-02-28T16:34:56.007Z version=5.11.0

ERR [OPENCTI] Platform start fail | category=APP error={"context":{"category":"technical","error":{},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:394:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:219:5)"} timestamp=2024-02-28T16:34:56.013Z version=5.11.0

Don't know what I can do.

Alessio

**Comment by alsbnd** [comment]
Hi,

The platform did not start. But there are another error to whom I could not find a solution.

ERR Platform unmanaged direct error | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Cannot read properties of undefined (reading '_index')","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Cannot read properties of undefined (reading '_index')\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:331:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:341:48)\n    at /opt/opencti/build/src/database/migration.js:127:18\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Cannot read properties of undefined (reading '_index')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading '_index')\n    at Zpu.up (/opt/opencti/build/src/migrations/1694352490408-stream-access.js:27:31)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}] timestamp=2024-02-28T18:36:18.374Z version=6.0.0

ERR Platform unmanaged direct error | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Cannot read properties of undefined (reading '_index')","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Cannot read properties of undefined (reading '_index')\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:331:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:341:48)\n    at platformStart (/opt/opencti/build/src/boot.js:21:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Cannot read properties of undefined (reading '_index')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading '_index')\n    at Zpu.up (/opt/opencti/build/src/migrations/1694352490408-stream-access.js:27:31)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}] timestamp=2024-02-28T18:36:18.378Z version=6.0.0

Need help.

Thanks.

**Comment by alsbnd** [comment]
Hi,

It seems to be a database conversion problem.
Any idea?

Alessio

**Comment by richard-julien** [comment]
Hi @alsbnd , that looks complex. The error you have means that a capability definition is missing in your database.
Do you have a kibana to be able to explore that data?

**Comment by alsbnd** [comment]
Hi @richard-julien ,

No, I don't have kibana installed in the OpenCTI asset.

Alessio

**Comment by alice-debra** [comment]
Hello @alsbnd,
We’re following up to see if you still need an answer to this question. If you still need help with this, don't hesitate to ask on our Slack: https://filigran-community.slack.com/. 
As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
