### ISSUE TITLE
Error when deleting a large number of entities

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#6344]
## Description

When I try to delete more than 1000 entities, an error occurs in the task logs
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/fc40e8b5-0c0f-4e4e-858a-597afc4c8d6f)

Please tell me how can I delete several million entities effectively?

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 6.0.4
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run a task to delete a large number of entities (in my case, 6 million entities)
2. See that the removal process stops after some time

## Expected Output

All entities were deleted without errors

## Actual Output

The entity deletion process has stopped

## Additional information

Platform logs:

{
  "category": "APP",
  "errors": [
    {
      "attributes": {
        "executions": [
          {
            "id": "67950c2c-6f47-4af2-9b49-ca7682ae0c1d",
            "message": "Request timed out - no reason provided"
          },
          {
            "id": "3ad09adf-1fdf-4fdc-80e3-a12a0d3dbb39",
            "message": "Request timed out - no reason provided"
          },
          {
            "id": "b92cdcc1-b157-4289-b6f0-0f77b7f3a6e5",
            "message": "Request timed out - no reason provided"
          },
          {
            "id": "25a4df2c-b5ca-4666-9a55-cb08e358df7f",
            "message": "Request timed out - no reason provided"
          },
          {
            "id": "3b1f336a-8640-4c54-a706-850e04b65e00",
            "message": "Request timed out - no reason provided"
          },
          {
            "id": "3fa4755e-30a2-44dc-a363-480d90a7c7a6",
            "message": "Request timed out - no reason provided"
          }
        ],
        "genre": "TECHNICAL",
        "http_status": 500
      },
      "message": "Tasks execution failure",
      "name": "UNKNOWN_ERROR",
      "stack": "UNKNOWN_ERROR: Tasks execution failure\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at executeProcessing (/opt/opencti/build/src/manager/taskManager.js:449:18)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at taskHandler (/opt/opencti/build/src/manager/taskManager.js:494:22)\n    at /opt/opencti/build/src/manager/taskManager.js:524:9\n    at lTt.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"
    }
  ],
  "level": "error",
  "message": "Tasks execution failure",
  "timestamp": "2024-03-14T07:40:34.943Z",
  "version": "6.0.4"
}

**Comment by alice-debra** [comment]
Hello @rattat0r,
We wanted to follow up to check if you are still experiencing the problem. If we are unable to reproduce the bug within the next few days, we may need to close this ticket.
Apologies for the lack of response regarding this question.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
