### ISSUE TITLE
Attack pattern knowledge matrix query perf issue

### ISSUE THREAD

**Issue by SouadHadjiat** [LuatixHQ/opencti#6662]
## Description

When viewing the attack patterns of an entity (in knowledge view), the query used to display this view can send a lot of requests to the database, leading in some cases to errors : 

```
"message":"Fail to execute engine pagination","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Fail to execute engine pagination\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/engine.js:2862:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at listEntitiesThroughRelationsPaginated (/opt/opencti/build/src/database/middleware-loader.ts:477:28)"},{"message":"search_phase_execution_exception\n\tCaused by:\n\t\tes_rejected_execution_exception: rejected execution of TimedRunnable{original=org.elasticsearch.action.search.FetchSearchPhase$1@525f033, creationTimeNanos=5678643698163724, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = opencti-prod-1/search, queue capacity = 1000, task execution EWMA = 2.5ms, total task execution time = 9.8d, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@3b8ce72[Running, pool size = 13, active threads = 13, queued tasks = 999, completed tasks = 521468374]]","name":"ResponseError","stack":"ResponseError: search_phase_execution_exception\n\tCaused by:\n\t\tes_rejected_execution_exception: rejected execution of TimedRunnable{original=org.elasticsearch.action.search.FetchSearchPhase$1@525f033, creationTimeNanos=5678643698163724, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = opencti-prod-1/search, queue capacity = 1000, task execution EWMA = 2.5ms, total task execution time = 9.8d, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@3b8ce72[Running, pool size = 13, active threads = 13, queued tasks = 999, completed tasks = 521468374]]\n    at Bon.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:553:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at qrt.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:89:10)\n    at listEntitiesThroughRelationsPaginated (/opt/opencti/build/src/database/middleware-loader.ts:477:28)"}],"inner_relation_creation":0,"level":"error","message":"Fail to execute engine pagination","operation":"StixDomainObjectAttackPatternsKillChainStixCoreRelationshipsQuery","operation_query":"query StixDomainObjectAttackPatternsKillChainStixCoreRelationshipsQuery($fromOrToId:[String]$elementWithTargetTypes:[String]$first:Int$filters:FilterGroup){...StixDomainObjectAttackPatternsKillChain_data} ...
````

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.0.9
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

not reproduced.

## Additional information

Issue raised in the slack community

**Comment by mvibraim** [comment]
Hello
In which release is this problem expected to be fixed?

**Comment by nino-filigran** [comment]
@mvibraim we've increased the priority of this bug internally. When someone will assign to it, this means this bug will be actively worked on & therefore, delivered in a minor release. Ticket will be updated accordingly. I cannot tell right now when this fix will be available though.

**Comment by mvibraim** [comment]
Thanks for the clarification, I will wait for the fix.
I found that the Attack Pattern screen error does not happens when [this threadpool config](https://github.com/OpenCTI-Platform/docker/commit/a40bcc75035219c2a0caf7ac21ca6f2b855581d0) is used in the database configuration. 
I think the threadpool config will not be needed after the fix be launched, right?
OpenCTI is deployed in AWS here and we are using Amazon OpenSearch Service as a database. When I asked AWS to change the threadpool config they said that increase the value from the default (1000) to 5000 will increase the database latency. And this can increase OpenCTI load time.
