### ISSUE TITLE
Manual installation of Opencti 

### ISSUE THREAD

**Issue by Alroff08** [LuatixHQ/opencti#6719]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I have installed the OpenCTI as per the instructions provided when I do Yarn build and then do yarn serv I am receiving an error message 

## Environment

1.  Ubuntu 22.x
2. OpenCTI version: 6.0.9
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. yarn build
2. yarn serv
3. {"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2024-04-17T07:18:42.190Z","version":"6.0.9"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2024-04-17T07:18:42.195Z","version":"6.0.9"}
{"category":"APP","level":"info","message":"[SEARCH] Engine opensearch client selected by configuration","timestamp":"2024-04-17T07:18:42.196Z","version":"6.0.9"}
{"category":"APP","dependencyError":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":null,"headers":null,"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":4,"headers":{},"id":"https://172.16.40.144:9200/","resurrectTimeout":1713338802590,"roles":{"data":true,"ingest":true},"status":"dead","url":"https://172.16.40.144:9200/"},"context":null,"name":"opensearch-js","request":{"id":1,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.6.0 (linux 5.15.0-102-generic-x64; Node.js v20.12.2)"},"method":"GET","path":"/","querystring":"","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-04-17T07:18:42.592Z"},"level":"error","message":"[OPENCTI] System dependencies check failed","timestamp":"2024-04-17T07:18:42.592Z","version":"6.0.9"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Search engine seems down","name":"CONFIGURATION_ERROR","stack":"CONFIGURATION_ERROR: Search engine seems down\n    at error (/usr/local/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/usr/local/opencti/build/src/config/errors.js:70:53)\n    at /usr/local/opencti/build/src/database/engine.js:235:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/usr/local/opencti/build/src/database/engine.js:231:22)\n    at searchEngineInit (/usr/local/opencti/build/src/database/engine.js:270:27)\n    at checkSystemDependencies (/usr/local/opencti/build/src/initialization.js:31:3)\n    at platformStart (/usr/local/opencti/build/src/boot.js:14:7)"},{"message":"self-signed certificate in certificate chain","name":"ConnectionError","stack":"ConnectionError: self-signed certificate in certificate chain\n    at ClientRequest.onError (/usr/local/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)\n    at ClientRequest.emit (node:events:518:28)\n    at TLSSocket.socketErrorListener (node:_http_client:500:9)\n    at TLSSocket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}],"level":"error","message":"Search engine seems down","timestamp":"2024-04-17T07:18:42.601Z","version":"6.0.9"}

## Additional information

{
  "app": {
    "port": 4000,
    "base_path": "",
    "base_url": "http://localhost:4000/",
    "enabled": true,
    "disabled_dev_features": ["PUBLIC_DASHBOARD"],
    "https_cert": {
      "ca": [],
      "key": null,
      "crt": null,
      "reject_unauthorized": true,
      "cookie_secure": false
    },
    "app_logs": {
      "logs_level": "info",
      "logs_files": true,
      "logs_console": true,
      "logs_max_files": 7,
      "logs_directory": "./logs",
      "logs_redacted_inputs": ["password", "secret", "token"]
    },
    "audit_logs": {
      "logs_files": true,
      "logs_console": true,
      "logs_max_files": 7,
      "logs_directory": "./logs"
    },
    "event_loop_logs": {
      "enabled": false,
      "max_time": 1000
    },
    "graphql": {
      "armor_enabled": false,
      "playground": {
        "enabled": true,
        "force_disabled_introspection": false
      }
    },
    "telemetry": {
      "tracing": {
        "enabled": false,
  "exporter_otlp": "",
        "exporter_zipkin": ""
      },
      "metrics": {
        "enabled": false,
        "exporter_otlp": "",
        "exporter_prometheus": 14269
      }
    },
    "health_access_key": "ChangeMe",
    "request_timeout": 1200000,
    "session_timeout": 1200000,
    "session_cookie": false,
    "locked_account_statuses": {
      "Inactive": "Your account has been marked inactive. If you would like to reactivate your account, please contact your administrator.",
      "Locked": "Your account has been locked for security reasons. Please contact your administrator."
    },
    "account_statuses_default": "Active",
    "session_idle_timeout": 0,
    "session_manager": "shared",
    "rate_protection": {
      "time_window": 1,
      "max_requests": 10000
    },
    "concurrency": {
      "retry_count": 100,
      "retry_delay": 250,
      "retry_jitter": 100,
      "max_ttl": 60000,
      "extension_threshold": 5000
    },
    "live_stream": {
      "cache_max_size": 5000,
      "cache_max_time": 2
    },
    "performance_logger": false,
    "map_tile_server_dark": "https://map.opencti.io/styles/filigran-dark2/{z}/{x}/{y}.png",
    "map_tile_server_light": "https://map.opencti.io/styles/filigran-light2/{z}/{x}/{y}.png",
    "reference_attachment": false,
    "python_execution": "native",
    "artifact_zip_password": "infected",
    "admin": {
  "email": "admin@opencti.io",
      "password": "Exelegent@01",
      "token": "1980f819-df26-42be-83a0-e094b9b63594"
    },
    "group_confidence_level": {
      "max_confidence_default": 100
    }
  },
  "demo_mode": false,
  "http_proxy": "",
  "https_proxy": "",
  "no_proxy": "",
  "https_proxy_ca": [],
  "https_proxy_reject_unauthorized": false,
  "relations_deduplication": {
    "past_days": 30,
    "next_days": 30,
    "created_by_based": false
  },
  "ai": {
    "enabled": true,
    "type": "mistralai",
    "endpoint": "",
    "token": "",
    "model": "",
    "model_images": ""
  },
  "xtm": {
    "openbas_url": "",
    "openbas_token": "",
    "openerm_url": "",
    "openrm_token": "",
    "openmtd_url": "",
    "openmtd_token": ""
  },
  "data_sharing": {
    "max_csv_feed_result": 5000
  },
  "rule_engine": {
    "enabled": true,
    "lock_key": "rule_engine_lock"
  },
 },
  "history_manager": {
    "enabled": true,
    "include_inferences": true,
    "lock_key": "history_manager_lock"
  },
  "activity_manager": {
    "enabled": true,
    "lock_key": "activity_manager_lock"
  },
  "connector_manager": {
    "enabled": true,
    "lock_key": "connector_manager_lock",
    "works_day_range": 7,
    "interval": 60000
  },
  "import_csv_built_in_connector": {
    "enabled": true,
    "interval": 10000,
    "validate_before_import": false
  },
  "task_scheduler": {
    "enabled": true,
    "lock_key": "task_manager_lock",
    "interval": 10000
  },
  "expiration_scheduler": {
    "enabled": true,
    "lock_key": "expired_manager_lock",
    "interval": 300000
  },
  "notification_manager": {
    "enabled": true,
    "lock_live_key": "notification_live_manager_lock",
    "lock_digest_key": "notification_digest_manager_lock",
    "interval": 10000
  },
  "playbook_manager": {
    "enabled": true,
    "lock_key": "playbook_manager_lock",
    "interval": 60000
  },
 "indicator_decay_manager": {
    "enabled": true,
    "lock_key": "indicator_decay_manager_lock",
    "batch_size": 10000,
    "interval": 60000
  },
  "publisher_manager": {
    "enabled": true,
    "lock_key": "publisher_manager_lock",
    "interval": 10000
  },
  "sync_manager": {
    "enabled": true,
    "lock_key": "sync_manager_lock",
    "interval": 10000
  },
  "ingestion_manager": {
    "enabled": true,
    "lock_key": "ingestion_manager_lock",
    "interval": 300000
  },
  "retention_manager": {
    "enabled": true,
    "lock_key": "retention_manager_lock",
    "interval": 60000
  },
  "file_index_manager": {
    "enabled": true,
    "lock_key": "file_index_manager_lock",
    "stream_lock_key": "file_index_manager_stream_lock",
    "interval": 60000
  },
  "redis": {
    "mode": "single",
    "namespace": "",
    "hostname": "localhost",
    "use_ssl": false,
    "ca": [],
    "port": 6379,
    "trimming": 2000000
  },
 "elasticsearch": {
    "index_prefix": "opencti",
    "url": "https://172.16.40.144:9200",
    "username": "elastic",
    "password": "i31p=QHe6123SSTOcT3m",
    "engine_selector": "opensearch",
    "engine_check": false,
    "index_creation_pattern": "-000001",
    "search_wildcard_prefix": false,
    "search_fuzzy": false,
    "max_pagination_result": 5000,
    "default_pagination_result": 500,
    "max_bulk_operations": 5000,
    "max_runtime_resolutions": 5000,
    "max_concurrency": 4
  },
  "minio": {
    "bucket_name": "opencti-bucket",
    "bucket_region": "us-east-1",
    "endpoint": "localhost",
    "port": 9000,
    "use_ssl": false,
    "access_key": "miniouser",
    "secret_key": "miniouser",
    "use_aws_role": false,
    "excluded_files": [".DS_Store"]
  },
  "rabbitmq": {
    "queue_prefix": "",
    "hostname": "localhost",
    "vhost": "/",
    "use_ssl": false,
    "use_ssl_ca": [],
    "port": 5672,
    "port_management": 15672,
    "management_ssl": false,
    "username": "guest",
    "password": "guest",
    "queue_type": "classic"
  },
"smtp": {
    "hostname": "localhost",
    "use_ssl": false,
    "reject_unauthorized": false,
    "port": 25,
    "username": "",
    "password": ""
  },
  "providers": {
    "local": {
      "strategy": "LocalStrategy"
    }
  }
}

**Comment by Alroff08** [comment]
I am having a new issue now {"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2024-04-17T17:52:04.401Z","version":"6.0.9"}
{"category":"APP","dependencyError":{"$metadata":{"attempts":3,"totalRetryDelay":128},"address":"172.16.40.144","code":"ECONNREFUSED","errno":-111,"port":9000,"syscall":"connect"},"level":"error","message":"[OPENCTI] System dependencies check failed","timestamp":"2024-04-17T17:52:04.836Z","version":"6.0.9"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"connect ECONNREFUSED 172.16.40.144:9000","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: connect ECONNREFUSED 172.16.40.144:9000\n    at error (/usr/local/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/usr/local/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/usr/local/opencti/build/src/config/conf.js:331:23)\n    at Object.error (/usr/local/opencti/build/src/config/conf.js:341:48)\n    at platformStart (/usr/local/opencti/build/src/boot.js:47:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"connect ECONNREFUSED 172.16.40.144:9000","name":"Error","stack":"Error: connect ECONNREFUSED 172.16.40.144:9000\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)"}],"level":"error","message":"Platform unmanaged direct error","timestamp":"2024-04-17T17:52:04.843Z","version":"6.0.9"}

**Comment by khoavan001** [comment]
i see your: elasticsearch:url is https. how do you deal with ca certificate. i added elasticsearch:ssl:ca but seems doesnt work.

**Comment by alice-debra** [comment]
Hello @khoavan001,
We’re following up to see if @khoavan001's solution has solved your problem. As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
