### ISSUE TITLE
Cannot add Data Component through contextual component

### ISSUE THREAD

**Issue by Bonsai8863** [LuatixHQ/opencti#6816]
## Description

On an Attack Pattern entity view, click the plus icon next to 'Data components'. Click on a data component in the drawer and nothing happens.

## Environment

1. OS (where OpenCTI server runs): Mac OS Sonoma 14.4.1
2. OpenCTI version: 6.0.10
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Have system running with at least one Attack Pattern and one Data component
2. Navigate to an Attack Pattern entity
3. Click the plus icon next to 'Data components'
4. Click on a data component in the drawer that appears

## Expected Output

The clicked data component's icon should be replaced with a blue check mark and it should appear on the attack pattern's entity view.

## Actual Output

Nothing happens: No logs in console or from graphql backend.

On page refresh it appears the relationship was created linking the Attack Pattern to the selected Data Component, but the Data Component still does not appear under the Details section. I've tried adding Data Components after deleting the relationships to no avail.

## Screenshots (optional)

https://github.com/OpenCTI-Platform/opencti/assets/131906254/bb69691c-295e-4bae-9fee-34bddc25014c

**Comment by Bonsai8863** [comment]
The contextual Data Component add on Data Sources also appears to fail, but this time with an error. We get the following toast: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/131906254/2e36abb3-ce1b-4357-bca7-362851a72011)

and the following error in the backend:
```
{
  "category": "APP",
  "errors": [
    {
      "attributes": { "genre": "TECHNICAL", "http_status": 500 },
      "message": "input.find is not a function",
      "name": "UNKNOWN_ERROR",
      "stack": "UNKNOWN_ERROR: input.find is not a function\n    at error (/path/to/opencti/opencti-platform/opencti-graphql/src/config/errors.js:8:10)\n    at UnknownError (/path/to/opencti/opencti-platform/opencti-graphql/src/config/errors.js:76:47)\n    at Object._logWithError (/path/to/opencti/opencti-platform/opencti-graphql/src/config/conf.js:331:23)\n    at Object.error (/path/to/opencti/opencti-platform/opencti-graphql/src/config/conf.js:341:48)\n    at Object.willSendResponse (/path/to/opencti/opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js:119:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at sendResponse (/path/to/opencti/opencti-platform/opencti-graphql/node_modules/apollo-server-core/src/requestPipeline.ts:530:5)\n    at processHTTPRequest (/path/to/opencti/opencti-platform/opencti-graphql/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"
    },
    {
      "message": "input.find is not a function",
      "name": "TypeError",
      "stack": "TypeError: input.find is not a function\n    at stixDomainObjectEditField (/path/to/opencti/opencti-platform/opencti-graphql/src/domain/stixDomainObject.js:205:30)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at dataSourceDataComponentAdd (/path/to/opencti/opencti-platform/opencti-graphql/src/modules/dataSource/dataSource-domain.ts:33:3)"
    }
  ],
  "inner_relation_creation": 0,
  "level": "error",
  "message": "Platform unmanaged direct error",
  "operation": "AddDataComponentsLinesToDataSourceRelationAddMutation",
  "operation_query": "mutation AddDataComponentsLinesToDataSourceRelationAddMutation($id:ID!$dataComponentId:ID!){dataSourceDataComponentAdd(id:$id dataComponentId:$dataComponentId){...DataSourceDataComponents_dataSource id}}fragment DataSourceDataComponents_dataSource on DataSource{id name parent_types entity_type dataComponents{edges{node{id parent_types name description}}}}",
  "size": 102,
  "time": 4,
  "timestamp": "2024-04-25T16:03:03.165Z",
  "type": "WRITE_ERROR",
  "user": {
    "group_ids": ["ede27053-615b-418d-8a72-1adf5c1e3ea6"],
    "ip": "::1",
    "organization_ids": [],
    "referer": "http://localhost:4000/dashboard/techniques/data_sources/45ada5f8-4f19-4c9a-b813-6e1613475843",
    "socket": "query",
    "user_id": "88ec0c6a-13ce-5e39-b486-354fe4a7084f",
    "user_metadata": {}
  },
  "variables": {
    "dataComponentId": "67ff9302-70f2-42e8-a5f0-fd386f92beda",
    "id": "45ada5f8-4f19-4c9a-b813-6e1613475843"
  },
  "version": "6.0.10"
}

```
