### ISSUE TITLE
K8 Helm deployment failing with UNKNOWN_ERROR: Invalid URL\n

### ISSUE THREAD

**Issue by mkay2999** [LuatixHQ/opencti#6907]
So ive been trying to deploy via helm chart, the elastic, minio, rabbitmq and redis are all running and all init containers pass but when the server starts to launch, I get the error below and the container goes into a crash loop. 

{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2024-05-07T14:06:01.761Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2024-05-07T14:06:01.763Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[SEARCH] Engine client not specified, trying to discover it with opensearch client","timestamp":"2024-05-07T14:06:01.763Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[SEARCH] Engine detected to elk","timestamp":"2024-05-07T14:06:01.804Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[SEARCH] elk (8.12.2) client selected / runtime sorting enabled / attachment processor enabled","timestamp":"2024-05-07T14:06:01.824Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2024-05-07T14:06:01.824Z","version":"6.0.5"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Invalid URL","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Invalid URL\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:331:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:341:48)\n    at platformStart (/opt/opencti/build/src/boot.js:21:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Invalid URL","name":"TypeError","stack":"TypeError: Invalid URL\n    at new URL (node:internal/url:775:36)\n    at parseUrl (/opt/opencti/build/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)\n    at toEndpointV1 (/opt/opencti/build/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:112:32)\n    at i (/opt/opencti/build/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}],"level":"error","message":"Platform unmanaged direct error","timestamp":"2024-05-07T14:06:01.831Z","version":"6.0.5"}

## Environment

 Kubernetes RKE v1.21.9
 OpenCTI 1.2.1

these are the environmental variables set in my values.yaml.
env:
  # Plain vars
  # foo: bar
  # my_env: my_value
  # APP OPENCTI
  APP__BASE_URL: http://opencti:4000
  APP__ADMIN__EMAIL: admin@opencti.io
  APP__ADMIN__PASSWORD: 1Password@
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
  APP__BASE_PATH: "/"
  APP__SESSION_COOKIE: "true"
  
  # MINIO:
  MINIO__ENDPOINT: opencti-minio:9000
  MINIO_ACCESS_KEY: key12345
  MINIO_SECRET_KEY: pwd12345
  # ELASTICSEARCH
  ELASTICSEARCH__ENGINE_SELECTOR: auto
  ELASTICSEARCH__URL: http://opencti-elasticsearch:9200
  # RABBITMQ
  RABBITMQ__HOSTNAME: opencti-rabbitmq
  RABBITMQ__PORT_MANAGEMENT: 15672
  RABBITMQ__PORT: 5672
  RABBITMQ__USERNAME: user
  RABBITMQ__PASSWORD: Password
  # REDIS
  REDIS__HOSTNAME: opencti-redis-master
  REDIS__PORT: 6379
  REDIS__MODE: single
  # METRICS AND HEALTHCHECK
  APP__TELEMETRY__METRICS__ENABLED: true
  APP__HEALTH_ACCESS_KEY: Password

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. helm install -f Chart.yaml opencti ./

**Comment by Reverse-laboratory** [comment]
May I ask if your problem has been resolved? I also encountered the same problem

**Comment by mkay2999** [comment]
> May I ask if your problem has been resolved? I also encountered the same problem

No, I still have the problem

**Comment by jtambi-cs** [comment]
I am getting similar error in EKS cluster
I am using v1.8.0
All checks required before run the service passed, but when opencti-server trying to startup is showing following error:

{"category":"APP","environment":"production","level":"info","message":"[OPENCTI] Starting platform","source":"backend","timestamp":"2025-02-04T19:36:37.078Z","version":"6.4.8"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","source":"backend","timestamp":"2025-02-04T19:36:37.080Z","version":"6.4.8"}
{"category":"APP","level":"info","message":"[CHECK] checking if Search engine is alive","source":"backend","timestamp":"2025-02-04T19:36:37.080Z","version":"6.4.8"}
{"category":"APP","level":"info","message":"[SEARCH] Engine elk client selected by configuration","source":"backend","timestamp":"2025-02-04T19:36:37.115Z","version":"6.4.8"}
{"category":"APP","level":"info","message":"[SEARCH] elk (8.17.0) client selected / runtime sorting enabled / attachment processor enabled","source":"backend","timestamp":"2025-02-04T19:36:37.141Z","version":"6.4.8"}
{"category":"APP","level":"info","message":"[CHECK] Search engine ok, checking if File storage is alive","source":"backend","timestamp":"2025-02-04T19:36:37.142Z","version":"6.4.8"}
{"category":"APP","cause":{"code":"UNKNOWN_ERROR","message":"Invalid URL","name":"TypeError","stack":"TypeError: Invalid URL\n    at new URL (node:internal/url:806:29)\n    at parseUrl (/opt/opencti/build/back.js:529:24818)\n    at toEndpointV1 (/opt/opencti/build/back.js:565:26781)\n    at customEndpointProvider (/opt/opencti/build/back.js:565:30447)"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2025-02-04T19:36:37.151Z","version":"6.4.8"}

**Comment by gambl3** [comment]
I had the same issue. The documentation [here](https://github.com/devops-ia/helm-opencti/blob/main/charts/opencti/docs/configuration.md) is wrong. It appears that adding the `:9000` causes the `Invald URL` error

```
env:
...
  MINIO__ENDPOINT: <release-name>-minio:9000
```

I had to do this to get past the error.

``` # MINIO
  MINIO__ENDPOINT: <release>-minio
  MINIO__PORT: 9000
  MINIO__ACCESS_KEY: <user>
  MINIO__SECRET_KEY: <password>
  MINIO__USE_SSL: false
```

You can use the `envFromSecrets`  for the secrets data. I used env variables for troubleshooting.

**Comment by ialejandro** [comment]
> I had the same issue. The documentation [here](https://github.com/devops-ia/helm-opencti/blob/main/charts/opencti/docs/configuration.md) is wrong. It appears that adding the `:9000` causes the `Invald URL` error
> 
> ```
> env:
> ...
>   MINIO__ENDPOINT: <release-name>-minio:9000
> ```
> 
> I had to do this to get past the error.
> 
> ```
>   MINIO__ENDPOINT: <release>-minio
>   MINIO__PORT: 9000
>   MINIO__ACCESS_KEY: <user>
>   MINIO__SECRET_KEY: <password>
>   MINIO__USE_SSL: false
> ```
> 
> You can use the `envFromSecrets` for the secrets data. I used env variables for troubleshooting.

Fixed on docs. Thx.
