### ISSUE TITLE
Malware Bazar Connector Error

### ISSUE THREAD

**Issue by 1337Deep** [LuatixHQ/opencti#6933]
## Description

Got this Error 

ERROR {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'} | timestamp=2024-05-13T06:03:03.679354Z name=MalwareBazaar Recent Additions exc_info=Traceback (most recent call last):
  File "/opt/opencti-connector-malwarebazaar-recent-additions/malwarebazaar-recent-additions.py", line 128, in run
    response = self.upload_artifact_opencti(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-malwarebazaar-recent-additions/malwarebazaar-recent-additions.py", line 260, in upload_artifact_opencti
    return self.helper.api.stix_cyber_observable.upload_artifact(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1802, in upload_artifact
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^

## Environment

1. OS (where OpenCTI server runs): {Ubuntu 23.10}
2. OpenCTI version: { 6.0.10 }
3. OpenCTI client: { python }

## Reproducible Steps

Steps to create the smallest reproducible scenario:
open Malware Bazar Connector Logs 

## Actual Output

```
raceback (most recent call last):
  File "/opt/opencti-connector-malwarebazaar-recent-additions/malwarebazaar-recent-additions.py", line 90, in run
    recent_additions_list = self.get_recent_additions()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-malwarebazaar-recent-additions/malwarebazaar-recent-additions.py", line 191, in get_recent_additions
    resp = requests.post(self.api_url, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mb-api.abuse.ch', port=443): Max retries exceeded with url: /api/v1/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c6b3e3e24d0>: Failed to resolve 'mb-api.abuse.ch' ([Errno -3] Try again)"))
ERROR {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'} | timestamp=2024-05-13T06:13:10.949042Z name=MalwareBazaar Recent Additions exc_info=Traceback (most recent call last):
  File "/opt/opencti-connector-malwarebazaar-recent-additions/malwarebazaar-recent-additions.py", line 128, in run
    response = self.upload_artifact_opencti(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-malwarebazaar-recent-additions/malwarebazaar-recent-additions.py", line 260, in upload_artifact_opencti
    return self.helper.api.stix_cyber_observable.upload_artifact(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1802, in upload_artifact
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 353, in query
    raise ValueError(
ValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}

```

**Comment by nino-filigran** [comment]
@1337Deep can you please open your ticket in this repo please? https://github.com/OpenCTI-Platform/connectors/issues
I'm closing your ticket just to ensure this repo remain clean.
