### ISSUE TITLE
When mandatory attributes are enabled in Report, importing data from CSV fails

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6947]
## Description

When mandatory attributes are enabled in Report type, importing a CSV generates the following error: 

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Setup mandatory attributes for the Report type
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/866b8615-8e67-43ab-a563-10f0c5c503e6)
2. Create a simple CSV mapper to ingest URLs
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/9415e1ab-3bb2-41f8-b007-79b2d575c9d4)

3. Create a report, a CSV file containing URLs and upload the file inside the report
[urls.csv](https://github.com/OpenCTI-Platform/opencti/files/15299225/urls.csv)
4. Import the CSV file using the previously created CSV mapper

## Actual Output

**[May 13, 2024, 8:54:46 PM] {'name': 'VALIDATION_ERROR', 'message': 'Validation error'}**

```
Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 269, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py", line 215, in import_bundle_from_json
    return self.import_bundle(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py", line 2669, in import_bundle
    self.import_object(item, update, types)
  File "/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py", line 990, in import_object
    stix_object_results = do_import(
                          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_report.py", line 881, in import_from_stix2
    return self.create(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_report.py", line 724, in create
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 359, in query
    raise ValueError(
ValueError: {'name': 'VALIDATION_ERROR', 'message': 'Validation error'}
```

**Comment by richard-julien** [comment]
https://github.com/OpenCTI-Platform/opencti/pull/6862 must be reviewed and merged first

**Comment by frapuks** [comment]
#5550 will create a new capability 'Bypass mandatory fields' for connectors
