### ISSUE TITLE
Deploying OpenCTI with helm reported an error

### ISSUE THREAD

**Issue by Reverse-laboratory** [LuatixHQ/opencti#7065]
## Description

Deploying OpenCTI with helm reported an error

## Environment

1. kubernetes version v1.26.6
2. helm version 3.9.4
3. OpenCTI version platform:6.0.5
4. Other environment details:

setp1 
kubectl get pod
output ：
root@master:/opencti# kubectl get pod
NAME                                              READY   STATUS             RESTARTS        AGE
nfs-subdir-external-provisioner-577d66557-ptj8f   1/1     Running            1 (109m ago)    47h
opencti-elasticsearch-data-0                      1/1     Running            0               19m
opencti-elasticsearch-master-0                    1/1     Running            0               19m
opencti-minio-8655fcbb79-ds6ns                    1/1     Running            0               19m
opencti-rabbitmq-0                                1/1     Running            0               19m
opencti-redis-master-0                            1/1     Running            0               19m
opencti-server-55d6878f45-kpxjk                   0/1     CrashLoopBackOff   8 (2m15s ago)   19m
opencti-worker-86c4644756-qzrns                   0/1     CrashLoopBackOff   8 (3m33s ago)   19m

setp2
root@master:/opencti# kubectl logs opencti-server-55d6878f45-kpxjk
Defaulted container "opencti-server" out of: opencti-server, ready-checker-elasticsearch (init), ready-checker-minio (init), ready-checker-rabbitmq (init), ready-checker-redis-master (init)
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2024-05-22T08:49:58.615Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2024-05-22T08:49:58.616Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[SEARCH] Engine client not specified, trying to discover it with opensearch client","timestamp":"2024-05-22T08:49:58.617Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[SEARCH] Engine detected to elk","timestamp":"2024-05-22T08:49:58.642Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[SEARCH] elk (8.12.2) client selected / runtime sorting enabled / attachment processor enabled","timestamp":"2024-05-22T08:49:58.658Z","version":"6.0.5"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2024-05-22T08:49:58.659Z","version":"6.0.5"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Invalid URL","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Invalid URL\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:331:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:341:48)\n    at platformStart (/opt/opencti/build/src/boot.js:21:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Invalid URL","name":"TypeError","stack":"TypeError: Invalid URL\n    at new URL (node:internal/url:775:36)\n    at parseUrl (/opt/opencti/build/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)\n    at toEndpointV1 (/opt/opencti/build/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:112:32)\n    at i (/opt/opencti/build/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}],"level":"error","message":"Platform unmanaged direct error","timestamp":"2024-05-22T08:49:58.668Z","version":"6.0.5"}

**Comment by Jipegien** [comment]
Without knowing your helm chart and your platform config, we cannot be of much help. 

At least, your error messages seem to indicate the config parameters of your platform are not right : platformStart (/opt/opencti/build/src/boot.js:21:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Invalid URL","name":"TypeError","stack":"TypeError: Invalid URL\n    at new URL (node:internal/url:775:36

**Comment by nino-filigran** [comment]
@Hades-p seing that there's no activity on this ticket, I'm closing it for now. Please feel free to re-open it if the issue persists on your side our if you have additional information.
