### ISSUE TITLE
Issue with Docker stack deployment

### ISSUE THREAD

**Issue by swaybs** [LuatixHQ/opencti#7162]
I have run through the correct steps in the documentation to deploy the stack via docker-compose. I have changed the default values for **.env** file and generated new UUID's. When the stack deploys, and I try to connect to port 8080, I get a **refused to connect** on that port. 

**Logs for opencti container:**
`ERR [OPENCTI] System dependencies check failed | category=APP dependencyError={"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":null,"headers":null,"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":4,"headers":{},"id":"http://elasticsearch:9200/","resurrectTimeout":1714566800942,"roles":{"data":true,"ingest":true},"status":"dead","url":"http://elasticsearch:9200/"},"context":null,"name":"opensearch-js","request":{"id":1,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.6.0 (linux 5.15.0-105-generic-x64; Node.js v20.12.0)"},"method":"GET","path":"/","querystring":"","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-05-01T12:25:20.943Z"} timestamp=2024-05-01T12:25:20.943Z version=6.0.9`

`ERR Search engine seems down | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Search engine seems down","name":"CONFIGURATION_ERROR","stack":"CONFIGURATION_ERROR: Search engine seems down\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:70:53)\n    at /opt/opencti/build/src/database/engine.js:235:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/opt/opencti/build/src/database/engine.js:231:22)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:279:27)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:31:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"},{"message":"getaddrinfo EAI_AGAIN elasticsearch","name":"ConnectionError","stack":"ConnectionError: getaddrinfo EAI_AGAIN elasticsearch\n    at ClientRequest.onError (/opt/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)\n    at ClientRequest.emit (node:events:518:28)\n    at Socket.socketErrorListener (node:_http_client:500:9)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}] timestamp=2024-05-01T12:25:20.947Z version=6.0.9
`

**Logs for opencit-elasticsearch container:**
`Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 8589934592 bytes. Error detail: committing reserved memory.
An error report file with more information is saved as:
logs/hs_err_pid28.log
error:
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000600000000, 8589934592, 0) failed; error='Not enough space' (errno=12)
	at org.elasticsearch.server.cli.JvmOption.flagsFinal(JvmOption.java:120)
	at org.elasticsearch.server.cli.JvmOption.findFinalOptions(JvmOption.java:87)
	at org.elasticsearch.server.cli.MachineDependentHeap.determineHeapSettings(MachineDependentHeap.java:59)
	at org.elasticsearch.server.cli.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:141)
	at org.elasticsearch.server.cli.JvmOptionsParser.determineJvmOptions(JvmOptionsParser.java:92)
	at org.elasticsearch.server.cli.ServerCli.startServer(ServerCli.java:248)
	at org.elasticsearch.server.cli.ServerCli.execute(ServerCli.java:100)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.Command.main(Command.java:50)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
`

**Comment by stoyky** [comment]
I have the same issue on a Docker single node, whatever I do I am unable to reach port 8080 with a "Connection reset" message. Switching to different ports doesn't help either.

**Comment by swaybs** [comment]
Any thoughts on what could be causing this? This error is a direct result from following the documentation to stand up the platform with Docker.

**Comment by AmmisettyBhuvanesh** [comment]
I am getting the same error for the last 10 days anf i couldnt trouble shoot them...i am using the the latest version of container.along with that,adding connectors also throwing many errors like 


401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
2024-05-08T12:26:17.878289057Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff8ecc150>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878292363Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff938fa90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878295579Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff936af10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878298785Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff98b5390>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878301991Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff98a0250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878305177Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff9b75e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878308363Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff939dc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878312180Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff93bb050>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878315466Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff98959d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878318672Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff93c66d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878321898Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff93a5fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878325104Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff93a60d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878333420Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff93b9150>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878336786Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff98c6590>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-08T12:26:17.878340022Z HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff93d0a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff8e97c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff8e70dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff8fb8090>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ff8e98090>: Failed to establish a new connection: [Errno 111] Connection refused'))

HTTPSConnectionPool(host='api.maltiverse.com', port=443): Max retries exceeded with url: /taxii2/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f0ff8dcef10>: Failed to resolve 'api.maltiverse.com' ([Errno -3] Try again)"))
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/
401 Client Error: UNAUTHORIZED for url: https://api.maltiverse.com/taxii2/api/collections/

**Comment by nikgreg99** [comment]
You arent' the only one.  I am trying to deploy it, but the docker compose is chaotic. For example the minio image used is not present into the Docker Hub registry

**Comment by Kamasan94** [comment]
I have the same issue, is the conenction parameter HTTPConnectionPool(host='opencti', port=8080) right?

**Comment by nikgreg99** [comment]
Also, I have deployed trough Portainer, but  i cannot reach the API. What could be the problem?

**Comment by sha1024zz** [comment]
> I have the same issue on a Docker single node, whatever I do I am unable to reach port 8080 with a "Connection reset" message. Switching to different ports doesn't help either.

I also have the same issue, please could someone kindly assist - thanks

**Comment by vesector** [comment]
same here

**Comment by jajaapie** [comment]
Still the same here..

**Comment by amirseyedian** [comment]
Issue is caused by opencti container not resolving `http://elasticsearch:9200`

First make sure elasticsearch is running and is healthy, then take note of the ip address of the elasticseach container by running `docker network ls` and then `docker network inspect`
drop to opencti root terminal and see if you can connect to elasticsearch by ip if you get the proper output from ES then try the alias `curl http://elasticsearch:9200` 
if IP work but the hostname does not then you need to reassign network alias.
First deattach elasticsearch container from the network then run this
`docker network connect --alias elasticsearch <docker_network> <docker-elasticsearch-container>`
now `curl http://elasticsearch:9200`  should work.

Also you can put the ip address of elasticsearch container in the Opencti configuration env but thats a temporary fix since ip address will change after restart.

**Comment by alice-debra** [comment]
Hello,
We’re following up to see if @amirseyedian's solution has solved your problem.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
