### ISSUE TITLE
Platform cant get the lock for initialization

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#7338]
## Description

Hi, I recently upgraded to v6.1.7, which meant the migration had to take place. This seemed to complete, but later on I had an ES issue, which I fixed. Then there were RabbitMQ errors, so CTI failed dependency check and thus the platform would not initialise. I seem to have resolve those errors, however now I am seeing the below but not sure where to look as Redis/RabbitMQ aren't displaying any errors in the logs for those services:

`ERR [OPENCTI] Platform default initialization failed | category=APP cause={"_error":{},"_showLocations":false,"_showPath":false,"data":{"genre":"BUSINESS","http_status":500,"participantIds":["platform_init_lock"]},"internalData":{},"name":"LOCK_ERROR","time_thrown":"2024-06-10T13:52:21.354Z"} source=backend timestamp=2024-06-10T13:52:21.354Z version=6.1.7`

`ERR Platform cant get the lock for initialization (can be due to other instance currently migrating/initializing) | category=APP errors=[{"attributes":{"genre":"BUSINESS","http_status":500,"participantIds":["platform_init_lock"]},"message":"Platform cant get the lock for initialization (can be due to other instance currently migrating/initializing)","name":"LOCK_ERROR","stack":"LOCK_ERROR: Platform cant get the lock for initialization (can be due to other instance currently migrating/initializing)\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at LockTimeoutError (/opt/opencti/build/src/config/errors.js:110:51)\n    at platformInit (/opt/opencti/build/src/initialization.js:115:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:28:7)"}] source=backend timestamp=2024-06-10T13:52:21.356Z version=6.1.7`

How can I find out exactly what is causing this? 

Restarting the stack didn't seem to help.

## Environment

OpenCTI v6.1.7

**Comment by dominictory** [comment]
created new redis volume to resolve
