### ISSUE TITLE
Taxii current_state_cursor Bug 

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#7403]
## Description
TAXII bug still present from 5678

```
{
    "category": "APP",
    "context": "Taxii ingestion execution",
    "errors": [
        {
            "attributes": {
                "genre": "BUSINESS",
                "http_status": 400
            },
            "message": "Validation against schema failed on attribute [current_state_cursor]: this mandatory field cannot be nil",
            "name": "FUNCTIONAL_ERROR",
            "stack": "FUNCTIONAL_ERROR: Validation against schema failed on attribute [current_state_cursor]: this mandatory field cannot be nil\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:95:50)\n    at validateInputAgainstSchema (/opt/opencti/build/src/schema/schema-attributes.ts:287:11)\n    at /opt/opencti/build/src/schema/schema-attributes.ts:342:5\n    at Array.forEach (<anonymous>)\n    at validateDataBeforeIndexing (/opt/opencti/build/src/schema/schema-attributes.ts:336:24)\n    at elUpdateElement (/opt/opencti/build/src/database/engine.js:3597:3)\n    at updateAttributeMetaResolved (/opt/opencti/build/src/database/middleware.js:2058:13)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at processImmediate (node:internal/timers:449:9)\n    at patchTaxiiIngestion (/opt/opencti/build/src/modules/ingestion/ingestion-taxii-domain.ts:57:19)\n    at taxiiV21DataHandler (/opt/opencti/build/src/manager/ingestionManager.ts:250:5)\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)\n    at ingestionHandler (/opt/opencti/build/src/manager/ingestionManager.ts:366:5)\n    at /opt/opencti/build/src/manager/ingestionManager.ts:385:9\n    at Abt.#runHandlerAndScheduleTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:36:13)\n    at Timeout._onTimeout (/opt/opencti/build/node_modules/set-interval-async/dist/set-interval-async-timer.cjs:29:13)"
        }
    ],
    "level": "error",
    "message": "Validation against schema failed on attribute [current_state_cursor]: this mandatory field cannot be nil",
    "name": "",
    "source": "backend",
    "timestamp": "2024-06-17T20:50:39.645Z",
    "version": "6.1.6"
}
```

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 6.1.6
3. OpenCTI client: frontend
4. Other environment details: Clustered

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Unknown

## Additional information

https://github.com/OpenCTI-Platform/opencti/issues/5678
https://github.com/OpenCTI-Platform/opencti/issues/4767

**Comment by nino-filigran** [comment]
Hey @MaxwellDPS I'm not sure to understand the context of your issue: could you specify? If I understand the underlying issue, you're trying to ingest something through a TAXII collection and it fails so you have this error?

**Comment by aHenryJard** [comment]
The issue seems to come from this code line when data.next does not exists on taxii response:
https://github.com/OpenCTI-Platform/opencti/blob/f0ed94129c1dafb0040bed13b51ab98d2d9b5213/opencti-platform/opencti-graphql/src/manager/ingestionManager.ts#L251

Fallback should not be undefined but something allowed by the database shema (empty string maybe ?)

**Comment by MaxwellDPS** [comment]
> Hey @MaxwellDPS I'm not sure to understand the context of your issue: could you specify? If I understand the underlying issue, you're trying to ingest something through a TAXII collection and it fails so you have this error?

Correct
