### ISSUE TITLE
Error while installing openCTI

### ISSUE THREAD

**Issue by otunbacarter** [LuatixHQ/opencti#7453]
## Prerequisites

- [ Yes] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [ Yes] I went through old GitHub issues and couldn't find anything relevant
- [ Yes] I googled the issue and didn't find anything relevant

## Description

I am currently trying to install OpenCTI on my Kali OS and after following all the manual step to install on linux I came across this error while trying to run 'yarn serv' :

TypeError: fCu.PyInterpreter is not a constructor
    at new Interpreter (/home/kali/Downloads/opencti/build/node_modules/node-calls-python/index.js:46:19)
    at /home/kali/Downloads/opencti/build/node_modules/node-calls-python/index.js:223:10
    at /home/kali/Downloads/opencti/build/back.js:1:409
    at Object.<anonymous> (/home/kali/Downloads/opencti/build/node_modules/node-calls-python/index.mjs:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49
                                             
Kindly help with how I can bypass this. I have done all updates and upgrades

![image](https://github.com/OpenCTI-Platform/opencti/assets/19763743/a0913eb1-5d91-4c15-b6dc-c0009191d5ab)

**Comment by felixguerrero12** [comment]
This is still an issue - I have been trying to install this, and have not been successful.
