### ISSUE TITLE
error get Platform default initialization failed while run opencti

### ISSUE THREAD

**Issue by manh7890** [LuatixHQ/opencti#7660]
## Environment

OS (where OpenCTI server runs):Ubuntu 16.4
OpenCTI version: 6.2.0
OpenCTI client: frontend
Other environment details: elasticsearch
## Reproducible Steps

Steps to create the smallest reproducible scenario:
cd opencti-platform -> cd opencti-graphql -> yarn install-> yarn start

## Expected Output

i expected it to run 

## Actual Output
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","source":"backend","timestamp":"2024-07-10T08:32:08.312Z","version":"6.2.3"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":{"error":{"failed_shards":[{"index":"opencti_inferred_entities-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0},{"index":"opencti_internal_objects-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0},{"index":"opencti_stix_cyber_observables-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0},{"index":"opencti_stix_domain_objects-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0},{"index":"opencti_stix_meta_objects-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0}],"grouped":true,"phase":"query","reason":"all shards failed","root_cause":[{"reason":null,"type":"no_shard_available_action_exception"},{"reason":null,"type":"no_shard_available_action_exception"},{"reason":null,"type":"no_shard_available_action_exception"},{"reason":null,"type":"no_shard_available_action_exception"},{"reason":null,"type":"no_shard_available_action_exception"}],"type":"search_phase_execution_exception"},"status":503},"headers":{"content-length":"1155","content-type":"application/vnd.elasticsearch+json;compatible-with=8","x-elastic-product":"Elasticsearch"},"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":0,"headers":{"user-agent":"elasticsearch-js/8.14.0 (linux 6.5.0-41-generic-x64; Node.js 18.16.0; Transport 8.6.1)","x-elastic-client-meta":"es=8.14.0,js=18.16.0,t=8.6.1,hc=18.16.0"},"id":"http://localhost:9201/","maxEventListeners":100,"pool":{"_events":{},"_eventsCount":0},"resurrectTimeout":0,"timeout":30000,"tls":{"ca":null,"rejectUnauthorized":true},"url":"http://localhost:9201/","weight":1000},"context":null,"name":"elasticsearch-js","request":{"id":70,"options":{"signal":{}},"params":{"body":"{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"bool\":{\"should\":[{\"multi_match\":{\"fields\":[\"entity_type.keyword\",\"parent_types.keyword\"],\"query\":\"EntitySetting\"}}],\"minimum_should_match\":1}}],\"minimum_should_match\":1}}],\"must_not\":[]}},\"size\":500,\"sort\":[{\"standard_id.keyword\":\"asc\"}],\"track_total_hits\":true,\"_source\":true}","headers":{"accept":"application/vnd.elasticsearch+json; compatible-with=8","content-length":"324","content-type":"application/vnd.elasticsearch+json; compatible-with=8","user-agent":"elasticsearch-js/8.14.0 (linux 6.5.0-41-generic-x64; Node.js 18.16.0; Transport 8.6.1)","x-elastic-client-meta":"es=8.14.0,js=18.16.0,t=8.6.1,hc=18.16.0"},"method":"POST","path":"/opencti_internal_objects*%2Copencti_stix_meta_objects*%2Copencti_stix_domain_objects*%2Copencti_stix_cyber_observables*%2Copencti_inferred_entities*/_search","querystring":""}}},"statusCode":503,"warnings":null},"name":"ResponseError","options":{"redaction":{"additionalKeys":[],"type":"replace"}}},"genre":"TECHNICAL","http_status":500,"query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["entity_type.keyword","parent_types.keyword"],"query":"EntitySetting"}}]}}]}}],"must_not":[]}},"size":500,"sort":[{"standard_id.keyword":"asc"}]},"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true}},"internalData":{},"name":"DATABASE_ERROR","time_thrown":"2024-07-10T08:32:08.311Z"},"level":"error","message":"[OPENCTI] Platform default initialization failed","source":"backend","timestamp":"2024-07-10T08:32:08.313Z","version":"6.2.3"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["entity_type.keyword","parent_types.keyword"],"query":"EntitySetting"}}]}}]}}],"must_not":[]}},"size":500,"sort":[{"standard_id.keyword":"asc"}]},"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true}},"message":"Fail to execute engine pagination","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Fail to execute engine pagination\n    at error (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/config/errors.js:8:10)\n    at DatabaseError (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/config/errors.js:58:48)\n    at /home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/engine.js:2933:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at elList (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/engine.js:2956:22)\n    at getEntitiesFromCacheFn (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/cache.ts:94:28)\n    at getEntitiesListFromCache (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/cache.ts:122:10)\n    at getEntitySettingFromCache (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-utils.ts:100:26)\n    at createEntityRaw (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/middleware.js:2870:25)\n    at createEntity (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/middleware.js:3035:16)\n    at initializeMigration (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/initialization.js:60:3)\n    at platformInit (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/initialization.js:97:7)\n    at platformStart (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/boot.js:28:7)"},{"message":"search_phase_execution_exception\n\tRoot causes:\n\t\tno_shard_available_action_exception: null\n\t\tno_shard_available_action_exception: null\n\t\tno_shard_available_action_exception: null\n\t\tno_shard_available_action_exception: null\n\t\tno_shard_available_action_exception: null","name":"ResponseError","stack":"ResponseError: search_phase_execution_exception\n\tRoot causes:\n\t\tno_shard_available_action_exception: null\n\t\tno_shard_available_action_exception: null\n\t\tno_shard_available_action_exception: null\n\t\tno_shard_available_action_exception: null\n\t\tno_shard_available_action_exception: null\n    at _SniffingTransport.request (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/node_modules/@elastic/transport/src/Transport.ts:568:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at _Client.SearchApi [as search] (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/node_modules/@elastic/elasticsearch/src/api/api/search.ts:89:10)\n    at elList (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/engine.js:2956:22)\n    at getEntitiesFromCacheFn (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/cache.ts:94:28)\n    at getEntitiesListFromCache (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/cache.ts:122:10)\n    at getEntitySettingFromCache (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-utils.ts:100:26)\n    at createEntityRaw (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/middleware.js:2870:25)\n    at createEntity (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/database/middleware.js:3035:16)\n    at initializeMigration (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/initialization.js:60:3)\n    at platformInit (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/initialization.js:97:7)\n    at platformStart (/home/thanhdk/Documents/Work/NTP/openCti/test/opencti/opencti-platform/opencti-graphql/src/boot.js:28:7)"}],"level":"error","message":"Fail to execute engine pagination","source":"backend","timestamp":"2024-07-10T08:32:08.317Z","version":"6.2.3"}

## Additional information

i have check the error log of graphql 
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"genre":"BUSINESS","http_status":500,"participantIds":["platform_init_lock"]},"internalData":{},"name":"LOCK_ERROR","time_thrown":"2024-07-10T08:17:31.544Z"},"level":"error","message":"[OPENCTI] Platform default initialization failed","source":"backend","timestamp":"2024-07-10T08:17:31.545Z","version":"6.2.3"}
{"category":"APP","cause":{"meta":{"headers":{},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":0,"deadCount":0,"headers":{"user-agent":"elasticsearch-js/8.14.0 (linux 6.5.0-41-generic-x64; Node.js 18.16.0; Transport 8.6.1)","x-elastic-client-meta":"es=8.14.0,js=18.16.0,t=8.6.1,hc=18.16.0"},"id":"http://localhost:9201/","maxEventListeners":100,"pool":{"_events":{},"_eventsCount":0},"resurrectTimeout":0,"timeout":30000,"tls":{"ca":null,"rejectUnauthorized":true},"url":"http://localhost:9201/","weight":1000},"context":null,"name":"elasticsearch-js","request":{"id":34,"options":{},"params":{"body":"{\"aliases\":{\"opencti_stix_domain_objects\":{}}}","headers":{"accept":"application/vnd.elasticsearch+json; compatible-with=8","content-length":"46","content-type":"application/vnd.elasticsearch+json; compatible-with=8","user-agent":"elasticsearch-js/8.14.0 (linux 6.5.0-41-generic-x64; Node.js 18.16.0; Transport 8.6.1)","x-elastic-client-meta":"es=8.14.0,js=18.16.0,t=8.6.1,hc=18.16.0"},"method":"PUT","path":"/opencti_stix_domain_objects-000001","querystring":""}}},"statusCode":0,"warnings":null},"name":"TimeoutError","options":{"redaction":{"additionalKeys":[],"type":"replace"}}},"level":"error","message":"[OPENCTI] Platform default initialization failed","source":"backend","timestamp":"2024-07-10T08:21:38.232Z","version":"6.2.3"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-07-10T08:23:17.385Z"},"level":"error","message":"[OPENCTI] Platform default initialization failed","source":"backend","timestamp":"2024-07-10T08:23:17.386Z","version":"6.2.3"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":{"error":{"failed_shards":[{"index":"opencti_inferred_entities-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0},{"index":"opencti_internal_objects-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0},{"index":"opencti_stix_cyber_observables-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0},{"index":"opencti_stix_domain_objects-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0},{"index":"opencti_stix_meta_objects-000001","node":null,"reason":{"reason":null,"type":"no_shard_available_action_exception"},"shard":0}],"grouped":true,"phase":"query","reason":"all shards failed","root_cause":[{"reason":null,"type":"no_shard_available_action_exception"},{"reason":null,"type":"no_shard_available_action_exception"},{"reason":null,"type":"no_shard_available_action_exception"},{"reason":null,"type":"no_shard_available_action_exception"},{"reason":null,"type":"no_shard_available_action_exception"}],"type":"search_phase_execution_exception"},"status":503},"headers":{"content-length":"1155","content-type":"application/vnd.elasticsearch+json;compatible-with=8","x-elastic-product":"Elasticsearch"},"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":0,"headers":{"user-agent":"elasticsearch-js/8.14.0 (linux 6.5.0-41-generic-x64; Node.js 18.16.0; Transport 8.6.1)","x-elastic-client-meta":"es=8.14.0,js=18.16.0,t=8.6.1,hc=18.16.0"},"id":"http://localhost:9201/","maxEventListeners":100,"pool":{"_events":{},"_eventsCount":0},"resurrectTimeout":0,"timeout":30000,"tls":{"ca":null,"rejectUnauthorized":true},"url":"http://localhost:9201/","weight":1000},"context":null,"name":"elasticsearch-js","request":{"id":70,"options":{"signal":{}},"params":{"body":"{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"bool\":{\"should\":[{\"multi_match\":{\"fields\":[\"entity_type.keyword\",\"parent_types.keyword\"],\"query\":\"EntitySetting\"}}],\"minimum_should_match\":1}}],\"minimum_should_match\":1}}],\"must_not\":[]}},\"size\":500,\"sort\":[{\"standard_id.keyword\":\"asc\"}],\"track_total_hits\":true,\"_source\":true}","headers":{"accept":"application/vnd.elasticsearch+json; compatible-with=8","content-length":"324","content-type":"application/vnd.elasticsearch+json; compatible-with=8","user-agent":"elasticsearch-js/8.14.0 (linux 6.5.0-41-generic-x64; Node.js 18.16.0; Transport 8.6.1)","x-elastic-client-meta":"es=8.14.0,js=18.16.0,t=8.6.1,hc=18.16.0"},"method":"POST","path":"/opencti_internal_objects*%2Copencti_stix_meta_objects*%2Copencti_stix_domain_objects*%2Copencti_stix_cyber_observables*%2Copencti_inferred_entities*/_search","querystring":""}}},"statusCode":503,"warnings":null},"name":"ResponseError","options":{"redaction":{"additionalKeys":[],"type":"replace"}}},"genre":"TECHNICAL","http_status":500,"query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["entity_type.keyword","parent_types.keyword"],"query":"EntitySetting"}}]}}]}}],"must_not":[]}},"size":500,"sort":[{"standard_id.keyword":"asc"}]},"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true}},"internalData":{},"name":"DATABASE_ERROR","time_thrown":"2024-07-10T08:32:08.311Z"},"level":"error","message":"[OPENCTI] Platform default initialization failed","source":"backend","timestamp":"2024-07-10T08:32:08.313Z","version":"6.2.3"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-07-10T08:42:47.231Z"},"level":"error","message":"[OPENCTI] Platform default initialization failed","source":"backend","timestamp":"2024-07-10T08:42:47.231Z","version":"6.2.3"}
and here is my elasticsearch in config 
![image](https://github.com/OpenCTI-Platform/opencti/assets/72128609/dcd4649d-7c3b-4c4e-b958-1188f2bed4c1)

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/72128609/113200a0-ae5a-4a08-adce-e0c978d6ee40)

**Comment by manh7890** [comment]
and i`m sorry if my question wast too long or i provide not enough to debug i am just new to opencti  last week

**Comment by alice-debra** [comment]
Hello @manh7890,
We’re following up to see if you still need an answer to this question. If you still need help with this, don't hesitate to ask on our Slack: https://filigran-community.slack.com/. As there hasn’t been any recent activity, we plan to close the case soon unless we hear otherwise.
Apologies for the lack of response regarding this question.
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice
