### ISSUE TITLE
OpenCTI refuses to start

### ISSUE THREAD

**Issue by nasiriyima** [LuatixHQ/opencti#7994]
## Description

I am setting up OpenCTI using the manual installation method. After installing and configuring all the required components, OpenCTI refuses to start on running` yarn serv`. It fails throwing an error resulting from elasticsearch. I have already verified that all the required components are functioning correctly. I have also updated the python elasticsearch to 6.3.1
## Environment

1. OS (where OpenCTI server runs): Ubuntu 24.04 LTS
2. OpenCTI version: 6.2.12
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Setup OpenCTI using the manual installation methodology

## Expected Output

`yarn serv` fails with errors

## Actual Output
 ```
Platform initialization done","source":"backend","timestamp":"2024-08-08T15:29:41.202Z","version":"6.2.12"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":{"error":"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported","status":406},"headers":{"content-length":"117","content-type":"application/json; charset=UTF-8"},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":0,"deadCount":0,"headers":{"user-agent":"elasticsearch-js/8.14.0 (linux 6.8.0-39-generic-x64; Node.js 20.16.0; Transport 8.6.1)","x-elastic-client-meta":"es=8.14.0,js=20.16.0,t=8.6.1,hc=20.16.0"},"id":"http://localhost:9200/","maxEventListeners":100,"pool":{"_events":{},"_eventsCount":0},"resurrectTimeout":0,"timeout":30000,"tls":{"ca":null,"rejectUnauthorized":true},"url":"http://localhost:9200/","weight":1000},"context":null,"name":"elasticsearch-js","request":{"id":4,"options":{},"params":{"body":"{\"template\":{\"settings\":{\"index\":{\"max_result_window\":100000},\"analysis\":{\"normalizer\":{\"string_normalizer\":{\"type\":\"custom\",\"filter\":[\"lowercase\",\"asciifolding\"]}}}}}}","headers":{"accept":"application/vnd.elasticsearch+json; compatible-with=8","content-length":"168","content-type":"application/vnd.elasticsearch+json; compatible-with=8","user-agent":"elasticsearch-js/8.14.0 (linux 6.8.0-39-generic-x64; Node.js 20.16.0; Transport 8.6.1)","x-elastic-client-meta":"es=8.14.0,js=20.16.0,t=8.6.1,hc=20.16.0"},"method":"PUT","path":"/_component_template/opencti-core-settings","querystring":"create=false"}}},"statusCode":406,"warnings":null},"name":"ResponseError","options":{"redaction":{"additionalKeys":[],"type":"replace"}}},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"DATABASE_ERROR","time_thrown":"2024-08-08T15:29:41.202Z"},"level":"error","message":"[OPENCTI] Platform default initialization failed","source":"backend","timestamp":"2024-08-08T15:29:41.203Z","version":"6.2.12"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Creating component template fail","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Creating component template fail\n    at error (/home/soc-playground/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/home/soc-playground/opencti/build/src/config/errors.js:58:48)\n    at /home/soc-playground/opencti/build/src/database/engine.js:654:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at elCreateCoreSettings (/home/soc-playground/opencti/build/src/database/engine.js:631:3)\n    at elCreateIndices (/home/soc-playground/opencti/build/src/database/engine.js:917:3)\n    at initializeSchema (/home/soc-playground/opencti/build/src/database/engine.js:941:3)\n    at platformInit (/home/soc-playground/opencti/build/src/initialization.js:98:7)\n    at platformStart (/home/soc-playground/opencti/build/src/boot.js:28:7)"},{"message":"{\"error\":\"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported\",\"status\":406}","name":"ResponseError","stack":"ResponseError: {\"error\":\"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported\",\"status\":406}\n    at syn.request (/home/soc-playground/opencti/build/node_modules/@elastic/transport/src/Transport.ts:568:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Myn.putComponentTemplate (/home/soc-playground/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/cluster.ts:374:12)\n    at elCreateCoreSettings (/home/soc-playground/opencti/build/src/database/engine.js:631:3)\n    at elCreateIndices (/home/soc-playground/opencti/build/src/database/engine.js:917:3)\n    at initializeSchema (/home/soc-playground/opencti/build/src/database/engine.js:941:3)\n    at platformInit (/home/soc-playground/opencti/build/src/initialization.js:98:7)\n    at platformStart (/home/soc-playground/opencti/build/src/boot.js:28:7)"}],"level":"error","message":"Creating component template fail","source":"backend","timestamp":"2024-08-08T15:29:41.204Z","version":"6.2.12"}
```

**Comment by nasiriyima** [comment]
So after some digging I updated my ES installation to version 8.9.0, but encountered a new issue. I'm unable to connect to the ES setup using https. I keep getting the error below:

```
{"category":"APP","feature":"TELEMETRY_COUNT_ACTIVE_USERS","level":"info","message":"[FEATURE-FLAG] Deactivated feature still in development","source":"backend","timestamp":"2024-08-09T07:14:46.571Z","version":"6.2.12"}
{"category":"APP","environment":"production","level":"info","message":"[OPENCTI] Starting platform","source":"backend","timestamp":"2024-08-09T07:14:46.619Z","version":"6.2.12"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","source":"backend","timestamp":"2024-08-09T07:14:46.619Z","version":"6.2.12"}
{"category":"APP","level":"info","message":"[CHECK] checking if Search engine is alive","source":"backend","timestamp":"2024-08-09T07:14:46.620Z","version":"6.2.12"}
{"category":"APP","level":"info","message":"[SEARCH] Engine client not specified, trying to discover it with opensearch client","source":"backend","timestamp":"2024-08-09T07:14:46.627Z","version":"6.2.12"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":null,"headers":null,"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":4,"headers":{},"id":"https://192.168.7.153:9200/","resurrectTimeout":1723188166763,"roles":{"data":true,"ingest":true},"status":"dead","url":"https://192.168.7.153:9200/"},"context":null,"name":"opensearch-js","request":{"id":1,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.11.0 (linux 6.8.0-39-generic-x64; Node.js v20.16.0)"},"method":"GET","path":"/","querystring":"","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-08-09T07:14:46.763Z"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2024-08-09T07:14:46.763Z","version":"6.2.12"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Search engine seems down","name":"CONFIGURATION_ERROR","stack":"CONFIGURATION_ERROR: Search engine seems down\n    at error (/home/soc-playground/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/home/soc-playground/opencti/build/src/config/errors.js:76:53)\n    at /home/soc-playground/opencti/build/src/database/engine.js:240:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/home/soc-playground/opencti/build/src/database/engine.js:236:22)\n    at searchEngineInit (/home/soc-playground/opencti/build/src/database/engine.js:322:27)\n    at checkSystemDependencies (/home/soc-playground/opencti/build/src/initialization.js:32:3)\n    at platformStart (/home/soc-playground/opencti/build/src/boot.js:14:7)"},{"message":"self-signed certificate in certificate chain","name":"ConnectionError","stack":"ConnectionError: self-signed certificate in certificate chain\n    at ClientRequest.onError (/home/soc-playground/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)\n    at ClientRequest.emit (node:events:519:28)\n    at TLSSocket.socketErrorListener (node:_http_client:500:9)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}],"level":"error","message":"Search engine seems down","source":"backend","timestamp":"2024-08-09T07:14:46.767Z","version":"6.2.12"}
```

Any further help will be gratefully appreciated. Although setting it up without https worked

**Comment by nasiriyima** [comment]
Issue resolved. In case any one encounters similar errors. Feel free to reopen this, I'll be glad to assist

**Comment by Bella-chris** [comment]
I have the same issue @nasiriyima , can you share with me how did you resolve it?

**Comment by ThanhPhuongw** [comment]
hi @nasiriyima it seem like i have same issuse. Would you mind share how you resolve this issue, please? Thank you!

**Comment by nasiriyima** [comment]
> hi [@nasiriyima](https://github.com/nasiriyima) it seem like i have same issuse. Would you mind share how you resolve this issue, please? Thank you!

Apologies for the belated response. I seldomly check the email address that I use for my GIT account. 

In my case, I had two options to resolve this issue. It was either I downgrade my ES installation to an older version, 7.x below or disable https connection for my ES installation, which might not advisable depending on your environment. Hope these helps.
