### ISSUE TITLE
Public dashboard: one widget is not render correctly on the public link

### ISSUE THREAD

**Issue by aHenryJard** [LuatixHQ/opencti#8297]
## Description

One widget is not renderred correctly on the public link, when looking at dashbord in opencti and authenticated it works worrectly.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 6.2.18
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Please see https://demo.octi.filigran.io/public/dashboard/public-version-finance
I don't know how to know the widget name sorry. But one of them is with "unknown error".

## Expected Output

No widget should be in error.

## Actual Output

Here is the output on the /public view:
![image](https://github.com/user-attachments/assets/90c5e414-0a9b-41d3-948f-4524d0b50a73)

Here is the screenshot on opencti configuration
![image](https://github.com/user-attachments/assets/47b3cf92-ee0e-42e4-a94d-edae400d5760)

**Comment by simonbjorzen-ts** [comment]
Confirming this behaviour, it has worked earlier but don't know exactly what caused this, no error in frontend app logs.

The widget is just a simple entity widget showing the latest Incidents or Reports using entity type filter.
Tried recreating the dashboard without any change.

The viewer is also presented with the message "You must be logged in to do this."

Browser console log:
```
front-264PMXOZ.js:8  Error: Invalid user context !
    at nd1 (front-264PMXOZ.js:140:26633)
    at gi (front-264PMXOZ.js:2201:4179)
    at pyp (front-264PMXOZ.js:10822:51292)
    at Txt (front-264PMXOZ.js:6:17358)
    at Edi (front-264PMXOZ.js:8:44818)
    at wdi (front-264PMXOZ.js:8:40445)
    at Dhu (front-264PMXOZ.js:8:40368)
    at qhn (front-264PMXOZ.js:8:40215)
    at X_t (front-264PMXOZ.js:8:36482)
    at Mdi (front-264PMXOZ.js:8:35396)
N_t @ front-264PMXOZ.js:8
o.componentDidCatch.a.callback @ front-264PMXOZ.js:8
vli @ front-264PMXOZ.js:6
Lli @ front-264PMXOZ.js:8
Adi @ front-264PMXOZ.js:8
Adi @ front-264PMXOZ.js:8
Adi @ front-264PMXOZ.js:8
Adi @ front-264PMXOZ.js:8
Ehu @ front-264PMXOZ.js:8
zhu @ front-264PMXOZ.js:8
p7e @ front-264PMXOZ.js:8
Mdi @ front-264PMXOZ.js:8
Lkt @ front-264PMXOZ.js:1
Rkt @ front-264PMXOZ.js:1
```

**Comment by SouadHadjiat** [comment]
The link https://demo.octi.filigran.io/public/dashboard/public-version-finance doesn't work anymore

**Comment by simonbjorzen-ts** [comment]
@SouadHadjiat it does not, I am experiencing this issue in our own instance.

**Comment by marieflorescontact** [comment]
I can't reproduce, I don't get any error when publishing the widget:

![Image](https://github.com/user-attachments/assets/d8d324a0-1149-49c3-b618-0487556a3d8b)

**Comment by simonbjorzen-ts** [comment]
I can't reproduce now either. Perhaps the issue was solved in a recent patch.

**Comment by marieflorescontact** [comment]
wont' fix as cannot reproduce anymore
