### ISSUE TITLE
[OPENCTI] Platform default initialization failed

### ISSUE THREAD

**Issue by khoavan001** [LuatixHQ/opencti#8784]
## Description

i got the message when run: yarn serv
[OPENCTI] Platform default initialization failed.
might be error comes because i have kill previous yarn serv initiation, 

## Environment

1. OS : Ubuntu 2204
2. OpenCTI version: 6.3.6
3. OpenCTI client: pythin
4. Other environment details:
    Manual installation with:
       Elasticsearch cluster v8.15.2
       Redis-server 6.0.16

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. yarn install
2. yarn build
3. yarn serv
4. error

{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Cannot convert undefined or null to object","name":"UNKNOWN_ERROR","stack":"GraphQLError: Cannot convert undefined or null to object\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:238:17)\n    at Object.error (/opt/opencti/build/src/config/conf.js:247:48)\n    at platformStart (/opt/opencti/build/src/boot.js:42:12)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)"},{"message":"Cannot convert undefined or null to object","name":"TypeError","stack":"TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at Object._objectKeys (/opt/opencti/build/node_modules/fast-json-patch/commonjs/helpers.js:34:23)\n    at _generate (/opt/opencti/build/node_modules/fast-json-patch/commonjs/duplex.js:125:32)\n    at Object.compare (/opt/opencti/build/node_modules/fast-json-patch/commonjs/duplex.js:178:5)\n    at elUpdateIndicesMappings (/opt/opencti/build/src/database/engine.js:1032:34)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at refreshMappingsAndIndices (/opt/opencti/build/src/initialization.js:60:3)\n    at platformInit (/opt/opencti/build/src/initialization.js:117:7)\n    at platformStart (/opt/opencti/build/src/boot.js:29:7)"}],"level":"error","message":"Cannot convert undefined or null to object","source":"backend","timestamp":"2024-10-25T03:26:08.177Z","version":"6.3.6"}

**Comment by khoavan001** [comment]
delete all index in elasticsearch then re-initiate the platform.
