### ISSUE TITLE
Platform crashes - http call interceptor fail / stream is not readable

### ISSUE THREAD

**Issue by simonbjorzen-ts** [LuatixHQ/opencti#8822]
## Description

OpenCTI platform, both backend (for connectors and workers) and frontend (users only) are crashing.

## Environment

1. OS (where OpenCTI server runs): RKE2 Kubernetes
2. OpenCTI version: 6.3.6
3. OpenCTI client: frontend
4. Other environment details: Clustered setup running 3 frontend and 3 backend platform instances

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Error occurs at random intervals on our heavily utilized cluster, dev cluster with same setup but not as heavy usage does not present this issue.

## Expected Output

Platform operating as normal

## Actual Output

Platform crashes, which causes the liveness health probe to fail.

## Additional information

Log output before crash:

```
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Http call interceptor fail","name":"UNKNOWN_ERROR","stack":"GraphQLError: Http call interceptor fail\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at fn (/opt/opencti/build/src/http/httpPlatform.js:501:19)\n    at Rge.handle_error (/opt/opencti/build/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/opt/opencti/build/node_modules/express/lib/router/index.js:326:13)\n    at done (/opt/opencti/build/node_modules/express/lib/router/index.js:286:9)\n    at Function.process_params (/opt/opencti/build/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/opencti/build/node_modules/express/lib/router/index.js:280:10)\n    at Rge.handle_error (/opt/opencti/build/node_modules/express/lib/router/layer.js:67:12)\n    at trim_prefix (/opt/opencti/build/node_modules/express/lib/router/index.js:326:13)\n    at done (/opt/opencti/build/node_modules/express/lib/router/index.js:286:9)\n    at Function.process_params (/opt/opencti/build/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/opencti/build/node_modules/express/lib/router/index.js:280:10)\n    at Rge.handle_error (/opt/opencti/build/node_modules/express/lib/router/layer.js:67:12)\n    at trim_prefix (/opt/opencti/build/node_modules/express/lib/router/index.js:326:13)\n    at done (/opt/opencti/build/node_modules/express/lib/router/index.js:286:9)\n    at Function.process_params (/opt/opencti/build/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/opencti/build/node_modules/express/lib/router/index.js:280:10)\n    at Rge.handle_error (/opt/opencti/build/node_modules/express/lib/router/layer.js:67:12)\n    at trim_prefix (/opt/opencti/build/node_modules/express/lib/router/index.js:326:13)\n    at done (/opt/opencti/build/node_modules/express/lib/router/index.js:286:9)\n    at Function.process
_params (/opt/opencti/build/node_modules/express/lib/router/index.js:346:12)"},{"message":"stream is not readable","name":"InternalServerError","stack":"InternalServerError: stream is not readable\n    at readStream (/opt/opencti/build/node_modules/raw-body/index.js:185:17)\n    at getBody (/opt/opencti/build/node_modules/raw-body/index.js:116:12)\n    at read (/opt/opencti/build/node_modules/body-parser/lib/read.js:79:3)\n    at fn (/opt/opencti/build/node_modules/body-parser/lib/types/json.js:138:5)\n    at Rge.handle [as handle_request] (/opt/opencti/build/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/opencti/build/node_modules/express/lib/router/index.js:328:13)\n    at done (/opt/opencti/build/node_modules/express/lib/router/index.js:286:9)\n    at Function.process_params (/opt/opencti/build/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/opencti/build/node_modules/express/lib/router/index.js:280:10)\n    at fn (/opt/opencti/build/node_modules/passport/lib/middleware/initialize.js:98:5)\n    at Rge.handle [as handle_request] (/opt/opencti/build/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/opencti/build/node_modules/express/lib/router/index.js:328:13)\n    at done (/opt/opencti/build/node_modules/express/lib/router/index.js:286:9)\n    at Function.process_params (/opt/opencti/build/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/opencti/build/node_modules/express/lib/router/index.js:280:10)\n    at cb (/opt/opencti/build/node_modules/express-session/index.js:514:7)\n    at cb (/opt/opencti/build/src/database/sessionStore-redis.js:38:14)\n    at done (/opt/opencti/build/node_modules/async-lock/lib/index.js:104:6)\n    at done (/opt/opencti/build/node_modules/async-lock/lib/index.js:157:7)\n    at /opt/opencti/build/src/database/sessionStore-redis.js:34:16\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}],"level":"error","message":"Http call interceptor fail","source":"backend","timestamp":
"2024-10-29T11:47:53.812Z","version":"6.3.6"}
```

**Comment by simonbjorzen-ts** [comment]
Additional log error:

```
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:463:23\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-10-29T12:28:56.412Z","version":"6.3.6"}
```

**Comment by security-penguin** [comment]
@simonbjorzen-ts can you share how you solved this as I am facing this issue.

**Comment by simonbjorzen-ts** [comment]
@security-penguin this issue helped, https://github.com/OpenCTI-Platform/opencti/issues/7381
Our issue ended up being related to an overloaded system which was resolved by separating the different platform components to separate containers.
