### ISSUE TITLE
 Platform start init user failed

### ISSUE THREAD

**Issue by 0915070217** [LuatixHQ/opencti#8839]
## Environment
docker start 
OpenCTI version: 6.3.7

opencti-1  | {"category":"APP","client":{"_index":"opencti_internal_objects-000001","account_status":"Active","api_token":"4ca93cb0-da63-4354-acd7-52a7b33fe555","base_type":"ENTITY","confidence":100,"created_at":"2024-10-30T05:05:19.290Z","creator_id":["6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"],"description":"Principal admin account","entity_type":"User","external":true,"firstname":"Admin","i_attributes":[{"confidence":100,"name":"password","updated_at":"2024-10-31T03:21:48.501Z","user_id":"6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"},{"confidence":100,"name":"api_token","updated_at":"2024-10-31T03:21:48.501Z","user_id":"6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"},{"confidence":100,"name":"user_email","updated_at":"2024-10-31T03:21:48.501Z","user_id":"6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"},{"confidence":100,"name":"standard_id","updated_at":"2024-10-31T03:21:48.501Z","user_id":"6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"}],"id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","internal_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","language":"auto","lastname":"OpenCTI","member-of":["1547cfa0-6fd7-4527-9975-c864d0fba40d"],"name":"admin","parent_types":["Basic-Object","Internal-Object"],"personal_notifiers":["f4ee7b33-006a-4b0d-b57d-411ad288653d","44fcf1f4-8e31-4b31-8dbc-cd6993e1b822"],"rel_member-of.internal_id":["1547cfa0-6fd7-4527-9975-c864d0fba40d"],"sort":[1730264719290],"standard_id":"user--c058561f-1c3a-53b3-82a0-1e262bf91bf3","theme":"default","updated_at":"2024-10-31T03:21:48.453Z","user_confidence_level":{"max_confidence":100,"overrides":[]},"user_email":"hunt@163.com"},"level":"debug","message":"Building complete user","source":"backend","stack":"Error: \n    at buildCompleteUser (/opt/opencti/build/src/domain/user.js:1308:28)\n    at findById (/opt/opencti/build/src/domain/user.js:167:10)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at initAdmin (/opt/opencti/build/src/domain/user.js:1578:25)\n    at initializeAdminUser (/opt/opencti/build/src/config/providers.js:48:7)\n    at platformInit (/opt/opencti/build/src/initialization.js:121:7)\n    at platformStart (/opt/opencti/build/src/boot.js:29:7)","timestamp":"2024-10-31T03:27:53.809Z","version":"6.3.7"}

## Reproducible Steps
docker-compose start opencti
![image](https://github.com/user-attachments/assets/d3f38711-9e7f-49cd-abd4-84fa03e335b5)

**Comment by nino-filigran** [comment]
@0915070217 can you please be a little more specific regarding your problem, and provide some explanations regarding what you're trying to do and how you reached there?

**Comment by 0915070217** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，你发的邮件我收到了，谢谢！

**Comment by nino-filigran** [comment]
Closing this ticket for inactivity purpose.

**Comment by 0915070217** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，你发的邮件我收到了，谢谢！
