### ISSUE TITLE
In case of SAML auth failure, platform is stuck and not redirecting to login with error message

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#9053]
## Description

In case of SAML auth failure, platform is stuck and not redirecting to login with error message

```
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:498:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}],"level":"error","message":"Engine unhandled rejection","source":"backend","timestamp":"2024-11-18T10:33:04.280Z","version":"6.3.13"}
```

**Comment by jercherng** [comment]
@SamuelHassine I started running into this issue after updating to 6.4.0. Do you know what other versions are affected?

**Comment by PeeBee66** [comment]
6.3.13 as well

```
{
  "category": "APP",
  "errors": [
    {
      "attributes": {
        "genre": "TECHNICAL",
        "http_status": 500,
        "reason": "Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:498:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
      },
      "message": "Engine unhandled rejection",
      "name": "UNKNOWN_ERROR",
      "stack": "GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process. (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:519:28)\n    at process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"
    }
  ],
  "level": "error",
  "message": "Engine unhandled rejection",
  "source": "backend",
  "timestamp": "2024-11-20T22:05:38.880Z",
  "version": "6.3.13"
}
```

**Comment by silvareal** [comment]
I am currently experiencing this issue, @SamuelHassine , how where you able to fix this?

**Comment by legoguy1000** [comment]
We're getting this on 6.4.3 too with OpenID. I'm also getting a bunch of but IDK if thats related
```
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"provider":"Rule manager"},"message":"Redis stream consume fail","name":"DATABASE_ERROR","stack":"GraphQLError: Redis stream consume fail\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:57:48)\n    at processStep (/opt/opencti/build/src/database/redis.ts:709:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:720:13)"},{"attributes":{"documentId":"rule_engine_settings","entityType":"","genre":"TECHNICAL","http_status":500},"message":"Update indexing fail","name":"DATABASE_ERROR","stack":"GraphQLError: Update indexing fail\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:57:48)\n    at /opt/opencti/build/src/database/engine.js:3457:11\n    at async Promise.all (index 0)\n    at updateAttributeMetaResolved (/opt/opencti/build/src/database/middleware.js:2158:7)\n    at ruleStreamHandler (/opt/opencti/build/src/manager/ruleManager.ts:267:3)\n    at processStreamResult (/opt/opencti/build/src/database/redis.ts:649:3)\n    at processStep (/opt/opencti/build/src/database/redis.ts:706:9)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:720:13)"},{"message":"Request timed out","name":"TimeoutError","stack":"TimeoutError: Request timed out\n    at FHt._request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:630:36)\n    at /opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:707:22\n    at FHt.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:704:14)\n    at QKe.UpdateApi [as update] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/update.ts:83:10)\n    at async Promise.all (index 0)\n    at updateAttributeMetaResolved (/opt/opencti/build/src/database/middleware.js:2158:7)\n    at ruleStreamHandler (/opt/opencti/build/src/manager/ruleManager.ts:267:3)\n    at processStreamResult (/opt/opencti/build/src/database/redis.ts:649:3)\n    at processStep (/opt/opencti/build/src/database/redis.ts:706:9)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:720:13)"}],"level":"error","message":"Redis stream consume fail","source":"backend","timestamp":"2024-12-10T21:21:28.502Z","version":"6.4.3"}
```

**Comment by dominictory** [comment]
We're seeing this same error in 6.4.2 but we don't use SAML.
```
ERR Engine unhandled rejection | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500,"reason":"Error: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (node:_http_outgoing:655:11)\n    at ServerResponse.header (/opt/opencti/build/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:174:12)\n    at ServerResponse.json (/opt/opencti/build/node_modules/express/lib/response.js:278:15)\n    at ServerResponse.send (/opt/opencti/build/node_modules/express/lib/response.js:162:21)\n    at /opt/opencti/build/src/http/httpPlatform.js:490:21\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},"message":"Engine unhandled rejection","name":"UNKNOWN_ERROR","stack":"GraphQLError: Engine unhandled rejection\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n    at process.<anonymous> (/opt/opencti/build/src/boot.js:61:16)\n    at process.emit (node:events:518:28)\n    at process.D9r.process.emit (/opt/opencti/build/node_modules/source-map-support/source-map-support.js:516:21)\n    at emitUnhandledRejection (node:internal/process/promises:250:13)\n    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)\n    at processPromiseRejections (node:internal/process/promises:470:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:32)"}] source=backend timestamp=2024-12-19T13:59:16.632Z version=6.4.2
```

**Comment by richard-julien** [comment]
Partially fixed with correct redirection.
Need to investigate more about why the flash cookie is not working anymore

**Comment by aHenryJard** [comment]
Tested today on current master: on SAML error user is correctly redirected to login page with a message "Invalid authentication, please ask your administrator". So I'm closing as cannot reproduce, feel free to reopen if needed.
