### ISSUE TITLE
Error when loading knowledge history

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#9101]
When trying to view History of a user, it spins, then I get `An unknown error occurred...` in the UI. Console shows attached. This is on 6.3.12. When trying to view the Activity page, I see audit history, but ticking Include knowledge produces a similar outcome. The following error is also seen in platform logs:
```
1970/01/01 09:14AM ERR Fail to execute engine pagination | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500,"query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"should":[{"terms":{"authorized_members.id.keyword":["ALL","88ec0c6a-13ce-5e39-b486-354fe4a7084f","8763664e-d84b-4ed1-942d-54891bbba7a8","e0045918-b301-487e-aaf1-c735fd28adde","82405095-1cdd-4aba-889c-1ab20cfbca4a"]}},{"bool":{"must_not":{"exists":{"field":"authorized_members"}}}}]}},{"bool":{"minimum_should_match":2,"should":[{"bool":{"minimum_should_match":1,"should":[{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["user_id"],"query":"\"54992603-ab16-4e69-8f33-370636b78a69\""}}]}},{"bool":{"minimum_should_match":1,"should":[{"query_string":{"fields":["context_data.id"],"query":"\"54992603-ab16-4e69-8f33-370636b78a69\""}}]}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["entity_type.keyword","parent_types.keyword"],"query":"History"}},{"multi_match":{"fields":["entity_type.keyword","parent_types.keyword"],"query":"Activity"}}]}}]}}],"must_not":[]}},"size":10,"sort":[{"timestamp":{"missing":0,"order":"desc"}},{"standard_id.keyword":"asc"}]},"index":"opencti_history*","track_total_hits":true}},"message":"Fail to execute engine pagination","name":"DATABASE_ERROR","stack":"GraphQLError: Fail to execute engine pagination\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:57:48)\n    at /opt/opencti/build/src/database/engine.js:3299:15"},{"message":"Request timed out","name":"TimeoutError","stack":"TimeoutError: Request timed out\n    at fqt._request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:630:36)\n    at /opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:704:22\n    at fqt.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:701:14)\n    at mKe.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:96:10)"}] inner_relation_creation=0 operation=Unspecified query_attributes=[[{"arguments":[[{"is_empty":true,"name":"types","type":"Variable"}],[{"is_empty":true,"name":"first","type":"Variable"}],[{"is_empty":true,"name":"orderBy","type":"Variable"}],[{"is_empty":true,"name":"orderMode","type":"Variable"}],[{"is_empty":true,"name":"filters","type":"Variable"}],[{"is_empty":true,"name":"search","type":"Variable"}],[{"is_empty":true,"name":"after","type":"Variable"}]],"name":"audits"}]] size=366 source=backend timestamp=2024-11-19T14:53:44.780Z type=READ_ERROR user={"group_ids":["e0045918-b301-487e-aaf1-c735fd28adde"],"ip":"::ffff:10.212.134.202","organization_ids":["8763664e-d84b-4ed1-942d-54891bbba7a8"],"referer":"https://10.254.202.12/dashboard/settings/accesses/users/54992603-ab16-4e69-8f33-370636b78a69","socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}} version=6.3.12
```
![Image](https://github.com/user-attachments/assets/7ca3dbab-f71c-4440-9dff-b246c4bf6a83)
![Image](https://github.com/user-attachments/assets/07838685-8a33-4e46-9508-00628da7250b)

**Comment by romain-filigran** [comment]
Hi @dominictory : I was unable to reproduce your problem with the latest version of OpenCTI (6.4.1). Can you try upgrading to the latest version to see if the problem is still there?
The "Fail to execute engine pagination" could also indicate performance issue with your elasticsearch stack.

**Comment by dominictory** [comment]
> Hi [@dominictory](https://github.com/dominictory) : I was unable to reproduce your problem with the latest version of OpenCTI (6.4.1). Can you try upgrading to the latest version to see if the problem is still there? The "Fail to execute engine pagination" could also indicate performance issue with your elasticsearch stack.

Thanks, we went up to 6.4.0 since raising this and we can see activity per user, however Activity page including knowledge still throws the error. It always seems to be this particular page we have trouble with, we see issues with opencti_history indexes fairly regularly but not others.

**Comment by nino-filigran** [comment]
@dominictory I'm going through old issues to ensure we have closed them or provided needed help & I see this one still open. Do you still encounter issues?

**Comment by dominictory** [comment]
> [@dominictory](https://github.com/dominictory) I'm going through old issues to ensure we have closed them or provided needed help & I see this one still open. Do you still encounter issues?

Hi, it does still happen sometimes but not very often. Happy to close as it isn't really an issue for me anymore.
