### ISSUE TITLE
[CI] Flaky e2e test on background tasks

### ISSUE THREAD

**Issue by lndrtrbn** [LuatixHQ/opencti#9147]
## Description

It appends that test `backgroundTask/backgroundTask.spec.ts` fails on CI

I do not have much info to give.

## Expected Output

Test pass every time

**Comment by SouadHadjiat** [comment]
recent example on a PR build https://drone.filigran.io/OpenCTI-Platform/opencti/28640/1/16
```
1) [chromium] › backgroundTask/backgroundTask.spec.ts:25:5 › Verify background tasks execution ───

    Test timeout of 200000ms exceeded.

    Error: page.waitForResponse: Test timeout of 200000ms exceeded.

       at model/taskPopup.pageModel.ts:17

      15 |     // Need to wait the request that fetch labels (in background task popup) - but only on the first call...
      16 |     if (firstTime) {
    > 17 |       await this.page.waitForResponse((resp) => resp.url().includes('/graphql') && resp.status() === 200);
         |                       ^
      18 |     }
      19 |
      20 |     await this.page.getByText(labelName).click();

        at TaskPopup.launchAddLabel (/drone/src/opencti-platform/opencti-front/tests_e2e/model/taskPopup.pageModel.ts:17:23)
        at /drone/src/opencti-platform/opencti-front/tests_e2e/backgroundTask/backgroundTask.spec.ts:42:3

```
Build result: https://filigran.jfrog.io/ui/builds/opencti-build/28640/1732899297271/published/opencti-build?buildRepo=artifactory-build-info

**Comment by aHenryJard** [comment]
Closing because should be solved by https://github.com/OpenCTI-Platform/opencti/pull/10297

Feel free to reopen if it's coming again after release 6.6 is out.

**Comment by aHenryJard** [comment]
Reopening, it's still happening

**Comment by aHenryJard** [comment]
I think it's good now
