### ISSUE TITLE
[Connector Error Display] Error "Id loading expect only one response" not supported

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#9233]
## Description

The "Id loading expect only one response" error are not supported by the new feature of displaying errors in a structured way. I mean that the fields are not filled (i.e. we cannot know the source of the problem) and the displayed text is the JSON error.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

It's quite hard to generate this error intentionally

Steps to create the smallest reproducible scenario:
1. Make sure to have a STIX ID on two different entities, e.g. the "malware ID--..." on two different Malware. This can be done only by manipulating Elastic directly (this situation could occur in older versions).
2. Send a bundle in ingestion with a relation having this malware ID as "from" for example
-> the error will be raised

#### Something like that

![Image](https://github.com/user-attachments/assets/2208b392-f1a4-48d2-92c3-dc7d2e2fdde5)

## Actual Output

![Image](https://github.com/user-attachments/assets/9a80ba74-7c48-46e0-9f42-7e21765ff555)

![Image](https://github.com/user-attachments/assets/e8b55eac-c51b-4e0e-99a1-4ab4ff48911b)

## Additional information

Another issue on the same subject (but another error type): https://github.com/OpenCTI-Platform/opencti/issues/9163

**Comment by labo-flg** [comment]
Thanks for the notice !
Indeed we expected some errors to be unstructured and difficult to parse. The error display tries its best to show what it can.
In fact, the error `source` is not a mandatory field when raising errors, so here it's not a matter of display but really a matter of raising properly this error with more context.

**Comment by frapuks** [comment]
- i have 2 malware with the same stix ID
- i manually launch a python script to create a relation between a report and 1 of these malwares
- i don't have the same error : `Input resolve refs expect single value`
```
{"category":"APP","errors":[{"attributes":{"doc_code":"ELEMENT_ID_COLLISION","genre":"BUSINESS","http_status":500,"key":"to","values":[{"_id":"dde89338-eb9c-4d47-b1f6-8821d4d31058","_index":"opencti_stix_domain_objects-000001","
architecture_execution_envs":[],"base_type":"ENTITY","confidence":100,"created":"2024-10-22T07:14:52.203Z","created_at":"2024-10-22T07:14:52.203Z","creator_id":["88ec0c6a-13ce-5e39-b486-354fe4a7084f"],"description":"","entity_ty
pe":"Malware","first_seen":"1970-01-01T00:00:00.000Z","i_aliases_ids":[],"i_group":{"destKey":"to","id":"malware--a3027859-b778-5708-b191-93c2045bda1b","multiple":false},"id":"dde89338-eb9c-4d47-b1f6-8821d4d31058","implementatio
n_languages":[],"internal_id":"dde89338-eb9c-4d47-b1f6-8821d4d31058","is_family":false,"lang":"en","last_seen":"5138-11-16T09:46:40.000Z","malware_types":[],"modified":"2024-10-22T07:14:52.203Z","name":"malware 1","object":"cb92
494e-2a2e-4087-ab9b-eeb845688215","parent_types":["Basic-Object","Stix-Object","Stix-Core-Object","Stix-Domain-Object"],"rel_object.internal_id":["cb92494e-2a2e-4087-ab9b-eeb845688215"],"revoked":false,"sort":[1729581292203],"st
andard_id":"malware--a3027859-b778-5708-b191-93c2045bda1b","updated_at":"2024-10-22T07:14:52.203Z","x_opencti_stix_ids":[]},{"_id":"88a8f2c2-8b22-4a6b-9ec6-14c40b756e16","_index":"opencti_stix_domain_objects-000001","architectur
e_execution_envs":[],"base_type":"ENTITY","confidence":100,"created":"2024-12-05T09:46:31.741Z","created_at":"2024-12-05T09:46:31.741Z","creator_id":["88ec0c6a-13ce-5e39-b486-354fe4a7084f"],"description":"","entity_type":"Malwar
e","first_seen":"1970-01-01T00:00:00.000Z","i_aliases_ids":[],"i_group":{"destKey":"to","id":"malware--a3027859-b778-5708-b191-93c2045bda1b","multiple":false},"id":"88a8f2c2-8b22-4a6b-9ec6-14c40b756e16","implementation_languages
":[],"internal_id":"88a8f2c2-8b22-4a6b-9ec6-14c40b756e16","is_family":false,"lang":"en","last_seen":"5138-11-16T09:46:40.000Z","malware_types":[],"modified":"2024-12-05T09:46:31.741Z","name":"malware 2","parent_types":["Basic-Ob
ject","Stix-Object","Stix-Core-Object","Stix-Domain-Object"],"revoked":false,"sort":[1733391991741],"standard_id":"malware--a3027859-b778-5708-b191-93c2045bda1b","updated_at":"2024-12-05T09:46:31.741Z","x_opencti_stix_ids":[]}]}
,"message":"Input resolve refs expect single value","name":"UNSUPPORTED_ERROR","stack":"GraphQLError: Input resolve refs expect single value\n    at error (C:\\Users\\FrancoisGrunert\\IdeaProjects\\opencti\\opencti-platform\\ope
ncti-graphql\\src\\config\\errors.js:7:10)\n    at UnsupportedError (C:\\Users\\FrancoisGrunert\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\config\\errors.js:88:51)\n    at C:\\Users\\FrancoisGrunert\\IdeaPro
jects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\middleware.js:790:15\n    at Array.map (<anonymous>)\n    at inputResolveRefsFn (C:\\Users\\FrancoisGrunert\\IdeaProjects\\opencti\\opencti-platform\\opencti-grap
hql\\src\\database\\middleware.js:784:58)\n    at createRelationRaw (C:\\Users\\FrancoisGrunert\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\middleware.js:2750:25)\n    at createRelation (C:\\Users\\
FrancoisGrunert\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\middleware.js:2890:16)\n    at addStixCoreRelationship (C:\\Users\\FrancoisGrunert\\IdeaProjects\\opencti\\opencti-platform\\opencti-graph
ql\\src\\domain\\stixCoreRelationship.js:100:19)"}],"inner_relation_creation":0,"level":"error","message":"Input resolve refs expect single value","operation":"Unspecified","query_attributes":[[{"arguments":[[{"is_empty":true,"n
ame":"input","type":"Variable"}]],"name":"stixCoreRelationshipAdd"}]],"size":502,"source":"backend","time":32,"timestamp":"2024-12-05T10:17:28.979Z","type":"WRITE_ERROR","user":{"group_ids":["a85d209b-611e-4e8a-826e-ca0fe64602bf"],"ip":"::1","organization_ids":[],"socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}},"version":"6.4.2"}
```

**Comment by Lhorus6** [comment]
Ok I see, the root cause of the error is the same but not the same error.

My error occurs when the ImportDocument connector tries to create a workbench. It uses the malware ID's that has a duplicate. 

Maybe trying to retrieve the entity using its ID will raise this error.
