### ISSUE TITLE
Opencti to openbas integration issue

### ISSUE THREAD

**Issue by vinayakcyber** [LuatixHQ/opencti#9271]
## Description

I am trying to simulate a scenario, from opencti to openbas.

Getting the following error:

```
 opencti_1                                         | {"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Error querying OpenBAS","name":"DATABASE_ERROR","stack":"GraphQLError: Error querying OpenBAS\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:57:48)\n    at createScenario (/opt/opencti/build/src/database/xtm-obas.ts:116:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at generateOpenBasScenario (/opt/opencti/build/src/modules/xtm/xtm-domain.js:101:24)"},{"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at settle (/opt/opencti/build/node_modules/axios/lib/core/settle.js:19:12)\n    at Unzip.handleStreamEnd (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:599:11)\n    at Unzip.emit (node:events:530:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at XYt.request (/opt/opencti/build/node_modules/axios/lib/core/Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at createScenario (/opt/opencti/build/src/database/xtm-obas.ts:65:33)\n    at generateOpenBasScenario (/opt/opencti/build/src/modules/xtm/xtm-domain.js:101:24)"}],"inner_relation_creation":0,"level":"error","message":"Error querying OpenBAS","operation":"Unspecified","query_attributes":[[{"arguments":[[{"is_empty":true,"name":"id","type":"Variable"}],[{"is_empty":true,"name":"interval","type":"Variable"}],[{"is_empty":true,"name":"selection","type":"Variable"}],[{"is_empty":true,"name":"simulationType","type":"Variable"}],[{"is_empty":true,"name":"useAI","type":"Variable"}],[{"is_empty":true,"name":"filters","type":"Variable"}]],"name":"obasContainerGenerateScenario"}]],"size":177,"source":"backend","time":583,"timestamp":"2024-12-09T15:56:40.129Z","type":"WRITE_ERROR","user":{"group_ids":["d5d79a28-95cc-4fa6-b355-822a4b3544a3"],"ip":"::ffff:10.34.20.184","organization_ids":["e6609312-ad38-44c0-860e-2017b686c66f"],"referer":"http://opencti:8080/dashboard/analyses/reports/ed67bef1-68ba-4b91-8159-93ae09c7062d","socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}},"version":"6.4.1"}
```

## Environment

1. OS (where OpenCTI server runs): Ubuntu 24.04
2. OpenCTI version: 6.4.1
3. OpenCTI client: frontend
4. Other environment details: 
      - XTM__OPENBAS_URL=http://openbas-ip:8080/api
      - XTM__OPENBAS_TOKEN=7006f266-317f-45a9-8c26-b1e242280668

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Access a report in Opencti, which has same attack-pattern as available in openbas
2. Click Simulate button
3. Error: Error querying OpenBAS

## Expected Output

Simulation should be created on OpenBas side

## Actual Output

Just got the error

**Comment by vinayakcyber** [comment]
Fixed, had to remove /api
