### ISSUE TITLE
Retention policy bulk deletion times out

### ISSUE THREAD

**Issue by rvo-itpg** [LuatixHQ/opencti#9276]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description
After updating form `6.3.13` to `6.4.2` and upgrading elastic from `8.13.4-debian-12-r0` to `8.15.3-debian-12-r0` it became clear that my elastic cluster became a bit unstable. I saw that my data usage was quite large so I decided to implement a retention policy for a lot of knowledge items that are older than 60 days. However, for some reason it keeps timing out the bulk requests. I have tried quite a bit (Increasing data nodes & adding more CPU, but to no avail) I have googled quite a bit, but can't find anything that would help. If anyone can help it would be much appreciated.

The error:
```
{
  "category": "APP",
  "errors": [
    {
      "attributes": {
        "genre": "TECHNICAL",
        "http_status": 500
      },
      "message": "Request timed out",
      "name": "UNKNOWN_ERROR",
      "stack": "GraphQLError: Request timed out\n at error (/opt/opencti/build/src/config/errors.js:7:10)\n at UnknownError (/opt/opencti/build/src/config/errors.js:81:47)\n at Object._logWithError (/opt/opencti/build/src/config/conf.js:238:17)\n at Object.error (/opt/opencti/build/src/config/conf.js:247:48)\n at deleteFn (/opt/opencti/build/src/manager/retentionManager.ts:94:18)\n at processTicksAndRejections (node:internal/process/task_queues:95:5)"
    },
    {
      "message": "Request timed out",
      "name": "TimeoutError",
      "stack": "TimeoutError: Request timed out\n at wHt._request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:630:36)\n at /opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:707:22\n at wHt.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:704:14)\n at WKe.BulkApi [as bulk] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/bulk.ts:82:10)\n at elRemoveRelationConnection (/opt/opencti/build/src/database/engine.js:3577:9)\n at elDeleteElements (/opt/opencti/build/src/database/engine.js:3762:3)\n at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3253:7)\n at deleteElementById (/opt/opencti/build/src/database/middleware.js:3275:32)\n at deleteElement (/opt/opencti/build/src/manager/retentionManager.ts:37:5)\n at deleteFn (/opt/opencti/build/src/manager/retentionManager.ts:83:11)"
    }
  ],
  "id": "2748463b-5da2-4b9c-b751-d89cfd8f1730",
  "level": "error",
  "manager": "RETENTION_MANAGER",
  "message": "Request timed out",
  "source": "backend",
  "timestamp": "2024-12-10T10:01:51.9830000Z",
  "version": "6.4.2"
}
```

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: 6.4.2
3. OpenCTI client: n.a.
4. K8S version: 1.27.16
5. Other environment details:
  * Runs on AKS.
  * Currently have 1 master & 5 Data nodes.
  * Each node has the following resources:
    * CPU: Request: 1 | Limit: 2
    * RAM: Request: 2Gi | Limit: 2Gi
    * Storage: 8Gi

## Reproducible Steps

Sadly due to a pretty unique environment I don't think I can give reproduction steps. However, I can provide logs/request results.

## Additional information

Info about all indencies: [Link to gist](https://gist.github.com/rvo-itpg/921246738a9446bba2764234d04f0719)

**Comment by rvo-itpg** [comment]
After investigating a bit more I have found the following. It appears the `_bulk` delete queries take a long time. This causes the GraphQL query to OpenCTI that the `RETENTION_MANAGER` does to time out. I can see by using `_cat/thread_pool/write?v=true` that requests are being aded to the queue. However, my number of documents do not change. This suggests that somehow Elastic is stuck. But when I manually delete something in Elastic it seems to delete fine.

**Comment by alice-debra** [comment]
Hello @rvo-itpg, 
We’re following up to see if you still need an answer to this question. If you still need help with this, don't hesitate to ask on our Slack: https://filigran-community.slack.com/. 
Please let us know at your earliest convenience. Thank you again for your valuable feedback. We truly appreciate your contribution in helping us improve.
Kind regards,
Alice

**Comment by rvo-itpg** [comment]
Hello @alice-debraq ,
The problem I had I have solved somewhat. I could manually create a task to delete a bulk amount from our environment. It took several weeks but it is now clean enough that the retention policy works.
