### ISSUE TITLE
Map container is already initialized error shown in logs when trying to filter entities for creating victimology relationship for intrusion set

### ISSUE THREAD

**Issue by toyray** [LuatixHQ/opencti#9449]
## Description

When trying to create a victimlogy relationship for a country or sector to a intrusion set via the website, after a country name is entered into the search box and pressing Enter, the error "An unknown error occurred. Please provide a support package to your administrator or OpenCTI maintainers" is displayed.

We are currently working around this by refreshing the page when this happens, which will display the correct entries when the bottom `+` button (for creating relationship) is pressed.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04.4 LTS
2. OpenCTI version: OpenCTI 6.3.13
3. OpenCTI client: N/A
4. Other environment details: Running in Docker container with modified version of the OpenCTI dockerfiles (same Docker image versions, slightly different environment variables and configuration)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. View an intrusion set via the left sidebar
2. Click on Knowledge tab
3. Click on Victimology on right sidebar
4. Click on + button on bottom right to create a relationship
5. Enter a country name .e.g. United States and press Enter
6. Error message "An unknown error occurred. Please provide a support package to your administrator or OpenCTI maintainers" is dsiplayed
7. Refresh page in browser
8. Click on + button on bottom right to ceate a relationship again
9. List is populated with the correct entries e.g. United States appears in the list.

## Expected Output

List of entities should be displayed without showing error message

## Actual Output

Error message is shown and page has to be refreshed before the list of entities is shown for creating the relationship.

## Additional information

We were previously on 6.2.18 and did not observe this issue.

The logs from the OpenCTI container, replaced the host IP with `SERVER_IP`.
```
{
category: "APP",
codeStack: "Error: Map container is already initialized.
    at oe._initContainer (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:27828:42513)
    at oe.initialize (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:27828:30325)
    at new oe (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:27828:4386)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:27828:159049
    at Kxt (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:24749)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33603)
    at Mui (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:31768)
    at Mui (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:31795)
    at Mui (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:31795)
    at Mui (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:31795)",
componentStack: "
    at div
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at div
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:321:129904
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:321:130237
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at injectIntl(n)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at div
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:244:83603
    at div
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:321:129904
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at injectIntl(n)
    at div
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:361:45470
    at div
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:361:45470
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:321:129904
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at injectIntl(n)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
 at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at div
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at div
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Suspense
 at TAm (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:250769:6812)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Suspense
    at tOm (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:262466:26731)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Suspense
    at main
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:117:63851
    at div
  at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:117:63851
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Suspense
    at $s0 (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:307822:25935)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Suspense
    at qbi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:307822:26498)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:483:115811
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)
    at Qs0
    at Suspense
    at Nsi (http://SERVER_IP:8080/static/js/front-R6E5RZBL.js:8:33619)",
level: "error",
message: "Error: Map container is already initialized.",
source: "frontend",
timestamp: "2024-12-23T06:56:14.691Z",
version: "6.3.13"
}
```

## Screenshots (optional)

N/A

**Comment by romain-filigran** [comment]
Reproduced in version 6.4.5. 
Moreover, the "search these results" search form in the "Create a relationship" drawer is not reinitialized.

**Comment by labo-flg** [comment]
Quick comment : this error comes from leaflet, the dependency used for the locations minimap widget.
